// Generated by aware_experience language contracts. Do not edit by hand.

typedef ExperienceViewModelDecoder = Object Function(Map<String, dynamic> json);

class ExperienceViewModelContract {
  const ExperienceViewModelContract({
    required this.viewRef,
    required this.viewKey,
    required this.stateModelRef,
    required this.version,
    required this.decode,
  });

  final String viewRef;
  final String viewKey;
  final String stateModelRef;
  final String version;
  final ExperienceViewModelDecoder decode;
}

const awareMetaExperienceViewModelContracts = <ExperienceViewModelContract>[
];

final awareMetaExperienceViewModelDecoders =
    <String, ExperienceViewModelDecoder>{
};
