aware = 1

[package]
package_name = "experience-ontology"
fqn_prefix = "aware_experience"
kind = "ontology"
version_number = 1
title = "Experience"
description = "SSOT canonical (.aware) sources for experience."

[build]
environment_slug = "aware_experience"

[[dependencies]]
package_name = "attention-ontology"

[[dependencies]]
package_name = "api-ontology"

[[dependencies]]
package_name = "meta-ontology"

[[dependencies]]
package_name = "reactivity-ontology"

[[dependencies]]
package_name = "sdk-ontology"

[[dependencies]]
package_name = "storage-ontology"

[[dependencies]]
package_name = "identity-ontology"

[[dependencies]]
package_name = "code-ontology"

[[dependencies]]
package_name = "environment-ontology"
