# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from typing import cast
from uuid import UUID

# Third-party
from pydantic import BaseModel

# Code
from aware_code.types import JsonArray, JsonObject

# Meta
from aware_meta.graph.instance.builder import build_object_instance_graph
from aware_meta.graph.instance.diff_orm import build_object_instance_graph_changes_from_orm_change_set
from aware_meta.runtime.handler_executor.argument_coercion import coerce_meta_handler_call_kwargs
from aware_meta.runtime.handler_executor.contracts import MetaGraphHandlerExecutionRequest, MetaGraphPreState
from aware_meta.runtime.handler_executor.language_handler import (
    MetaGraphGeneratedInvocationHandlerCallable,
    MetaGraphGeneratedLanguageHandlerCallable,
    MetaGraphGeneratedLanguageHandlerKey,
    MetaGraphLanguageHandlerExecution,
    MetaGraphLanguageHandlerExecutionError,
)
from aware_meta.runtime.handler_executor.pre_state import (
    MetaGraphEmptyLaneBootstrap,
    MetaGraphEmptyLaneBootstrapCallable,
)
from aware_meta.runtime.oig_model_reifier import reify_oig_root_model
from aware_meta.runtime.value_resolvers import default_meta_enum_option_resolver

# Meta Ontology
from aware_meta_ontology.class_.class_config import ClassConfig
from aware_meta_ontology.graph.instance.object_instance_graph import ObjectInstanceGraph

# Orm
from aware_orm.models.orm_model import ORMModel
from aware_orm.registry import ORMModelRegistry
from aware_orm.session.change_collector import current_change_collector


def _bind_keyword_payload(
    *,
    positional: JsonArray,
    keyword: JsonObject,
    field_names: tuple[str, ...],
    function_name: str,
) -> JsonObject:
    if len(positional) > len(field_names):
        raise MetaGraphLanguageHandlerExecutionError(
            "Too many positional arguments for generated Meta language handler: "
            f"function_name={function_name} have={len(positional)} max={len(field_names)}"
        )
    payload = JsonObject(dict(keyword))
    unknown_names = sorted(set(payload) - set(field_names))
    if unknown_names:
        raise MetaGraphLanguageHandlerExecutionError(
            "Unknown generated Meta language-handler argument(s): "
            f"function_name={function_name} names={unknown_names}"
        )
    for position, value in enumerate(positional):
        field_name = field_names[position]
        if field_name in payload:
            raise MetaGraphLanguageHandlerExecutionError(
                "Generated Meta language-handler argument provided twice: "
                f"function_name={function_name} name={field_name}"
            )
        payload[field_name] = value
    return payload


def _assert_constructor_owner_class(*, request: MetaGraphHandlerExecutionRequest, expected_class_name: str) -> None:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )


def _post_oig_with_root_model(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    root_model: ORMModel,
) -> ObjectInstanceGraph:
    before_oig = pre_state.before_oig
    return build_object_instance_graph(
        root_instance=root_model,
        object_config_graph=request.execution_plan.index.ocg,
        object_projection_graph=request.execution_plan.object_projection_graph,
        key=before_oig.key or str(before_oig.id),
        name=before_oig.name or request.execution_plan.object_projection_graph.name,
        description=before_oig.description or "",
        oig_id=before_oig.id,
        enum_option_resolver=default_meta_enum_option_resolver,
    )


def _changes_from_current_collector(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
):
    collector = current_change_collector()
    if collector is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires an active ORM change collector."
        )
    change_set = collector.snapshot()
    changes = tuple(
        build_object_instance_graph_changes_from_orm_change_set(
            before_oig=pre_state.before_oig,
            object_instance_graph_identity_id=(request.staged_call.lane_scope.object_instance_graph_identity_id),
            ocg=request.execution_plan.index.ocg,
            opg=request.execution_plan.object_projection_graph,
            change_set=change_set,
            class_configs_by_id=dict(request.execution_plan.index.class_configs_by_id),
            relationships_by_id=dict(request.execution_plan.index.relationships_by_id),
            enum_option_resolver=default_meta_enum_option_resolver,
        )
    )
    constructed_class_instance_ids = tuple(
        class_change.class_instance_id
        for root_change in changes
        for class_change in root_change.class_instance_changes
        if class_change.change.type.value == "create"
    )
    return changes, constructed_class_instance_ids


def _root_and_target_models_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    expected_class_name: str,
) -> tuple[ORMModel, ORMModel]:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )
    target_object_id = (
        pre_state.target_object_id
        or request.execution_plan.target_object_id
        or request.request.target_object_id
        or pre_state.root_object_id
    )
    if target_object_id is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance handler requires a target object id.")
    root_model = _root_model_from_pre_state(request=request, pre_state=pre_state)
    target_source_object_id = _target_source_object_id_from_pre_state(
        pre_state=pre_state,
        target_class_instance_id=target_object_id,
    )
    target = _find_orm_model_by_id(root_model, target_source_object_id)
    target_orm_class = ORMModelRegistry.get_class_by_class_config_id(owner_class_config.id)
    if target_orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve ORM class: "
            f"class_config_id={owner_class_config.id} class_name={owner_class_config.name}"
        )
    if not isinstance(target, target_orm_class):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve target model in "
            "the rooted projection model: "
            f"class_name={owner_class_config.name} target_object_id={target_object_id}"
        )
    return root_model, target


def _root_model_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
) -> ORMModel:
    root_orm_class = _root_orm_class_from_projection(request)
    root_object_id = _root_source_object_id_from_pre_state(pre_state)
    root = reify_oig_root_model(
        index=request.execution_plan.index,
        opg=request.execution_plan.object_projection_graph,
        oig=pre_state.before_oig,
        model_type=root_orm_class,
        root_id=root_object_id,
        branch_id=request.execution_plan.staged_call.lane_scope.domain_branch_id,
    )
    if root is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot reify rooted projection model: " f"root_object_id={root_object_id}"
        )
    return root


def _root_orm_class_from_projection(
    request: MetaGraphHandlerExecutionRequest,
) -> type[ORMModel]:
    root_nodes = [
        node for node in request.execution_plan.object_projection_graph.object_projection_graph_nodes if node.is_root
    ]
    if len(root_nodes) != 1:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler requires exactly one OPG root node: "
            f"have={len(root_nodes)} "
            f"object_projection_graph_id={request.execution_plan.object_projection_graph.id}"
        )
    orm_class = ORMModelRegistry.get_class_by_class_config_id(root_nodes[0].class_config_id)
    if orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve root ORM class: " f"class_config_id={root_nodes[0].class_config_id}"
        )
    return cast(type[ORMModel], orm_class)


def _root_source_object_id_from_pre_state(pre_state: MetaGraphPreState):
    if pre_state.root_object_id is not None:
        return pre_state.root_object_id
    root_class_instance = pre_state.before_oig.root_class_instance
    if root_class_instance is None and pre_state.before_oig.root_class_instance_id is not None:
        root_class_instance = next(
            (
                instance
                for instance in pre_state.before_oig.class_instances
                if instance.id == pre_state.before_oig.root_class_instance_id
            ),
            None,
        )
    if root_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler cannot resolve root source object id.")
    return root_class_instance.source_object_id


def _target_source_object_id_from_pre_state(
    *,
    pre_state: MetaGraphPreState,
    target_class_instance_id,
):
    if pre_state.oig_index is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler requires pre-state OIG index.")
    target_class_instance = pre_state.oig_index.class_instances_by_id.get(target_class_instance_id)
    if target_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve target class instance: "
            f"target_class_instance_id={target_class_instance_id}"
        )
    return target_class_instance.source_object_id


def _find_orm_model_by_id(root_model: ORMModel, object_id) -> ORMModel | None:
    stack: list[object] = [root_model]
    seen: set[int] = set()
    while stack:
        current = stack.pop()
        identity = id(current)
        if identity in seen:
            continue
        seen.add(identity)
        if isinstance(current, ORMModel):
            if current.id == object_id:
                return current
            stack.extend(current.__dict__.values())
            continue
        if isinstance(current, (list, tuple, set)):
            stack.extend(current)
            continue
        if isinstance(current, dict):
            stack.extend(current.values())
    return None


def _constructed_class_instance_ids_from_post_oig(
    *,
    pre_state: MetaGraphPreState,
    post_oig: ObjectInstanceGraph,
) -> tuple:
    before_ids = {instance.id for instance in pre_state.before_oig.class_instances}
    return tuple(instance.id for instance in post_oig.class_instances if instance.id not in before_ids)


def _json_payload_value(value: object) -> object:
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    if isinstance(value, tuple):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, list):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_payload_value(item) for key, item in value.items()}
    return value


def _bind_ontology__build_via_ontology_config(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("ontology_config_id", "key", "title", "description", "status"),
        function_name="build_via_ontology_config",
    )


async def _call_ontology__build_via_ontology_config(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> ORMModel:
    from aware_ontology.handlers.impl.ontology.ontology import build_via_ontology_config as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_ontology__build_via_ontology_config(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_ontology_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    ontology_config_id = bound_input.get("ontology_config_id")
    key = bound_input.get("key")
    title = bound_input.get("title")
    if title is None:
        title = None
    description = bound_input.get("description")
    if description is None:
        description = None
    status = bound_input.get("status")
    if status is None:
        status = "active"
    _aware_self_values = {
        "ontology_config_id": ontology_config_id,
        "key": key,
        "title": title,
        "description": description,
        "status": status,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("043af7f1-9107-5933-b6cb-fcc86f658424")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Ontology.build_via_ontology_config"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Ontology.build_via_ontology_config"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_ontology_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_ontology_config__build(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "name",
            "fqn_prefix",
            "object_config_graph_id",
            "object_config_graph_object_instance_graph_commit_id",
            "version_number",
            "title",
            "description",
            "schema_hash",
        ),
        function_name="build",
    )


async def _call_ontology_config__build(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_ontology.handlers.impl.ontology.ontology_config import build as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_ontology_config__build(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_ontology_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    name = bound_input.get("name")
    fqn_prefix = bound_input.get("fqn_prefix")
    object_config_graph_id = bound_input.get("object_config_graph_id")
    if object_config_graph_id is None:
        object_config_graph_id = None
    object_config_graph_object_instance_graph_commit_id = bound_input.get(
        "object_config_graph_object_instance_graph_commit_id"
    )
    if object_config_graph_object_instance_graph_commit_id is None:
        object_config_graph_object_instance_graph_commit_id = None
    version_number = bound_input.get("version_number")
    if version_number is None:
        version_number = 1
    title = bound_input.get("title")
    if title is None:
        title = None
    description = bound_input.get("description")
    if description is None:
        description = None
    schema_hash = bound_input.get("schema_hash")
    if schema_hash is None:
        schema_hash = None
    _aware_self_values = {
        "name": name,
        "fqn_prefix": fqn_prefix,
        "object_config_graph_id": object_config_graph_id,
        "object_config_graph_object_instance_graph_commit_id": object_config_graph_object_instance_graph_commit_id,
        "version_number": version_number,
        "title": title,
        "description": description,
        "schema_hash": schema_hash,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("bead5bba-40ce-5bef-8e0e-200caf0615b0")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: OntologyConfig.build"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: OntologyConfig.build"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_ontology_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_ontology_config__create_ontology(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("key", "title", "description", "status"),
        function_name="create_ontology",
    )


async def _call_ontology_config__create_ontology(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_ontology.handlers.impl.ontology.ontology_config import create_ontology as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: OntologyConfig.create_ontology"
        )
    result = await _impl(ontology_config=target, **call_kwargs)
    return result


def _bind_ontology_package__build(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "name",
            "fqn_prefix",
            "ontology_config_id",
            "ontology_config_object_instance_graph_commit_id",
            "source_code_package_id",
            "object_config_graph_package_id",
            "object_config_graph_package_object_instance_graph_commit_id",
            "object_config_graph_object_instance_graph_commit_id",
            "version_number",
            "title",
            "description",
            "manifest_relative_path",
            "package_root",
            "sources_root",
        ),
        function_name="build",
    )


async def _call_ontology_package__build(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_ontology.handlers.impl.ontology.ontology_package import build as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_ontology_package__build(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_ontology_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    name = bound_input.get("name")
    fqn_prefix = bound_input.get("fqn_prefix")
    ontology_config_id = bound_input.get("ontology_config_id")
    if ontology_config_id is None:
        ontology_config_id = None
    ontology_config_object_instance_graph_commit_id = bound_input.get("ontology_config_object_instance_graph_commit_id")
    if ontology_config_object_instance_graph_commit_id is None:
        ontology_config_object_instance_graph_commit_id = None
    source_code_package_id = bound_input.get("source_code_package_id")
    if source_code_package_id is None:
        source_code_package_id = None
    object_config_graph_package_id = bound_input.get("object_config_graph_package_id")
    if object_config_graph_package_id is None:
        object_config_graph_package_id = None
    object_config_graph_package_object_instance_graph_commit_id = bound_input.get(
        "object_config_graph_package_object_instance_graph_commit_id"
    )
    if object_config_graph_package_object_instance_graph_commit_id is None:
        object_config_graph_package_object_instance_graph_commit_id = None
    object_config_graph_object_instance_graph_commit_id = bound_input.get(
        "object_config_graph_object_instance_graph_commit_id"
    )
    if object_config_graph_object_instance_graph_commit_id is None:
        object_config_graph_object_instance_graph_commit_id = None
    version_number = bound_input.get("version_number")
    if version_number is None:
        version_number = 1
    title = bound_input.get("title")
    if title is None:
        title = None
    description = bound_input.get("description")
    if description is None:
        description = None
    manifest_relative_path = bound_input.get("manifest_relative_path")
    if manifest_relative_path is None:
        manifest_relative_path = None
    package_root = bound_input.get("package_root")
    if package_root is None:
        package_root = "."
    sources_root = bound_input.get("sources_root")
    if sources_root is None:
        sources_root = "modules"
    _aware_self_values = {
        "name": name,
        "fqn_prefix": fqn_prefix,
        "ontology_config_id": ontology_config_id,
        "ontology_config_object_instance_graph_commit_id": ontology_config_object_instance_graph_commit_id,
        "source_code_package_id": source_code_package_id,
        "object_config_graph_package_id": object_config_graph_package_id,
        "object_config_graph_package_object_instance_graph_commit_id": object_config_graph_package_object_instance_graph_commit_id,
        "object_config_graph_object_instance_graph_commit_id": object_config_graph_object_instance_graph_commit_id,
        "version_number": version_number,
        "title": title,
        "description": description,
        "manifest_relative_path": manifest_relative_path,
        "package_root": package_root,
        "sources_root": sources_root,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("d76251eb-85fe-56fb-8eea-154d30f22e5b")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: OntologyPackage.build"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: OntologyPackage.build"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_ontology_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_ontology_package__attach_runtime_code_package(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "code_package_id",
            "package_name",
            "language",
            "import_root",
            "manifest_relative_path",
            "package_root",
            "role",
            "object_instance_graph_commit_id",
            "include_paths",
            "exclude_paths",
        ),
        function_name="attach_runtime_code_package",
    )


async def _call_ontology_package__attach_runtime_code_package(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> object:
    from aware_ontology.handlers.impl.ontology.ontology_package import attach_runtime_code_package as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: OntologyPackage.attach_runtime_code_package"
        )
    result = await _impl(ontology_package=target, **call_kwargs)
    return result


def _bind_ontology_package__attach_dependency(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "target_ontology_package_id",
            "target_package_name",
            "target_ontology_package_object_instance_graph_commit_id",
            "target_version_number",
            "expected_hash_sha256",
            "description",
        ),
        function_name="attach_dependency",
    )


async def _call_ontology_package__attach_dependency(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> object:
    from aware_ontology.handlers.impl.ontology.ontology_package import attach_dependency as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: OntologyPackage.attach_dependency"
        )
    result = await _impl(ontology_package=target, **call_kwargs)
    return result


def _bind_ontology_package_dependency__build_via_ontology_package(
    *, positional: JsonArray, keyword: JsonObject
) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "ontology_package_id",
            "target_ontology_package_id",
            "target_package_name",
            "target_ontology_package_object_instance_graph_commit_id",
            "target_version_number",
            "expected_hash_sha256",
            "description",
        ),
        function_name="build_via_ontology_package",
    )


async def _call_ontology_package_dependency__build_via_ontology_package(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> ORMModel:
    from aware_ontology.handlers.impl.ontology.ontology_package_dependency import build_via_ontology_package as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_ontology_package_dependency__build_via_ontology_package(
    *, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject
):
    from importlib import import_module
    from aware_ontology_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    ontology_package_id = bound_input.get("ontology_package_id")
    target_ontology_package_id = bound_input.get("target_ontology_package_id")
    target_package_name = bound_input.get("target_package_name")
    target_ontology_package_object_instance_graph_commit_id = bound_input.get(
        "target_ontology_package_object_instance_graph_commit_id"
    )
    if target_ontology_package_object_instance_graph_commit_id is None:
        target_ontology_package_object_instance_graph_commit_id = None
    target_version_number = bound_input.get("target_version_number")
    if target_version_number is None:
        target_version_number = None
    expected_hash_sha256 = bound_input.get("expected_hash_sha256")
    if expected_hash_sha256 is None:
        expected_hash_sha256 = None
    description = bound_input.get("description")
    if description is None:
        description = None
    _aware_self_values = {
        "ontology_package_id": ontology_package_id,
        "target_ontology_package_id": target_ontology_package_id,
        "target_package_name": target_package_name,
        "target_ontology_package_object_instance_graph_commit_id": target_ontology_package_object_instance_graph_commit_id,
        "target_version_number": target_version_number,
        "expected_hash_sha256": expected_hash_sha256,
        "description": description,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("0b865742-53d4-5022-a869-f9d322547c21")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: OntologyPackageDependency.build_via_ontology_package"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: OntologyPackageDependency.build_via_ontology_package"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_ontology_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_ontology_package_runtime_code_package__build_via_ontology_package(
    *, positional: JsonArray, keyword: JsonObject
) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=(
            "ontology_package_id",
            "code_package_id",
            "package_name",
            "language",
            "import_root",
            "manifest_relative_path",
            "package_root",
            "role",
            "object_instance_graph_commit_id",
            "include_paths",
            "exclude_paths",
        ),
        function_name="build_via_ontology_package",
    )


async def _call_ontology_package_runtime_code_package__build_via_ontology_package(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> ORMModel:
    from aware_ontology.handlers.impl.ontology.ontology_package_runtime_code_package import (
        build_via_ontology_package as _impl,
    )

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_ontology_package_runtime_code_package__build_via_ontology_package(
    *, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject
):
    from importlib import import_module
    from aware_ontology_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    ontology_package_id = bound_input.get("ontology_package_id")
    code_package_id = bound_input.get("code_package_id")
    package_name = bound_input.get("package_name")
    language = bound_input.get("language")
    import_root = bound_input.get("import_root")
    manifest_relative_path = bound_input.get("manifest_relative_path")
    package_root = bound_input.get("package_root")
    if package_root is None:
        package_root = "."
    role = bound_input.get("role")
    if role is None:
        role = "runtime"
    object_instance_graph_commit_id = bound_input.get("object_instance_graph_commit_id")
    if object_instance_graph_commit_id is None:
        object_instance_graph_commit_id = None
    include_paths = bound_input.get("include_paths")
    if include_paths is None:
        include_paths = []
    exclude_paths = bound_input.get("exclude_paths")
    if exclude_paths is None:
        exclude_paths = []
    _aware_self_values = {
        "ontology_package_id": ontology_package_id,
        "code_package_id": code_package_id,
        "package_name": package_name,
        "language": language,
        "import_root": import_root,
        "manifest_relative_path": manifest_relative_path,
        "package_root": package_root,
        "role": role,
        "object_instance_graph_commit_id": object_instance_graph_commit_id,
        "include_paths": include_paths,
        "exclude_paths": exclude_paths,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("6f05623c-8965-5768-85ba-03a41d8b9803")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: OntologyPackageRuntimeCodePackage.build_via_ontology_package"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: OntologyPackageRuntimeCodePackage.build_via_ontology_package"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_ontology_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


async def ontology__build_via_ontology_config__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology__build_via_ontology_config(positional=positional, keyword=keyword)
    result = await _call_ontology__build_via_ontology_config(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Ontology")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def ontology__build_via_ontology_config__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_ontology__build_via_ontology_config(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_ontology__build_via_ontology_config(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Ontology",
        description="Meta constructor bootstrap for Ontology.",
    )


async def ontology_config__build__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_config__build(positional=positional, keyword=keyword)
    result = await _call_ontology_config__build(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="OntologyConfig")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def ontology_config__build__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_ontology_config__build(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_ontology_config__build(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="OntologyConfig",
        description="Meta constructor bootstrap for OntologyConfig.",
    )


async def ontology_config__create_ontology__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_config__create_ontology(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="OntologyConfig",
    )
    result = await _call_ontology_config__create_ontology(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def ontology_package__build__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_package__build(positional=positional, keyword=keyword)
    result = await _call_ontology_package__build(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="OntologyPackage")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def ontology_package__build__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_ontology_package__build(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_ontology_package__build(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="OntologyPackage",
        description="Meta constructor bootstrap for OntologyPackage.",
    )


async def ontology_package__attach_runtime_code_package__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_package__attach_runtime_code_package(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="OntologyPackage",
    )
    result = await _call_ontology_package__attach_runtime_code_package(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def ontology_package__attach_dependency__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_package__attach_dependency(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="OntologyPackage",
    )
    result = await _call_ontology_package__attach_dependency(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def ontology_package_dependency__build_via_ontology_package__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_package_dependency__build_via_ontology_package(positional=positional, keyword=keyword)
    result = await _call_ontology_package_dependency__build_via_ontology_package(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="OntologyPackageDependency")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def ontology_package_dependency__build_via_ontology_package__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_ontology_package_dependency__build_via_ontology_package(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_ontology_package_dependency__build_via_ontology_package(
        request=request, bound_input=bound_input
    )
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="OntologyPackageDependency",
        description="Meta constructor bootstrap for OntologyPackageDependency.",
    )


async def ontology_package_runtime_code_package__build_via_ontology_package__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_ontology_package_runtime_code_package__build_via_ontology_package(
        positional=positional, keyword=keyword
    )
    result = await _call_ontology_package_runtime_code_package__build_via_ontology_package(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="OntologyPackageRuntimeCodePackage")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def ontology_package_runtime_code_package__build_via_ontology_package__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_ontology_package_runtime_code_package__build_via_ontology_package(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_ontology_package_runtime_code_package__build_via_ontology_package(
        request=request, bound_input=bound_input
    )
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="OntologyPackageRuntimeCodePackage",
        description="Meta constructor bootstrap for OntologyPackageRuntimeCodePackage.",
    )


async def ontology__build_via_ontology_config__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology__build_via_ontology_config(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_ontology__build_via_ontology_config(bound_input=bound_input)


async def ontology_config__build__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_config__build(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_ontology_config__build(bound_input=bound_input)


async def ontology_config__create_ontology__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_config__create_ontology(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_ontology_config__create_ontology(bound_input=bound_input, target=target)


async def ontology_package__build__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_package__build(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_ontology_package__build(bound_input=bound_input)


async def ontology_package__attach_runtime_code_package__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_package__attach_runtime_code_package(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_ontology_package__attach_runtime_code_package(bound_input=bound_input, target=target)


async def ontology_package__attach_dependency__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_package__attach_dependency(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_ontology_package__attach_dependency(bound_input=bound_input, target=target)


async def ontology_package_dependency__build_via_ontology_package__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_package_dependency__build_via_ontology_package(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_ontology_package_dependency__build_via_ontology_package(bound_input=bound_input)


async def ontology_package_runtime_code_package__build_via_ontology_package__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_ontology_package_runtime_code_package__build_via_ontology_package(
        positional=positional, keyword=keyword
    )
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_ontology_package_runtime_code_package__build_via_ontology_package(bound_input=bound_input)


AWARE_META_GRAPH_HANDLERS: dict[MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedLanguageHandlerCallable] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.Ontology",
        function_name="build_via_ontology_config",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.Ontology",
        owner_class_name="Ontology",
    ): ontology__build_via_ontology_config__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyConfig",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyConfig",
        owner_class_name="OntologyConfig",
    ): ontology_config__build__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyConfig",
        function_name="create_ontology",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyConfig",
        owner_class_name="OntologyConfig",
    ): ontology_config__create_ontology__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__build__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="attach_runtime_code_package",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__attach_runtime_code_package__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="attach_dependency",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__attach_dependency__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageDependency",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageDependency",
        owner_class_name="OntologyPackageDependency",
    ): ontology_package_dependency__build_via_ontology_package__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        owner_class_name="OntologyPackageRuntimeCodePackage",
    ): ontology_package_runtime_code_package__build_via_ontology_package__handler,
}

AWARE_META_GRAPH_INVOCATION_HANDLERS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedInvocationHandlerCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.Ontology",
        function_name="build_via_ontology_config",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.Ontology",
        owner_class_name="Ontology",
    ): ontology__build_via_ontology_config__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyConfig",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyConfig",
        owner_class_name="OntologyConfig",
    ): ontology_config__build__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyConfig",
        function_name="create_ontology",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyConfig",
        owner_class_name="OntologyConfig",
    ): ontology_config__create_ontology__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__build__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="attach_runtime_code_package",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__attach_runtime_code_package__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="attach_dependency",
        is_constructor=False,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__attach_dependency__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageDependency",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageDependency",
        owner_class_name="OntologyPackageDependency",
    ): ontology_package_dependency__build_via_ontology_package__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        owner_class_name="OntologyPackageRuntimeCodePackage",
    ): ontology_package_runtime_code_package__build_via_ontology_package__invocation_handler,
}

AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphEmptyLaneBootstrapCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.Ontology",
        function_name="build_via_ontology_config",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.Ontology",
        owner_class_name="Ontology",
    ): ontology__build_via_ontology_config__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyConfig",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyConfig",
        owner_class_name="OntologyConfig",
    ): ontology_config__build__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackage",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackage",
        owner_class_name="OntologyPackage",
    ): ontology_package__build__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageDependency",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageDependency",
        owner_class_name="OntologyPackageDependency",
    ): ontology_package_dependency__build_via_ontology_package__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        function_name="build_via_ontology_package",
        is_constructor=True,
        owner_class_fqn="aware_ontology.ontology.OntologyPackageRuntimeCodePackage",
        owner_class_name="OntologyPackageRuntimeCodePackage",
    ): ontology_package_runtime_code_package__build_via_ontology_package__empty_lane_bootstrap,
}

__all__ = [
    "AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS",
    "AWARE_META_GRAPH_HANDLERS",
    "AWARE_META_GRAPH_INVOCATION_HANDLERS",
]
