from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_code.semantic_capability import SEMANTIC_ANALYSIS_CAPABILITY
from aware_skill.semantic_contract import (
    AWARE_SKILL_SEMANTIC_CONTRACT,
    SKILL_API_OWNER,
    SKILL_CAPABILITY_BUNDLES,
    SKILL_CAPABILITY_PARTICIPATION,
    SKILL_CAPABILITY_PROFILES,
    SKILL_CONFIG_OWNER,
    SKILL_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    SKILL_DIAGNOSTICS_CAPABILITY_PROFILES,
    SKILL_ENDPOINT_OWNER,
    SKILL_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION,
    SKILL_SEMANTIC_ANALYSIS_CAPABILITY_PROFILES,
    SKILL_SEMANTIC_SCOPE_KEYS,
    SKILL_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    SKILL_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
    SKILL_STEP_OWNER,
)


SKILL_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_SKILL_SEMANTIC_CONTRACT
)

SKILL_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in SKILL_CAPABILITY_METADATA if item.capability == "diagnostics"
)

SKILL_SEMANTIC_ANALYSIS_CAPABILITY_METADATA = tuple(
    item
    for item in SKILL_CAPABILITY_METADATA
    if item.capability == SEMANTIC_ANALYSIS_CAPABILITY
)

SKILL_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in SKILL_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)


__all__ = [
    "SKILL_API_OWNER",
    "SKILL_CAPABILITY_BUNDLES",
    "SKILL_CAPABILITY_METADATA",
    "SKILL_CAPABILITY_PARTICIPATION",
    "SKILL_CAPABILITY_PROFILES",
    "SKILL_CONFIG_OWNER",
    "SKILL_DIAGNOSTICS_CAPABILITY_METADATA",
    "SKILL_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "SKILL_DIAGNOSTICS_CAPABILITY_PROFILES",
    "SKILL_ENDPOINT_OWNER",
    "SKILL_SEMANTIC_ANALYSIS_CAPABILITY_METADATA",
    "SKILL_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION",
    "SKILL_SEMANTIC_ANALYSIS_CAPABILITY_PROFILES",
    "SKILL_SEMANTIC_SCOPE_KEYS",
    "SKILL_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "SKILL_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
    "SKILL_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "SKILL_STEP_OWNER",
]
