from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_interface.semantic_contract import (
    AWARE_INTERFACE_SEMANTIC_CONTRACT,
    INTERFACE_API_OWNER,
    INTERFACE_CAPABILITY_BUNDLES,
    INTERFACE_CAPABILITY_PARTICIPATION,
    INTERFACE_CAPABILITY_PROFILES,
    INTERFACE_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    INTERFACE_DIAGNOSTICS_CAPABILITY_PROFILES,
    INTERFACE_ENDPOINT_OWNER,
    INTERFACE_LAYOUT_OWNER,
    INTERFACE_MOUNT_OWNER,
    INTERFACE_NARRATIVE_OWNER,
    INTERFACE_PACKAGE_CAPABILITY_PARTICIPATION,
    INTERFACE_PACKAGE_CAPABILITY_PROFILES,
    INTERFACE_PANE_COMPOSITION_OWNER,
    INTERFACE_PANE_OWNER,
    INTERFACE_ROOT_OWNER,
    INTERFACE_SECTION_OWNER,
    INTERFACE_SEMANTIC_SCOPE_KEYS,
    INTERFACE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    INTERFACE_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
    INTERFACE_VIEW_OWNER,
    INTERFACE_WINDOW_OWNER,
    PANE_DIAGNOSTICS_CAPABILITY_PROFILES,
    PANE_PACKAGE_CAPABILITY_PARTICIPATION,
    PANE_PACKAGE_CAPABILITY_PROFILES,
    PANE_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
)

INTERFACE_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_INTERFACE_SEMANTIC_CONTRACT
)

INTERFACE_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in INTERFACE_CAPABILITY_METADATA if item.capability == "diagnostics"
)

INTERFACE_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in INTERFACE_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)

__all__ = [
    "INTERFACE_API_OWNER",
    "INTERFACE_CAPABILITY_BUNDLES",
    "INTERFACE_CAPABILITY_METADATA",
    "INTERFACE_CAPABILITY_PARTICIPATION",
    "INTERFACE_CAPABILITY_PROFILES",
    "INTERFACE_DIAGNOSTICS_CAPABILITY_METADATA",
    "INTERFACE_DIAGNOSTICS_CAPABILITY_PROFILES",
    "INTERFACE_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "INTERFACE_ENDPOINT_OWNER",
    "INTERFACE_LAYOUT_OWNER",
    "INTERFACE_MOUNT_OWNER",
    "INTERFACE_NARRATIVE_OWNER",
    "INTERFACE_PACKAGE_CAPABILITY_PARTICIPATION",
    "INTERFACE_PACKAGE_CAPABILITY_PROFILES",
    "INTERFACE_PANE_COMPOSITION_OWNER",
    "INTERFACE_PANE_OWNER",
    "INTERFACE_ROOT_OWNER",
    "INTERFACE_SECTION_OWNER",
    "INTERFACE_SEMANTIC_SCOPE_KEYS",
    "INTERFACE_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "INTERFACE_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "INTERFACE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
    "INTERFACE_VIEW_OWNER",
    "INTERFACE_WINDOW_OWNER",
    "PANE_DIAGNOSTICS_CAPABILITY_PROFILES",
    "PANE_PACKAGE_CAPABILITY_PARTICIPATION",
    "PANE_PACKAGE_CAPABILITY_PROFILES",
    "PANE_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
]
