from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_api_runtime.semantic_contract import (
    AWARE_API_SEMANTIC_CONTRACT,
    API_API_OWNER,
    API_CAPABILITY_OWNER,
    API_CAPABILITY_PARTICIPATION,
    API_CAPABILITY_BUNDLES,
    API_CAPABILITY_PROFILES,
    API_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    API_DIAGNOSTICS_CAPABILITY_PROFILES,
    API_GRAPH_OWNER,
    API_PROJECTION_OWNER,
    API_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION,
    API_SEMANTIC_ANALYSIS_CAPABILITY_PROFILES,
    API_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    API_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
)
from aware_code.semantic_capability import SEMANTIC_ANALYSIS_CAPABILITY

API_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_API_SEMANTIC_CONTRACT
)

API_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in API_CAPABILITY_METADATA if item.capability == "diagnostics"
)

API_SEMANTIC_ANALYSIS_CAPABILITY_METADATA = tuple(
    item
    for item in API_CAPABILITY_METADATA
    if item.capability == SEMANTIC_ANALYSIS_CAPABILITY
)

API_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in API_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)

__all__ = [
    "API_API_OWNER",
    "API_CAPABILITY_METADATA",
    "API_CAPABILITY_PARTICIPATION",
    "API_CAPABILITY_BUNDLES",
    "API_CAPABILITY_PROFILES",
    "API_CAPABILITY_OWNER",
    "API_DIAGNOSTICS_CAPABILITY_METADATA",
    "API_DIAGNOSTICS_CAPABILITY_PROFILES",
    "API_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "API_GRAPH_OWNER",
    "API_PROJECTION_OWNER",
    "API_SEMANTIC_ANALYSIS_CAPABILITY_METADATA",
    "API_SEMANTIC_ANALYSIS_CAPABILITY_PROFILES",
    "API_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION",
    "API_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "API_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "API_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
]
