from __future__ import annotations

from pathlib import Path


TESTS_ROOT = Path(__file__).resolve().parent
RUNTIME_PYTHON_ROOT = TESTS_ROOT.parent
IDENTITY_ONTOLOGY_ROOT = RUNTIME_PYTHON_ROOT.parents[1]
IDENTITY_MODULE_ROOT = IDENTITY_ONTOLOGY_ROOT.parent
AWARE_NETWORK_WORKSPACE_ROOT = IDENTITY_MODULE_ROOT.parents[1]
REPO_ROOT = AWARE_NETWORK_WORKSPACE_ROOT.parent.parent

IDENTITY_STRUCTURE_ROOT = IDENTITY_ONTOLOGY_ROOT / "structure"
IDENTITY_AWARE_ROOT = IDENTITY_STRUCTURE_ROOT / "aware"
IDENTITY_AWARE_TOML = IDENTITY_STRUCTURE_ROOT / "aware.toml"
IDENTITY_RUNTIME_MANIFEST = (
    IDENTITY_STRUCTURE_ROOT / ".aware/ontology/runtime/ontology.runtime.manifest.json"
)
IDENTITY_RUNTIME_SOURCE_ROOT = RUNTIME_PYTHON_ROOT / "aware_identity"
IDENTITY_SQL_ROOT = IDENTITY_STRUCTURE_ROOT / "sql"
IDENTITY_ORM_RUNTIME_ROOT = IDENTITY_STRUCTURE_ROOT / "python" / "orm_runtime"
