# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from typing import (
    TYPE_CHECKING,
    cast,
)

# Runtime
from aware_meta.runtime.generated_handlers import (
    constructor,
    instance,
)

if TYPE_CHECKING:
    from aware_meta_ontology.function.function_call import FunctionCall
    from aware_orm.models.orm_model import ORMModel
    from aware_orm.session.session import Session
    from aware_meta.runtime.generated_handlers import HandlerContext


async def skill_config__build__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config import build as _impl

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(name=name, description=description)
    return result, result


async def skill_config__add_api__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config import add_api as _impl
    from uuid import UUID

    _raw_api_id: object | None = None
    if "api_id" in kwargs:
        _raw_api_id = kwargs["api_id"]
    elif len(args) > 0:
        _raw_api_id = args[0]
    api_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(skill_config=orm_model, api_id=api_id, description=description)
    return result


async def skill_config__add_step__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config import add_step as _impl
    from uuid import UUID

    _raw_position: object | None = None
    if "position" in kwargs:
        _raw_position = kwargs["position"]
    elif len(args) > 0:
        _raw_position = args[0]
    position: int = TypeAdapter(int).validate_python(_raw_position)
    _raw_skill_config_api_endpoint_id: object | None = None
    if "skill_config_api_endpoint_id" in kwargs:
        _raw_skill_config_api_endpoint_id = kwargs["skill_config_api_endpoint_id"]
    elif len(args) > 1:
        _raw_skill_config_api_endpoint_id = args[1]
    skill_config_api_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_api_endpoint_id)
    _raw_instruction: object | None = None
    if "instruction" in kwargs:
        _raw_instruction = kwargs["instruction"]
    elif len(args) > 2:
        _raw_instruction = args[2]
    instruction: str = TypeAdapter(str).validate_python(_raw_instruction)
    result = await _impl(
        skill_config=orm_model,
        position=position,
        skill_config_api_endpoint_id=skill_config_api_endpoint_id,
        instruction=instruction,
    )
    return result


async def skill_config__add_experience__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config import add_experience as _impl
    from uuid import UUID

    _raw_projection_experience_id: object | None = None
    if "projection_experience_id" in kwargs:
        _raw_projection_experience_id = kwargs["projection_experience_id"]
    elif len(args) > 0:
        _raw_projection_experience_id = args[0]
    projection_experience_id: UUID = TypeAdapter(UUID).validate_python(_raw_projection_experience_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config=orm_model, projection_experience_id=projection_experience_id, description=description
    )
    return result


async def skill_config__create_run__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config import create_run as _impl
    from aware_skill_ontology.skill.skill_run_enums import SkillRunStatus
    from datetime import datetime

    _raw_run_key: object | None = None
    if "run_key" in kwargs:
        _raw_run_key = kwargs["run_key"]
    elif len(args) > 0:
        _raw_run_key = args[0]
    run_key: str = TypeAdapter(str).validate_python(_raw_run_key)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 1:
        _raw_status = args[1]
    if _raw_status is None:
        _raw_status = SkillRunStatus.queued
    status: SkillRunStatus = TypeAdapter(SkillRunStatus).validate_python(_raw_status)
    _raw_started_at_utc: object | None = None
    if "started_at_utc" in kwargs:
        _raw_started_at_utc = kwargs["started_at_utc"]
    elif len(args) > 2:
        _raw_started_at_utc = args[2]
    if _raw_started_at_utc is None:
        _raw_started_at_utc = None
    started_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_started_at_utc)
    )
    _raw_finished_at_utc: object | None = None
    if "finished_at_utc" in kwargs:
        _raw_finished_at_utc = kwargs["finished_at_utc"]
    elif len(args) > 3:
        _raw_finished_at_utc = args[3]
    if _raw_finished_at_utc is None:
        _raw_finished_at_utc = None
    finished_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_finished_at_utc)
    )
    _raw_error: object | None = None
    if "error" in kwargs:
        _raw_error = kwargs["error"]
    elif len(args) > 4:
        _raw_error = args[4]
    if _raw_error is None:
        _raw_error = None
    error: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_error))
    result = await _impl(
        skill_config=orm_model,
        run_key=run_key,
        status=status,
        started_at_utc=started_at_utc,
        finished_at_utc=finished_at_utc,
        error=error,
    )
    return result


async def skill_config_api__add_api_endpoint__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_api import add_api_endpoint as _impl
    from uuid import UUID

    _raw_api_endpoint_id: object | None = None
    if "api_endpoint_id" in kwargs:
        _raw_api_endpoint_id = kwargs["api_endpoint_id"]
    elif len(args) > 0:
        _raw_api_endpoint_id = args[0]
    api_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_endpoint_id)
    _raw_capability_name: object | None = None
    if "capability_name" in kwargs:
        _raw_capability_name = kwargs["capability_name"]
    elif len(args) > 1:
        _raw_capability_name = args[1]
    capability_name: str = TypeAdapter(str).validate_python(_raw_capability_name)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 2:
        _raw_name = args[2]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 3:
        _raw_description = args[3]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_api=orm_model,
        api_endpoint_id=api_endpoint_id,
        capability_name=capability_name,
        name=name,
        description=description,
    )
    return result


async def skill_config_api__build_via_skill_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_api import build_via_skill_config as _impl
    from uuid import UUID

    _raw_skill_config_id: object | None = None
    if "skill_config_id" in kwargs:
        _raw_skill_config_id = kwargs["skill_config_id"]
    elif len(args) > 0:
        _raw_skill_config_id = args[0]
    skill_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_id)
    _raw_api_id: object | None = None
    if "api_id" in kwargs:
        _raw_api_id = kwargs["api_id"]
    elif len(args) > 1:
        _raw_api_id = args[1]
    api_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(skill_config_id=skill_config_id, api_id=api_id, description=description)
    return result, result


async def skill_config_api_endpoint__build_via_skill_config_api__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_api_endpoint import build_via_skill_config_api as _impl
    from uuid import UUID

    _raw_skill_config_api_id: object | None = None
    if "skill_config_api_id" in kwargs:
        _raw_skill_config_api_id = kwargs["skill_config_api_id"]
    elif len(args) > 0:
        _raw_skill_config_api_id = args[0]
    skill_config_api_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_api_id)
    _raw_api_endpoint_id: object | None = None
    if "api_endpoint_id" in kwargs:
        _raw_api_endpoint_id = kwargs["api_endpoint_id"]
    elif len(args) > 1:
        _raw_api_endpoint_id = args[1]
    api_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_endpoint_id)
    _raw_capability_name: object | None = None
    if "capability_name" in kwargs:
        _raw_capability_name = kwargs["capability_name"]
    elif len(args) > 2:
        _raw_capability_name = args[2]
    capability_name: str = TypeAdapter(str).validate_python(_raw_capability_name)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 3:
        _raw_name = args[3]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 4:
        _raw_description = args[4]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_api_id=skill_config_api_id,
        api_endpoint_id=api_endpoint_id,
        capability_name=capability_name,
        name=name,
        description=description,
    )
    return result, result


async def skill_config_experience__add_target__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_experience import add_target as _impl
    from uuid import UUID

    _raw_projection_experience_graph_identity_id: object | None = None
    if "projection_experience_graph_identity_id" in kwargs:
        _raw_projection_experience_graph_identity_id = kwargs["projection_experience_graph_identity_id"]
    elif len(args) > 0:
        _raw_projection_experience_graph_identity_id = args[0]
    projection_experience_graph_identity_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_projection_experience_graph_identity_id
    )
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 1:
        _raw_name = args[1]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_experience=orm_model,
        projection_experience_graph_identity_id=projection_experience_graph_identity_id,
        name=name,
        description=description,
    )
    return result


async def skill_config_experience__build_via_skill_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_experience import build_via_skill_config as _impl
    from uuid import UUID

    _raw_skill_config_id: object | None = None
    if "skill_config_id" in kwargs:
        _raw_skill_config_id = kwargs["skill_config_id"]
    elif len(args) > 0:
        _raw_skill_config_id = args[0]
    skill_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_id)
    _raw_projection_experience_id: object | None = None
    if "projection_experience_id" in kwargs:
        _raw_projection_experience_id = kwargs["projection_experience_id"]
    elif len(args) > 1:
        _raw_projection_experience_id = args[1]
    projection_experience_id: UUID = TypeAdapter(UUID).validate_python(_raw_projection_experience_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_id=skill_config_id, projection_experience_id=projection_experience_id, description=description
    )
    return result, result


async def skill_config_step__add_target__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_step import add_target as _impl
    from uuid import UUID

    _raw_skill_config_target_id: object | None = None
    if "skill_config_target_id" in kwargs:
        _raw_skill_config_target_id = kwargs["skill_config_target_id"]
    elif len(args) > 0:
        _raw_skill_config_target_id = args[0]
    skill_config_target_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_target_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_step=orm_model, skill_config_target_id=skill_config_target_id, description=description
    )
    return result


async def skill_config_step__build_via_skill_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_step import build_via_skill_config as _impl
    from uuid import UUID

    _raw_skill_config_id: object | None = None
    if "skill_config_id" in kwargs:
        _raw_skill_config_id = kwargs["skill_config_id"]
    elif len(args) > 0:
        _raw_skill_config_id = args[0]
    skill_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_id)
    _raw_position: object | None = None
    if "position" in kwargs:
        _raw_position = kwargs["position"]
    elif len(args) > 1:
        _raw_position = args[1]
    position: int = TypeAdapter(int).validate_python(_raw_position)
    _raw_skill_config_api_endpoint_id: object | None = None
    if "skill_config_api_endpoint_id" in kwargs:
        _raw_skill_config_api_endpoint_id = kwargs["skill_config_api_endpoint_id"]
    elif len(args) > 2:
        _raw_skill_config_api_endpoint_id = args[2]
    skill_config_api_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_api_endpoint_id)
    _raw_instruction: object | None = None
    if "instruction" in kwargs:
        _raw_instruction = kwargs["instruction"]
    elif len(args) > 3:
        _raw_instruction = args[3]
    instruction: str = TypeAdapter(str).validate_python(_raw_instruction)
    result = await _impl(
        skill_config_id=skill_config_id,
        position=position,
        skill_config_api_endpoint_id=skill_config_api_endpoint_id,
        instruction=instruction,
    )
    return result, result


async def skill_config_step_target__build_via_skill_config_step__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_step_target import build_via_skill_config_step as _impl
    from uuid import UUID

    _raw_skill_config_step_id: object | None = None
    if "skill_config_step_id" in kwargs:
        _raw_skill_config_step_id = kwargs["skill_config_step_id"]
    elif len(args) > 0:
        _raw_skill_config_step_id = args[0]
    skill_config_step_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_step_id)
    _raw_skill_config_target_id: object | None = None
    if "skill_config_target_id" in kwargs:
        _raw_skill_config_target_id = kwargs["skill_config_target_id"]
    elif len(args) > 1:
        _raw_skill_config_target_id = args[1]
    skill_config_target_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_target_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_step_id=skill_config_step_id,
        skill_config_target_id=skill_config_target_id,
        description=description,
    )
    return result, result


async def skill_config_target__build_via_skill_config_experience__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_config_target import build_via_skill_config_experience as _impl
    from uuid import UUID

    _raw_skill_config_experience_id: object | None = None
    if "skill_config_experience_id" in kwargs:
        _raw_skill_config_experience_id = kwargs["skill_config_experience_id"]
    elif len(args) > 0:
        _raw_skill_config_experience_id = args[0]
    skill_config_experience_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_experience_id)
    _raw_projection_experience_graph_identity_id: object | None = None
    if "projection_experience_graph_identity_id" in kwargs:
        _raw_projection_experience_graph_identity_id = kwargs["projection_experience_graph_identity_id"]
    elif len(args) > 1:
        _raw_projection_experience_graph_identity_id = args[1]
    projection_experience_graph_identity_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_projection_experience_graph_identity_id
    )
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 2:
        _raw_name = args[2]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 3:
        _raw_description = args[3]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        skill_config_experience_id=skill_config_experience_id,
        projection_experience_graph_identity_id=projection_experience_graph_identity_id,
        name=name,
        description=description,
    )
    return result, result


async def skill_package__build__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_package import build as _impl
    from uuid import UUID

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_skill_config_id: object | None = None
    if "skill_config_id" in kwargs:
        _raw_skill_config_id = kwargs["skill_config_id"]
    elif len(args) > 1:
        _raw_skill_config_id = args[1]
    skill_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_id)
    _raw_skill_config_object_instance_graph_commit_id: object | None = None
    if "skill_config_object_instance_graph_commit_id" in kwargs:
        _raw_skill_config_object_instance_graph_commit_id = kwargs["skill_config_object_instance_graph_commit_id"]
    elif len(args) > 2:
        _raw_skill_config_object_instance_graph_commit_id = args[2]
    if _raw_skill_config_object_instance_graph_commit_id is None:
        _raw_skill_config_object_instance_graph_commit_id = None
    skill_config_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_skill_config_object_instance_graph_commit_id)
    )
    _raw_source_code_package_id: object | None = None
    if "source_code_package_id" in kwargs:
        _raw_source_code_package_id = kwargs["source_code_package_id"]
    elif len(args) > 3:
        _raw_source_code_package_id = args[3]
    if _raw_source_code_package_id is None:
        _raw_source_code_package_id = None
    source_code_package_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_source_code_package_id)
    )
    result = await _impl(
        name=name,
        skill_config_id=skill_config_id,
        skill_config_object_instance_graph_commit_id=skill_config_object_instance_graph_commit_id,
        source_code_package_id=source_code_package_id,
    )
    return result, result


async def skill_package__attach_api_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_package import attach_api_package as _impl
    from uuid import UUID

    _raw_api_package_id: object | None = None
    if "api_package_id" in kwargs:
        _raw_api_package_id = kwargs["api_package_id"]
    elif len(args) > 0:
        _raw_api_package_id = args[0]
    api_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_package_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(skill_package=orm_model, api_package_id=api_package_id, description=description)
    return result


async def skill_package_api_package__build_via_skill_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_package_api_package import build_via_skill_package as _impl
    from uuid import UUID

    _raw_skill_package_id: object | None = None
    if "skill_package_id" in kwargs:
        _raw_skill_package_id = kwargs["skill_package_id"]
    elif len(args) > 0:
        _raw_skill_package_id = args[0]
    skill_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_package_id)
    _raw_api_package_id: object | None = None
    if "api_package_id" in kwargs:
        _raw_api_package_id = kwargs["api_package_id"]
    elif len(args) > 1:
        _raw_api_package_id = args[1]
    api_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_package_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(skill_package_id=skill_package_id, api_package_id=api_package_id, description=description)
    return result, result


async def skill_run__create_step__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_run import create_step as _impl
    from aware_skill_ontology.skill.skill_run_enums import SkillRunStatus
    from datetime import datetime
    from uuid import UUID

    _raw_skill_config_step_id: object | None = None
    if "skill_config_step_id" in kwargs:
        _raw_skill_config_step_id = kwargs["skill_config_step_id"]
    elif len(args) > 0:
        _raw_skill_config_step_id = args[0]
    skill_config_step_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_step_id)
    _raw_api_call_id: object | None = None
    if "api_call_id" in kwargs:
        _raw_api_call_id = kwargs["api_call_id"]
    elif len(args) > 1:
        _raw_api_call_id = args[1]
    if _raw_api_call_id is None:
        _raw_api_call_id = None
    api_call_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_api_call_id))
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 2:
        _raw_status = args[2]
    if _raw_status is None:
        _raw_status = SkillRunStatus.queued
    status: SkillRunStatus = TypeAdapter(SkillRunStatus).validate_python(_raw_status)
    _raw_started_at_utc: object | None = None
    if "started_at_utc" in kwargs:
        _raw_started_at_utc = kwargs["started_at_utc"]
    elif len(args) > 3:
        _raw_started_at_utc = args[3]
    if _raw_started_at_utc is None:
        _raw_started_at_utc = None
    started_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_started_at_utc)
    )
    _raw_finished_at_utc: object | None = None
    if "finished_at_utc" in kwargs:
        _raw_finished_at_utc = kwargs["finished_at_utc"]
    elif len(args) > 4:
        _raw_finished_at_utc = args[4]
    if _raw_finished_at_utc is None:
        _raw_finished_at_utc = None
    finished_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_finished_at_utc)
    )
    _raw_error: object | None = None
    if "error" in kwargs:
        _raw_error = kwargs["error"]
    elif len(args) > 5:
        _raw_error = args[5]
    if _raw_error is None:
        _raw_error = None
    error: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_error))
    result = await _impl(
        skill_run=orm_model,
        skill_config_step_id=skill_config_step_id,
        api_call_id=api_call_id,
        status=status,
        started_at_utc=started_at_utc,
        finished_at_utc=finished_at_utc,
        error=error,
    )
    return result


async def skill_run__build_via_skill_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_run import build_via_skill_config as _impl
    from aware_skill_ontology.skill.skill_run_enums import SkillRunStatus
    from datetime import datetime
    from uuid import UUID

    _raw_skill_config_id: object | None = None
    if "skill_config_id" in kwargs:
        _raw_skill_config_id = kwargs["skill_config_id"]
    elif len(args) > 0:
        _raw_skill_config_id = args[0]
    skill_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_id)
    _raw_run_key: object | None = None
    if "run_key" in kwargs:
        _raw_run_key = kwargs["run_key"]
    elif len(args) > 1:
        _raw_run_key = args[1]
    run_key: str = TypeAdapter(str).validate_python(_raw_run_key)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 2:
        _raw_status = args[2]
    if _raw_status is None:
        _raw_status = SkillRunStatus.queued
    status: SkillRunStatus = TypeAdapter(SkillRunStatus).validate_python(_raw_status)
    _raw_started_at_utc: object | None = None
    if "started_at_utc" in kwargs:
        _raw_started_at_utc = kwargs["started_at_utc"]
    elif len(args) > 3:
        _raw_started_at_utc = args[3]
    if _raw_started_at_utc is None:
        _raw_started_at_utc = None
    started_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_started_at_utc)
    )
    _raw_finished_at_utc: object | None = None
    if "finished_at_utc" in kwargs:
        _raw_finished_at_utc = kwargs["finished_at_utc"]
    elif len(args) > 4:
        _raw_finished_at_utc = args[4]
    if _raw_finished_at_utc is None:
        _raw_finished_at_utc = None
    finished_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_finished_at_utc)
    )
    _raw_error: object | None = None
    if "error" in kwargs:
        _raw_error = kwargs["error"]
    elif len(args) > 5:
        _raw_error = args[5]
    if _raw_error is None:
        _raw_error = None
    error: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_error))
    result = await _impl(
        skill_config_id=skill_config_id,
        run_key=run_key,
        status=status,
        started_at_utc=started_at_utc,
        finished_at_utc=finished_at_utc,
        error=error,
    )
    return result, result


async def skill_run_step__build_via_skill_run__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_skill.handlers.impl.skill.skill_run_step import build_via_skill_run as _impl
    from aware_skill_ontology.skill.skill_run_enums import SkillRunStatus
    from datetime import datetime
    from uuid import UUID

    _raw_skill_run_id: object | None = None
    if "skill_run_id" in kwargs:
        _raw_skill_run_id = kwargs["skill_run_id"]
    elif len(args) > 0:
        _raw_skill_run_id = args[0]
    skill_run_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_run_id)
    _raw_skill_config_step_id: object | None = None
    if "skill_config_step_id" in kwargs:
        _raw_skill_config_step_id = kwargs["skill_config_step_id"]
    elif len(args) > 1:
        _raw_skill_config_step_id = args[1]
    skill_config_step_id: UUID = TypeAdapter(UUID).validate_python(_raw_skill_config_step_id)
    _raw_api_call_id: object | None = None
    if "api_call_id" in kwargs:
        _raw_api_call_id = kwargs["api_call_id"]
    elif len(args) > 2:
        _raw_api_call_id = args[2]
    if _raw_api_call_id is None:
        _raw_api_call_id = None
    api_call_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_api_call_id))
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 3:
        _raw_status = args[3]
    if _raw_status is None:
        _raw_status = SkillRunStatus.queued
    status: SkillRunStatus = TypeAdapter(SkillRunStatus).validate_python(_raw_status)
    _raw_started_at_utc: object | None = None
    if "started_at_utc" in kwargs:
        _raw_started_at_utc = kwargs["started_at_utc"]
    elif len(args) > 4:
        _raw_started_at_utc = args[4]
    if _raw_started_at_utc is None:
        _raw_started_at_utc = None
    started_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_started_at_utc)
    )
    _raw_finished_at_utc: object | None = None
    if "finished_at_utc" in kwargs:
        _raw_finished_at_utc = kwargs["finished_at_utc"]
    elif len(args) > 5:
        _raw_finished_at_utc = args[5]
    if _raw_finished_at_utc is None:
        _raw_finished_at_utc = None
    finished_at_utc: datetime | None = cast(
        datetime | None, TypeAdapter(datetime | None).validate_python(_raw_finished_at_utc)
    )
    _raw_error: object | None = None
    if "error" in kwargs:
        _raw_error = kwargs["error"]
    elif len(args) > 6:
        _raw_error = args[6]
    if _raw_error is None:
        _raw_error = None
    error: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_error))
    result = await _impl(
        skill_run_id=skill_run_id,
        skill_config_step_id=skill_config_step_id,
        api_call_id=api_call_id,
        status=status,
        started_at_utc=started_at_utc,
        finished_at_utc=finished_at_utc,
        error=error,
    )
    return result, result


AWARE_HANDLERS = [
    constructor("aware_skill_ontology.skill.skill_config.SkillConfig", "build", skill_config__build__handler),
    instance("aware_skill_ontology.skill.skill_config.SkillConfig", "add_api", skill_config__add_api__handler),
    instance("aware_skill_ontology.skill.skill_config.SkillConfig", "add_step", skill_config__add_step__handler),
    instance(
        "aware_skill_ontology.skill.skill_config.SkillConfig", "add_experience", skill_config__add_experience__handler
    ),
    instance("aware_skill_ontology.skill.skill_config.SkillConfig", "create_run", skill_config__create_run__handler),
    instance(
        "aware_skill_ontology.skill.skill_config_api.SkillConfigApi",
        "add_api_endpoint",
        skill_config_api__add_api_endpoint__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_api.SkillConfigApi",
        "build_via_skill_config",
        skill_config_api__build_via_skill_config__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_api_endpoint.SkillConfigApiEndpoint",
        "build_via_skill_config_api",
        skill_config_api_endpoint__build_via_skill_config_api__handler,
    ),
    instance(
        "aware_skill_ontology.skill.skill_config_experience.SkillConfigExperience",
        "add_target",
        skill_config_experience__add_target__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_experience.SkillConfigExperience",
        "build_via_skill_config",
        skill_config_experience__build_via_skill_config__handler,
    ),
    instance(
        "aware_skill_ontology.skill.skill_config_step.SkillConfigStep",
        "add_target",
        skill_config_step__add_target__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_step.SkillConfigStep",
        "build_via_skill_config",
        skill_config_step__build_via_skill_config__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_step_target.SkillConfigStepTarget",
        "build_via_skill_config_step",
        skill_config_step_target__build_via_skill_config_step__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_config_target.SkillConfigTarget",
        "build_via_skill_config_experience",
        skill_config_target__build_via_skill_config_experience__handler,
    ),
    constructor("aware_skill_ontology.skill.skill_package.SkillPackage", "build", skill_package__build__handler),
    instance(
        "aware_skill_ontology.skill.skill_package.SkillPackage",
        "attach_api_package",
        skill_package__attach_api_package__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_package_api_package.SkillPackageApiPackage",
        "build_via_skill_package",
        skill_package_api_package__build_via_skill_package__handler,
    ),
    instance("aware_skill_ontology.skill.skill_run.SkillRun", "create_step", skill_run__create_step__handler),
    constructor(
        "aware_skill_ontology.skill.skill_run.SkillRun",
        "build_via_skill_config",
        skill_run__build_via_skill_config__handler,
    ),
    constructor(
        "aware_skill_ontology.skill.skill_run_step.SkillRunStep",
        "build_via_skill_run",
        skill_run_step__build_via_skill_run__handler,
    ),
]

__all__ = ["AWARE_HANDLERS"]
