name: aware_storage_sdk
description: Storage SDK facade over generated Storage Service API.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  aware_api:
    path: ../../../../../api/libs/api/dart
  aware_storage_service_api:
    path: ../../../../apis/storage/dart/aware_storage_service_api
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.26.3
