"""Interface-owned manifest spec facade."""

from aware_interface.manifest.app_spec import (
    AwareAppScreenSourceSpec,
    AwareAppSourceSpec,
    AwareAppTomlBuildSpec,
    AwareAppTomlControlSpec,
    AwareAppTomlDependencySpec,
    AwareAppTomlDartSpec,
    AwareAppTomlFactorySpec,
    AwareAppTomlInterfaceSpec,
    AwareAppTomlLaunchSpec,
    AwareAppTomlPackageSpec,
    AwareAppTomlPlatformSpec,
    AwareAppTomlSpec,
)
from aware_interface.manifest.interface_spec import (
    AwareInterfaceCompilationMode,
    AwareInterfaceDependencyKind,
    AwareInterfaceTomlBuildSpec,
    AwareInterfaceTomlDartSpec,
    AwareInterfaceTomlDependencySpec,
    AwareInterfaceTomlPackageSpec,
    AwareInterfaceTomlSpec,
)
from aware_interface.manifest.pane_spec import (
    AwarePaneDependencyKind,
    AwarePaneTomlBuildSpec,
    AwarePaneTomlDependencySpec,
    AwarePaneTomlDartFlutterSpec,
    AwarePaneTomlDartSpec,
    AwarePaneTomlPackageSpec,
    AwarePaneTomlPythonSpec,
    AwarePaneTomlPythonTextualSpec,
    AwarePaneTomlSpec,
)
from aware_interface.manifest.render_component_spec import (
    AwareRenderComponentTomlBuildSpec,
    AwareRenderComponentTomlDartFlutterSpec,
    AwareRenderComponentTomlDartSpec,
    AwareRenderComponentTomlPackageSpec,
    AwareRenderComponentTomlPythonSpec,
    AwareRenderComponentTomlPythonTextualSpec,
    AwareRenderComponentTomlSpec,
)

__all__ = [
    "AwareAppScreenSourceSpec",
    "AwareAppSourceSpec",
    "AwareAppTomlBuildSpec",
    "AwareAppTomlControlSpec",
    "AwareAppTomlDependencySpec",
    "AwareAppTomlDartSpec",
    "AwareAppTomlFactorySpec",
    "AwareAppTomlInterfaceSpec",
    "AwareAppTomlLaunchSpec",
    "AwareAppTomlPackageSpec",
    "AwareAppTomlPlatformSpec",
    "AwareAppTomlSpec",
    "AwareInterfaceCompilationMode",
    "AwareInterfaceDependencyKind",
    "AwareInterfaceTomlBuildSpec",
    "AwareInterfaceTomlDartSpec",
    "AwareInterfaceTomlDependencySpec",
    "AwareInterfaceTomlPackageSpec",
    "AwareInterfaceTomlSpec",
    "AwarePaneTomlBuildSpec",
    "AwarePaneDependencyKind",
    "AwarePaneTomlDependencySpec",
    "AwarePaneTomlDartFlutterSpec",
    "AwarePaneTomlDartSpec",
    "AwarePaneTomlPackageSpec",
    "AwarePaneTomlPythonSpec",
    "AwarePaneTomlPythonTextualSpec",
    "AwarePaneTomlSpec",
    "AwareRenderComponentTomlBuildSpec",
    "AwareRenderComponentTomlDartFlutterSpec",
    "AwareRenderComponentTomlDartSpec",
    "AwareRenderComponentTomlPackageSpec",
    "AwareRenderComponentTomlPythonSpec",
    "AwareRenderComponentTomlPythonTextualSpec",
    "AwareRenderComponentTomlSpec",
]
