from __future__ import annotations

# Auto-generated by Aware package strategy.
#
# Stable delegator: load bootstrap metadata from embedded `_aware/python.bootstrap.json`
# and let the ORM runtime handle deterministic module import + Pydantic rebuild.
#
# NOTE: The actual bootstrap mechanics live in aware_orm runtime so this file
# stays tiny and stable across package generations.

from aware_orm.runtime.package_bootstrap import bootstrap_orm_package_from_artifacts
from aware_orm.runtime.package_install import install_package_runtime_artifacts


def _bootstrap_models() -> None:
    """Import generated modules and rebuild ORM models once."""
    bootstrap_orm_package_from_artifacts(package_prefix=__name__)
    install_package_runtime_artifacts(package_prefix=__name__, strict=True)


# Run bootstrap on import so Pydantic models are usable immediately.
_bootstrap_models()
