from aware_meta.materialization.contracts import (
    MaterializationExecutionObserver,
    MaterializationLaneContext,
    MaterializationPlan,
    MaterializationStep,
    MaterializationStepResult,
    MaterializationStepRunner,
    validate_materialization_plan,
)
from aware_meta.materialization.executor import (
    MaterializationExecutionError,
    MaterializationExecutor,
)
from aware_meta.materialization.receipts import (
    MaterializationRunReceipt,
    MaterializationStepReceipt,
    encode_materialization_run_receipt,
)
from aware_meta.materialization.artifact_lifecycle import (
    LanguageMaterializationArtifactChange,
    LanguageMaterializationArtifactChangeKind,
    LanguageMaterializationArtifactKind,
    LanguageMaterializationArtifactLifecycleBuildRequest,
    LanguageMaterializationArtifactLifecycleReceipt,
    LanguageMaterializationArtifactLifecycleResult,
    LanguageMaterializationArtifactMutationRecord,
    LanguageMaterializationArtifactTracker,
    LanguageMaterializationFileSnapshot,
    LanguageMaterializationOutcomeSummary,
    LanguageMaterializationPackageOutcome,
    LanguageMaterializationProducerStep,
    LanguageMaterializationStageability,
    build_language_materialization_artifact_lifecycle,
    build_language_materialization_artifact_lifecycle_receipt,
    language_materialization_artifact_mutation_record,
    language_materialization_classify_output_artifact_kind,
    language_materialization_direct_write_mutation_record,
    language_materialization_path_relative_to,
    language_materialization_repo_identity_path,
    language_materialization_snapshot_file,
    language_materialization_stageability,
)
from aware_meta.materialization.language_service import (
    GraphMaterializationRuntimeBatchRequest,
    GraphMaterializationRuntimeBatchResult,
    GraphMaterializationProfile,
    GraphMaterializationStage,
    GraphMaterializationTransformRequest,
    GraphMaterializationTransformResult,
    GraphMaterializationTransformService,
    LanguageMaterializationArtifactOutput,
    LanguageMaterializationGeneratedFile,
    LanguageMaterializationManifestSnapshot,
    LanguageMaterializationOwnershipReceipt,
    LanguageMaterializationPackageOutput,
    LanguageMaterializationPluginDeclaredOutput,
    LanguageMaterializationRenderRequest,
    LanguageMaterializationRenderResult,
    LanguageMaterializationStep,
    LanguagePluginDeclaredOutputProductionRequest,
    LanguagePluginDeclaredOutputProductionResult,
    LanguagePluginMaterializationRequest,
    LanguagePluginMaterializationResult,
    LanguagePluginMaterializationService,
    RuntimeToLanguageClosureLoweringRequest,
    RuntimeToLanguageClosureLoweringResult,
    RuntimeToLanguageClosureLoweringService,
    RuntimeToLanguageLoweringCache,
    materialize_object_config_graph_via_language_plugin,
    plan_language_plugin_declared_outputs,
    produce_language_plugin_declared_outputs,
    render_language_materialization,
)
from aware_meta.materialization.package_runner import (
    LanguageMaterializationPackageBuildRequest,
    LanguageMaterializationPackageBuildResult,
    build_language_materialization_packages,
)
from aware_meta.materialization.post_step_plan import (
    LanguageMaterializationPostStepInput,
    LanguageMaterializationPostStepPlan,
    LanguageMaterializationPostStepPlanItem,
    LanguageMaterializationPostStepPlanRequest,
    canonical_language_materialization_post_step_tool_id,
    plan_language_materialization_post_steps,
)
from aware_meta.materialization.post_step_executor import (
    LanguageMaterializationPostStepExecution,
    LanguageMaterializationPostStepExecutionRequest,
    LanguageMaterializationPostStepReceipt,
    execute_language_materialization_post_steps,
)
from aware_meta.materialization.post_step_target_result import (
    LanguageMaterializationPostStepExecutionResult,
    LanguageMaterializationPostStepPackageContext,
    LanguageMaterializationPostStepPackageLifecycleInput,
    LanguageMaterializationPostStepPackageLifecycleResult,
    LanguageMaterializationPostStepPackageTargets,
    LanguageMaterializationPostStepLifecycleReconciliationRequest,
    LanguageMaterializationPostStepLifecycleReconciliationResult,
    LanguageMaterializationPostStepTargetDiscoveryRequest,
    LanguageMaterializationPostStepTargetDiscoveryResult,
    discover_language_materialization_post_step_targets,
    language_materialization_post_step_execution_path_hints,
    reconcile_language_materialization_post_step_lifecycle,
)
from aware_meta.materialization.tool_runner import (
    LanguageMaterializationPreparedToolCommand,
    LanguageMaterializationToolCommandRequest,
    prepare_language_materialization_tool_command,
    resolve_language_materialization_tool_spec,
)

_SERVICE_EXPORTS = frozenset(
    {
        "ObjectConfigGraphPackageLeafMaterializationResult",
        "materialize_object_config_graph_package_leaf_from_manifest",
        "stable_object_config_graph_package_branch_id",
        "stable_semantic_package_branch_id",
    }
)


def __getattr__(name: str) -> object:
    if name not in _SERVICE_EXPORTS:
        raise AttributeError(name)
    from importlib import import_module

    _service = import_module("aware_meta.materialization.service")

    value = getattr(_service, name)
    globals()[name] = value
    return value


__all__ = [
    "GraphMaterializationRuntimeBatchRequest",
    "GraphMaterializationRuntimeBatchResult",
    "GraphMaterializationProfile",
    "GraphMaterializationStage",
    "GraphMaterializationTransformRequest",
    "GraphMaterializationTransformResult",
    "GraphMaterializationTransformService",
    "LanguageMaterializationArtifactChange",
    "LanguageMaterializationArtifactChangeKind",
    "LanguageMaterializationArtifactKind",
    "LanguageMaterializationArtifactLifecycleBuildRequest",
    "LanguageMaterializationArtifactLifecycleReceipt",
    "LanguageMaterializationArtifactLifecycleResult",
    "LanguageMaterializationArtifactMutationRecord",
    "LanguageMaterializationArtifactOutput",
    "LanguageMaterializationArtifactTracker",
    "LanguageMaterializationFileSnapshot",
    "LanguageMaterializationGeneratedFile",
    "LanguageMaterializationManifestSnapshot",
    "LanguageMaterializationOwnershipReceipt",
    "LanguageMaterializationOutcomeSummary",
    "LanguageMaterializationPackageOutcome",
    "LanguageMaterializationPackageOutput",
    "LanguageMaterializationPackageBuildRequest",
    "LanguageMaterializationPackageBuildResult",
    "LanguageMaterializationPluginDeclaredOutput",
    "LanguageMaterializationPostStepInput",
    "LanguageMaterializationPostStepExecution",
    "LanguageMaterializationPostStepExecutionRequest",
    "LanguageMaterializationPostStepExecutionResult",
    "LanguageMaterializationPostStepPackageContext",
    "LanguageMaterializationPostStepPackageLifecycleInput",
    "LanguageMaterializationPostStepPackageLifecycleResult",
    "LanguageMaterializationPostStepPackageTargets",
    "LanguageMaterializationPostStepLifecycleReconciliationRequest",
    "LanguageMaterializationPostStepLifecycleReconciliationResult",
    "LanguageMaterializationPostStepPlan",
    "LanguageMaterializationPostStepPlanItem",
    "LanguageMaterializationPostStepPlanRequest",
    "LanguageMaterializationPostStepReceipt",
    "LanguageMaterializationPostStepTargetDiscoveryRequest",
    "LanguageMaterializationPostStepTargetDiscoveryResult",
    "LanguageMaterializationPreparedToolCommand",
    "LanguageMaterializationProducerStep",
    "LanguageMaterializationRenderRequest",
    "LanguageMaterializationRenderResult",
    "LanguageMaterializationStageability",
    "LanguageMaterializationStep",
    "LanguageMaterializationToolCommandRequest",
    "LanguagePluginDeclaredOutputProductionRequest",
    "LanguagePluginDeclaredOutputProductionResult",
    "LanguagePluginMaterializationRequest",
    "LanguagePluginMaterializationResult",
    "LanguagePluginMaterializationService",
    "MaterializationExecutionError",
    "MaterializationExecutionObserver",
    "MaterializationExecutor",
    "MaterializationLaneContext",
    "MaterializationPlan",
    "MaterializationRunReceipt",
    "MaterializationStep",
    "MaterializationStepReceipt",
    "MaterializationStepResult",
    "MaterializationStepRunner",
    "RuntimeToLanguageClosureLoweringRequest",
    "RuntimeToLanguageClosureLoweringResult",
    "RuntimeToLanguageClosureLoweringService",
    "RuntimeToLanguageLoweringCache",
    "ObjectConfigGraphPackageLeafMaterializationResult",
    "build_language_materialization_artifact_lifecycle",
    "build_language_materialization_artifact_lifecycle_receipt",
    "build_language_materialization_packages",
    "canonical_language_materialization_post_step_tool_id",
    "discover_language_materialization_post_step_targets",
    "encode_materialization_run_receipt",
    "execute_language_materialization_post_steps",
    "language_materialization_artifact_mutation_record",
    "language_materialization_post_step_execution_path_hints",
    "language_materialization_classify_output_artifact_kind",
    "language_materialization_direct_write_mutation_record",
    "language_materialization_path_relative_to",
    "language_materialization_repo_identity_path",
    "language_materialization_snapshot_file",
    "language_materialization_stageability",
    "materialize_object_config_graph_package_leaf_from_manifest",
    "materialize_object_config_graph_via_language_plugin",
    "plan_language_plugin_declared_outputs",
    "plan_language_materialization_post_steps",
    "prepare_language_materialization_tool_command",
    "produce_language_plugin_declared_outputs",
    "render_language_materialization",
    "reconcile_language_materialization_post_step_lifecycle",
    "resolve_language_materialization_tool_spec",
    "stable_object_config_graph_package_branch_id",
    "stable_semantic_package_branch_id",
    "validate_materialization_plan",
]
