# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from typing import (
    TYPE_CHECKING,
    cast,
)

# Runtime
from aware_meta.runtime.generated_handlers import (
    constructor,
    instance,
)

if TYPE_CHECKING:
    from aware_meta_ontology.function.function_call import FunctionCall
    from aware_orm.models.orm_model import ORMModel
    from aware_orm.session.session import Session
    from aware_meta.runtime.generated_handlers import HandlerContext


async def action__set_status__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action import set_status as _impl
    from aware_reactivity_ontology.action.action_enums import ActionStatus

    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 0:
        _raw_status = args[0]
    status: ActionStatus = TypeAdapter(ActionStatus).validate_python(_raw_status)
    _raw_result_info: object | None = None
    if "result_info" in kwargs:
        _raw_result_info = kwargs["result_info"]
    elif len(args) > 1:
        _raw_result_info = args[1]
    if _raw_result_info is None:
        _raw_result_info = None
    result_info: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_result_info))
    result = await _impl(action=orm_model, status=status, result_info=result_info)
    return result


async def action__create_via_event__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action import create_via_event as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionStatus
    from uuid import UUID

    _raw_event_id: object | None = None
    if "event_id" in kwargs:
        _raw_event_id = kwargs["event_id"]
    elif len(args) > 0:
        _raw_event_id = args[0]
    event_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_id)
    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 1:
        _raw_config_id = args[1]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 2:
        _raw_status = args[2]
    if _raw_status is None:
        _raw_status = ActionStatus.requested
    status: ActionStatus = TypeAdapter(ActionStatus).validate_python(_raw_status)
    _raw_execution_context: object | None = None
    if "execution_context" in kwargs:
        _raw_execution_context = kwargs["execution_context"]
    elif len(args) > 3:
        _raw_execution_context = args[3]
    if _raw_execution_context is None:
        _raw_execution_context = JsonObject()
    execution_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_execution_context)
    result = await _impl(event_id=event_id, config_id=config_id, status=status, execution_context=execution_context)
    return result, result


async def action_config__create__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_config import create as _impl
    from aware_code.types import JsonObject

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    description: str = TypeAdapter(str).validate_python(_raw_description)
    _raw_action_type: object | None = None
    if "action_type" in kwargs:
        _raw_action_type = kwargs["action_type"]
    elif len(args) > 2:
        _raw_action_type = args[2]
    action_type: str = TypeAdapter(str).validate_python(_raw_action_type)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 3:
        _raw_is_enabled = args[3]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_system: object | None = None
    if "is_system" in kwargs:
        _raw_is_system = kwargs["is_system"]
    elif len(args) > 4:
        _raw_is_system = args[4]
    if _raw_is_system is None:
        _raw_is_system = False
    is_system: bool = TypeAdapter(bool).validate_python(_raw_is_system)
    _raw_require_authentication: object | None = None
    if "require_authentication" in kwargs:
        _raw_require_authentication = kwargs["require_authentication"]
    elif len(args) > 5:
        _raw_require_authentication = args[5]
    if _raw_require_authentication is None:
        _raw_require_authentication = True
    require_authentication: bool = TypeAdapter(bool).validate_python(_raw_require_authentication)
    _raw_allowed_roles: object | None = None
    if "allowed_roles" in kwargs:
        _raw_allowed_roles = kwargs["allowed_roles"]
    elif len(args) > 6:
        _raw_allowed_roles = args[6]
    if _raw_allowed_roles is None:
        _raw_allowed_roles = []
    allowed_roles: list[str] = TypeAdapter(list[str]).validate_python(_raw_allowed_roles)
    _raw_action_schema: object | None = None
    if "action_schema" in kwargs:
        _raw_action_schema = kwargs["action_schema"]
    elif len(args) > 7:
        _raw_action_schema = args[7]
    if _raw_action_schema is None:
        _raw_action_schema = JsonObject()
    action_schema: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_action_schema)
    result = await _impl(
        name=name,
        description=description,
        action_type=action_type,
        is_enabled=is_enabled,
        is_system=is_system,
        require_authentication=require_authentication,
        allowed_roles=allowed_roles,
        action_schema=action_schema,
    )
    return result, result


async def action_execution__add_feedback__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_execution import add_feedback as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionFeedbackStage, ActionFeedbackStatus

    _raw_sequence: object | None = None
    if "sequence" in kwargs:
        _raw_sequence = kwargs["sequence"]
    elif len(args) > 0:
        _raw_sequence = args[0]
    sequence: int = TypeAdapter(int).validate_python(_raw_sequence)
    _raw_stage: object | None = None
    if "stage" in kwargs:
        _raw_stage = kwargs["stage"]
    elif len(args) > 1:
        _raw_stage = args[1]
    stage: ActionFeedbackStage = TypeAdapter(ActionFeedbackStage).validate_python(_raw_stage)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 2:
        _raw_status = args[2]
    status: ActionFeedbackStatus = TypeAdapter(ActionFeedbackStatus).validate_python(_raw_status)
    _raw_created_at_unix_ms: object | None = None
    if "created_at_unix_ms" in kwargs:
        _raw_created_at_unix_ms = kwargs["created_at_unix_ms"]
    elif len(args) > 3:
        _raw_created_at_unix_ms = args[3]
    if _raw_created_at_unix_ms is None:
        _raw_created_at_unix_ms = 0
    created_at_unix_ms: int = TypeAdapter(int).validate_python(_raw_created_at_unix_ms)
    _raw_message: object | None = None
    if "message" in kwargs:
        _raw_message = kwargs["message"]
    elif len(args) > 4:
        _raw_message = args[4]
    if _raw_message is None:
        _raw_message = None
    message: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_message))
    _raw_payload: object | None = None
    if "payload" in kwargs:
        _raw_payload = kwargs["payload"]
    elif len(args) > 5:
        _raw_payload = args[5]
    if _raw_payload is None:
        _raw_payload = JsonObject()
    payload: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_payload)
    result = await _impl(
        action_execution=orm_model,
        sequence=sequence,
        stage=stage,
        status=status,
        created_at_unix_ms=created_at_unix_ms,
        message=message,
        payload=payload,
    )
    return result


async def action_execution__set_status__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_execution import set_status as _impl
    from aware_reactivity_ontology.action.action_enums import ActionExecutionStatus

    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 0:
        _raw_status = args[0]
    status: ActionExecutionStatus = TypeAdapter(ActionExecutionStatus).validate_python(_raw_status)
    _raw_result_info: object | None = None
    if "result_info" in kwargs:
        _raw_result_info = kwargs["result_info"]
    elif len(args) > 1:
        _raw_result_info = args[1]
    if _raw_result_info is None:
        _raw_result_info = None
    result_info: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_result_info))
    result = await _impl(action_execution=orm_model, status=status, result_info=result_info)
    return result


async def action_execution__create_via_action_intent__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_execution import create_via_action_intent as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionExecutionStatus
    from uuid import UUID

    _raw_action_intent_id: object | None = None
    if "action_intent_id" in kwargs:
        _raw_action_intent_id = kwargs["action_intent_id"]
    elif len(args) > 0:
        _raw_action_intent_id = args[0]
    action_intent_id: UUID = TypeAdapter(UUID).validate_python(_raw_action_intent_id)
    _raw_execution_key: object | None = None
    if "execution_key" in kwargs:
        _raw_execution_key = kwargs["execution_key"]
    elif len(args) > 1:
        _raw_execution_key = args[1]
    if _raw_execution_key is None:
        _raw_execution_key = "primary"
    execution_key: str = TypeAdapter(str).validate_python(_raw_execution_key)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 2:
        _raw_status = args[2]
    if _raw_status is None:
        _raw_status = ActionExecutionStatus.created
    status: ActionExecutionStatus = TypeAdapter(ActionExecutionStatus).validate_python(_raw_status)
    _raw_execution_context: object | None = None
    if "execution_context" in kwargs:
        _raw_execution_context = kwargs["execution_context"]
    elif len(args) > 3:
        _raw_execution_context = args[3]
    if _raw_execution_context is None:
        _raw_execution_context = JsonObject()
    execution_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_execution_context)
    _raw_executor_ref: object | None = None
    if "executor_ref" in kwargs:
        _raw_executor_ref = kwargs["executor_ref"]
    elif len(args) > 4:
        _raw_executor_ref = args[4]
    if _raw_executor_ref is None:
        _raw_executor_ref = None
    executor_ref: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_executor_ref))
    _raw_result_info: object | None = None
    if "result_info" in kwargs:
        _raw_result_info = kwargs["result_info"]
    elif len(args) > 5:
        _raw_result_info = args[5]
    if _raw_result_info is None:
        _raw_result_info = None
    result_info: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_result_info))
    result = await _impl(
        action_intent_id=action_intent_id,
        execution_key=execution_key,
        status=status,
        execution_context=execution_context,
        executor_ref=executor_ref,
        result_info=result_info,
    )
    return result, result


async def action_feedback__create_via_action_execution__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_feedback import create_via_action_execution as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionFeedbackStage, ActionFeedbackStatus
    from uuid import UUID

    _raw_action_execution_id: object | None = None
    if "action_execution_id" in kwargs:
        _raw_action_execution_id = kwargs["action_execution_id"]
    elif len(args) > 0:
        _raw_action_execution_id = args[0]
    action_execution_id: UUID = TypeAdapter(UUID).validate_python(_raw_action_execution_id)
    _raw_sequence: object | None = None
    if "sequence" in kwargs:
        _raw_sequence = kwargs["sequence"]
    elif len(args) > 1:
        _raw_sequence = args[1]
    sequence: int = TypeAdapter(int).validate_python(_raw_sequence)
    _raw_stage: object | None = None
    if "stage" in kwargs:
        _raw_stage = kwargs["stage"]
    elif len(args) > 2:
        _raw_stage = args[2]
    stage: ActionFeedbackStage = TypeAdapter(ActionFeedbackStage).validate_python(_raw_stage)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 3:
        _raw_status = args[3]
    status: ActionFeedbackStatus = TypeAdapter(ActionFeedbackStatus).validate_python(_raw_status)
    _raw_created_at_unix_ms: object | None = None
    if "created_at_unix_ms" in kwargs:
        _raw_created_at_unix_ms = kwargs["created_at_unix_ms"]
    elif len(args) > 4:
        _raw_created_at_unix_ms = args[4]
    if _raw_created_at_unix_ms is None:
        _raw_created_at_unix_ms = 0
    created_at_unix_ms: int = TypeAdapter(int).validate_python(_raw_created_at_unix_ms)
    _raw_message: object | None = None
    if "message" in kwargs:
        _raw_message = kwargs["message"]
    elif len(args) > 5:
        _raw_message = args[5]
    if _raw_message is None:
        _raw_message = None
    message: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_message))
    _raw_payload: object | None = None
    if "payload" in kwargs:
        _raw_payload = kwargs["payload"]
    elif len(args) > 6:
        _raw_payload = args[6]
    if _raw_payload is None:
        _raw_payload = JsonObject()
    payload: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_payload)
    result = await _impl(
        action_execution_id=action_execution_id,
        sequence=sequence,
        stage=stage,
        status=status,
        created_at_unix_ms=created_at_unix_ms,
        message=message,
        payload=payload,
    )
    return result, result


async def action_intent__start_execution__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_intent import start_execution as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionExecutionStatus

    _raw_execution_key: object | None = None
    if "execution_key" in kwargs:
        _raw_execution_key = kwargs["execution_key"]
    elif len(args) > 0:
        _raw_execution_key = args[0]
    if _raw_execution_key is None:
        _raw_execution_key = "primary"
    execution_key: str = TypeAdapter(str).validate_python(_raw_execution_key)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 1:
        _raw_status = args[1]
    if _raw_status is None:
        _raw_status = ActionExecutionStatus.created
    status: ActionExecutionStatus = TypeAdapter(ActionExecutionStatus).validate_python(_raw_status)
    _raw_execution_context: object | None = None
    if "execution_context" in kwargs:
        _raw_execution_context = kwargs["execution_context"]
    elif len(args) > 2:
        _raw_execution_context = args[2]
    if _raw_execution_context is None:
        _raw_execution_context = JsonObject()
    execution_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_execution_context)
    result = await _impl(
        action_intent=orm_model, execution_key=execution_key, status=status, execution_context=execution_context
    )
    return result


async def action_intent__set_status__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_intent import set_status as _impl
    from aware_reactivity_ontology.action.action_enums import ActionIntentStatus

    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 0:
        _raw_status = args[0]
    status: ActionIntentStatus = TypeAdapter(ActionIntentStatus).validate_python(_raw_status)
    result = await _impl(action_intent=orm_model, status=status)
    return result


async def action_intent__create_via_event__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.action.action_intent import create_via_event as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionIntentStatus
    from uuid import UUID

    _raw_event_id: object | None = None
    if "event_id" in kwargs:
        _raw_event_id = kwargs["event_id"]
    elif len(args) > 0:
        _raw_event_id = args[0]
    event_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_id)
    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 1:
        _raw_config_id = args[1]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_actor_subscription_id: object | None = None
    if "actor_subscription_id" in kwargs:
        _raw_actor_subscription_id = kwargs["actor_subscription_id"]
    elif len(args) > 2:
        _raw_actor_subscription_id = args[2]
    actor_subscription_id: UUID = TypeAdapter(UUID).validate_python(_raw_actor_subscription_id)
    _raw_action_type: object | None = None
    if "action_type" in kwargs:
        _raw_action_type = kwargs["action_type"]
    elif len(args) > 3:
        _raw_action_type = args[3]
    if _raw_action_type is None:
        _raw_action_type = None
    action_type: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_action_type))
    _raw_actor_id: object | None = None
    if "actor_id" in kwargs:
        _raw_actor_id = kwargs["actor_id"]
    elif len(args) > 4:
        _raw_actor_id = args[4]
    if _raw_actor_id is None:
        _raw_actor_id = None
    actor_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_actor_id))
    _raw_target_actor_id: object | None = None
    if "target_actor_id" in kwargs:
        _raw_target_actor_id = kwargs["target_actor_id"]
    elif len(args) > 5:
        _raw_target_actor_id = args[5]
    if _raw_target_actor_id is None:
        _raw_target_actor_id = None
    target_actor_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_target_actor_id))
    _raw_action_payload: object | None = None
    if "action_payload" in kwargs:
        _raw_action_payload = kwargs["action_payload"]
    elif len(args) > 6:
        _raw_action_payload = args[6]
    if _raw_action_payload is None:
        _raw_action_payload = JsonObject()
    action_payload: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_action_payload)
    _raw_subscription_filter_config: object | None = None
    if "subscription_filter_config" in kwargs:
        _raw_subscription_filter_config = kwargs["subscription_filter_config"]
    elif len(args) > 7:
        _raw_subscription_filter_config = args[7]
    if _raw_subscription_filter_config is None:
        _raw_subscription_filter_config = JsonObject()
    subscription_filter_config: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_subscription_filter_config)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 8:
        _raw_priority = args[8]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 9:
        _raw_status = args[9]
    if _raw_status is None:
        _raw_status = ActionIntentStatus.requested
    status: ActionIntentStatus = TypeAdapter(ActionIntentStatus).validate_python(_raw_status)
    result = await _impl(
        event_id=event_id,
        config_id=config_id,
        actor_subscription_id=actor_subscription_id,
        action_type=action_type,
        actor_id=actor_id,
        target_actor_id=target_actor_id,
        action_payload=action_payload,
        subscription_filter_config=subscription_filter_config,
        priority=priority,
        status=status,
    )
    return result, result


async def condition__create__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition import create as _impl
    from aware_code.types import JsonObject
    from uuid import UUID

    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 0:
        _raw_config_id = args[0]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_activation_id: object | None = None
    if "activation_id" in kwargs:
        _raw_activation_id = kwargs["activation_id"]
    elif len(args) > 1:
        _raw_activation_id = args[1]
    activation_id: UUID = TypeAdapter(UUID).validate_python(_raw_activation_id)
    _raw_trigger_object_instance_graph_commit_id: object | None = None
    if "trigger_object_instance_graph_commit_id" in kwargs:
        _raw_trigger_object_instance_graph_commit_id = kwargs["trigger_object_instance_graph_commit_id"]
    elif len(args) > 2:
        _raw_trigger_object_instance_graph_commit_id = args[2]
    trigger_object_instance_graph_commit_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_trigger_object_instance_graph_commit_id
    )
    _raw_arguments: object | None = None
    if "arguments" in kwargs:
        _raw_arguments = kwargs["arguments"]
    elif len(args) > 3:
        _raw_arguments = args[3]
    if _raw_arguments is None:
        _raw_arguments = JsonObject()
    arguments: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_arguments)
    result = await _impl(
        config_id=config_id,
        activation_id=activation_id,
        trigger_object_instance_graph_commit_id=trigger_object_instance_graph_commit_id,
        arguments=arguments,
    )
    return result, result


async def condition_config__create__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config import create as _impl
    from aware_reactivity_ontology.condition.condition_enums import ConditionLogicStrategy

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    description: str = TypeAdapter(str).validate_python(_raw_description)
    _raw_logic_strategy: object | None = None
    if "logic_strategy" in kwargs:
        _raw_logic_strategy = kwargs["logic_strategy"]
    elif len(args) > 2:
        _raw_logic_strategy = args[2]
    if _raw_logic_strategy is None:
        _raw_logic_strategy = ConditionLogicStrategy.all
    logic_strategy: ConditionLogicStrategy = TypeAdapter(ConditionLogicStrategy).validate_python(_raw_logic_strategy)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 3:
        _raw_is_enabled = args[3]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_system: object | None = None
    if "is_system" in kwargs:
        _raw_is_system = kwargs["is_system"]
    elif len(args) > 4:
        _raw_is_system = args[4]
    if _raw_is_system is None:
        _raw_is_system = False
    is_system: bool = TypeAdapter(bool).validate_python(_raw_is_system)
    result = await _impl(
        name=name, description=description, logic_strategy=logic_strategy, is_enabled=is_enabled, is_system=is_system
    )
    return result, result


async def condition_config__add_class_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config import add_class_config as _impl
    from aware_reactivity_ontology.condition.condition_enums import ClassSelectionMode, ConditionLogicStrategy
    from uuid import UUID

    _raw_class_config_id: object | None = None
    if "class_config_id" in kwargs:
        _raw_class_config_id = kwargs["class_config_id"]
    elif len(args) > 0:
        _raw_class_config_id = args[0]
    class_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_class_config_id)
    _raw_class_selection: object | None = None
    if "class_selection" in kwargs:
        _raw_class_selection = kwargs["class_selection"]
    elif len(args) > 1:
        _raw_class_selection = args[1]
    if _raw_class_selection is None:
        _raw_class_selection = ClassSelectionMode.base_class
    class_selection: ClassSelectionMode = TypeAdapter(ClassSelectionMode).validate_python(_raw_class_selection)
    _raw_class_logic: object | None = None
    if "class_logic" in kwargs:
        _raw_class_logic = kwargs["class_logic"]
    elif len(args) > 2:
        _raw_class_logic = args[2]
    if _raw_class_logic is None:
        _raw_class_logic = ConditionLogicStrategy.all
    class_logic: ConditionLogicStrategy = TypeAdapter(ConditionLogicStrategy).validate_python(_raw_class_logic)
    _raw_require_existence: object | None = None
    if "require_existence" in kwargs:
        _raw_require_existence = kwargs["require_existence"]
    elif len(args) > 3:
        _raw_require_existence = args[3]
    if _raw_require_existence is None:
        _raw_require_existence = True
    require_existence: bool = TypeAdapter(bool).validate_python(_raw_require_existence)
    result = await _impl(
        condition_config=orm_model,
        class_config_id=class_config_id,
        class_selection=class_selection,
        class_logic=class_logic,
        require_existence=require_existence,
    )
    return result


async def condition_config_attribute_config__set_primitive_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_attribute_config import set_primitive_config as _impl
    from uuid import UUID

    _raw_primitive_config_id: object | None = None
    if "primitive_config_id" in kwargs:
        _raw_primitive_config_id = kwargs["primitive_config_id"]
    elif len(args) > 0:
        _raw_primitive_config_id = args[0]
    primitive_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_primitive_config_id)
    _raw_primitive_value: object | None = None
    if "primitive_value" in kwargs:
        _raw_primitive_value = kwargs["primitive_value"]
    elif len(args) > 1:
        _raw_primitive_value = args[1]
    primitive_value: str = TypeAdapter(str).validate_python(_raw_primitive_value)
    _raw_range_min: object | None = None
    if "range_min" in kwargs:
        _raw_range_min = kwargs["range_min"]
    elif len(args) > 2:
        _raw_range_min = args[2]
    if _raw_range_min is None:
        _raw_range_min = None
    range_min: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_range_min))
    _raw_range_max: object | None = None
    if "range_max" in kwargs:
        _raw_range_max = kwargs["range_max"]
    elif len(args) > 3:
        _raw_range_max = args[3]
    if _raw_range_max is None:
        _raw_range_max = None
    range_max: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_range_max))
    result = await _impl(
        condition_config_attribute_config=orm_model,
        primitive_config_id=primitive_config_id,
        primitive_value=primitive_value,
        range_min=range_min,
        range_max=range_max,
    )
    return result


async def condition_config_attribute_config__set_enum_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_attribute_config import set_enum_config as _impl
    from aware_reactivity_ontology.condition.condition_enums import EnumMatchMode
    from uuid import UUID

    _raw_enum_config_id: object | None = None
    if "enum_config_id" in kwargs:
        _raw_enum_config_id = kwargs["enum_config_id"]
    elif len(args) > 0:
        _raw_enum_config_id = args[0]
    enum_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_enum_config_id)
    _raw_enum_option_ids: object | None = None
    if "enum_option_ids" in kwargs:
        _raw_enum_option_ids = kwargs["enum_option_ids"]
    elif len(args) > 1:
        _raw_enum_option_ids = args[1]
    if _raw_enum_option_ids is None:
        _raw_enum_option_ids = []
    enum_option_ids: list[UUID] = TypeAdapter(list[UUID]).validate_python(_raw_enum_option_ids)
    _raw_match_mode: object | None = None
    if "match_mode" in kwargs:
        _raw_match_mode = kwargs["match_mode"]
    elif len(args) > 2:
        _raw_match_mode = args[2]
    if _raw_match_mode is None:
        _raw_match_mode = EnumMatchMode.any_of
    match_mode: EnumMatchMode = TypeAdapter(EnumMatchMode).validate_python(_raw_match_mode)
    result = await _impl(
        condition_config_attribute_config=orm_model,
        enum_config_id=enum_config_id,
        enum_option_ids=enum_option_ids,
        match_mode=match_mode,
    )
    return result


async def condition_config_attribute_config__set_relationship_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_attribute_config import (
        set_relationship_config as _impl,
    )
    from aware_reactivity_ontology.condition.condition_enums import RelationshipEvalMode
    from uuid import UUID

    _raw_class_config_relationship_id: object | None = None
    if "class_config_relationship_id" in kwargs:
        _raw_class_config_relationship_id = kwargs["class_config_relationship_id"]
    elif len(args) > 0:
        _raw_class_config_relationship_id = args[0]
    class_config_relationship_id: UUID = TypeAdapter(UUID).validate_python(_raw_class_config_relationship_id)
    _raw_eval_mode: object | None = None
    if "eval_mode" in kwargs:
        _raw_eval_mode = kwargs["eval_mode"]
    elif len(args) > 1:
        _raw_eval_mode = args[1]
    if _raw_eval_mode is None:
        _raw_eval_mode = RelationshipEvalMode.exists
    eval_mode: RelationshipEvalMode = TypeAdapter(RelationshipEvalMode).validate_python(_raw_eval_mode)
    _raw_count_threshold: object | None = None
    if "count_threshold" in kwargs:
        _raw_count_threshold = kwargs["count_threshold"]
    elif len(args) > 2:
        _raw_count_threshold = args[2]
    if _raw_count_threshold is None:
        _raw_count_threshold = None
    count_threshold: int | None = cast(int | None, TypeAdapter(int | None).validate_python(_raw_count_threshold))
    result = await _impl(
        condition_config_attribute_config=orm_model,
        class_config_relationship_id=class_config_relationship_id,
        eval_mode=eval_mode,
        count_threshold=count_threshold,
    )
    return result


async def condition_config_attribute_config__create_via_condition_config_class_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_attribute_config import (
        create_via_condition_config_class_config as _impl,
    )
    from aware_reactivity_ontology.condition.condition_enums import ConditionOperator
    from uuid import UUID

    _raw_condition_config_class_config_id: object | None = None
    if "condition_config_class_config_id" in kwargs:
        _raw_condition_config_class_config_id = kwargs["condition_config_class_config_id"]
    elif len(args) > 0:
        _raw_condition_config_class_config_id = args[0]
    condition_config_class_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_config_class_config_id)
    _raw_attribute_config_id: object | None = None
    if "attribute_config_id" in kwargs:
        _raw_attribute_config_id = kwargs["attribute_config_id"]
    elif len(args) > 1:
        _raw_attribute_config_id = args[1]
    attribute_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_attribute_config_id)
    _raw_operator: object | None = None
    if "operator" in kwargs:
        _raw_operator = kwargs["operator"]
    elif len(args) > 2:
        _raw_operator = args[2]
    operator: ConditionOperator = TypeAdapter(ConditionOperator).validate_python(_raw_operator)
    _raw_negate: object | None = None
    if "negate" in kwargs:
        _raw_negate = kwargs["negate"]
    elif len(args) > 3:
        _raw_negate = args[3]
    if _raw_negate is None:
        _raw_negate = False
    negate: bool = TypeAdapter(bool).validate_python(_raw_negate)
    result = await _impl(
        condition_config_class_config_id=condition_config_class_config_id,
        attribute_config_id=attribute_config_id,
        operator=operator,
        negate=negate,
    )
    return result, result


async def condition_config_class_config__add_attribute_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_class_config import add_attribute_config as _impl
    from aware_reactivity_ontology.condition.condition_enums import ConditionOperator
    from uuid import UUID

    _raw_attribute_config_id: object | None = None
    if "attribute_config_id" in kwargs:
        _raw_attribute_config_id = kwargs["attribute_config_id"]
    elif len(args) > 0:
        _raw_attribute_config_id = args[0]
    attribute_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_attribute_config_id)
    _raw_operator: object | None = None
    if "operator" in kwargs:
        _raw_operator = kwargs["operator"]
    elif len(args) > 1:
        _raw_operator = args[1]
    operator: ConditionOperator = TypeAdapter(ConditionOperator).validate_python(_raw_operator)
    _raw_negate: object | None = None
    if "negate" in kwargs:
        _raw_negate = kwargs["negate"]
    elif len(args) > 2:
        _raw_negate = args[2]
    if _raw_negate is None:
        _raw_negate = False
    negate: bool = TypeAdapter(bool).validate_python(_raw_negate)
    result = await _impl(
        condition_config_class_config=orm_model,
        attribute_config_id=attribute_config_id,
        operator=operator,
        negate=negate,
    )
    return result


async def condition_config_class_config__create_via_condition_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_class_config import (
        create_via_condition_config as _impl,
    )
    from aware_reactivity_ontology.condition.condition_enums import ClassSelectionMode, ConditionLogicStrategy
    from uuid import UUID

    _raw_condition_config_id: object | None = None
    if "condition_config_id" in kwargs:
        _raw_condition_config_id = kwargs["condition_config_id"]
    elif len(args) > 0:
        _raw_condition_config_id = args[0]
    condition_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_config_id)
    _raw_class_config_id: object | None = None
    if "class_config_id" in kwargs:
        _raw_class_config_id = kwargs["class_config_id"]
    elif len(args) > 1:
        _raw_class_config_id = args[1]
    class_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_class_config_id)
    _raw_class_selection: object | None = None
    if "class_selection" in kwargs:
        _raw_class_selection = kwargs["class_selection"]
    elif len(args) > 2:
        _raw_class_selection = args[2]
    if _raw_class_selection is None:
        _raw_class_selection = ClassSelectionMode.base_class
    class_selection: ClassSelectionMode = TypeAdapter(ClassSelectionMode).validate_python(_raw_class_selection)
    _raw_class_logic: object | None = None
    if "class_logic" in kwargs:
        _raw_class_logic = kwargs["class_logic"]
    elif len(args) > 3:
        _raw_class_logic = args[3]
    if _raw_class_logic is None:
        _raw_class_logic = ConditionLogicStrategy.all
    class_logic: ConditionLogicStrategy = TypeAdapter(ConditionLogicStrategy).validate_python(_raw_class_logic)
    _raw_require_existence: object | None = None
    if "require_existence" in kwargs:
        _raw_require_existence = kwargs["require_existence"]
    elif len(args) > 4:
        _raw_require_existence = args[4]
    if _raw_require_existence is None:
        _raw_require_existence = True
    require_existence: bool = TypeAdapter(bool).validate_python(_raw_require_existence)
    result = await _impl(
        condition_config_id=condition_config_id,
        class_config_id=class_config_id,
        class_selection=class_selection,
        class_logic=class_logic,
        require_existence=require_existence,
    )
    return result, result


async def condition_config_enum_config__add_enum_option__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_enum_config import add_enum_option as _impl
    from uuid import UUID

    _raw_enum_option_id: object | None = None
    if "enum_option_id" in kwargs:
        _raw_enum_option_id = kwargs["enum_option_id"]
    elif len(args) > 0:
        _raw_enum_option_id = args[0]
    enum_option_id: UUID = TypeAdapter(UUID).validate_python(_raw_enum_option_id)
    result = await _impl(condition_config_enum_config=orm_model, enum_option_id=enum_option_id)
    return result


async def condition_config_enum_config__create_via_condition_config_attribute_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_enum_config import (
        create_via_condition_config_attribute_config as _impl,
    )
    from aware_reactivity_ontology.condition.condition_enums import EnumMatchMode
    from uuid import UUID

    _raw_condition_config_attribute_config_id: object | None = None
    if "condition_config_attribute_config_id" in kwargs:
        _raw_condition_config_attribute_config_id = kwargs["condition_config_attribute_config_id"]
    elif len(args) > 0:
        _raw_condition_config_attribute_config_id = args[0]
    condition_config_attribute_config_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_condition_config_attribute_config_id
    )
    _raw_enum_config_id: object | None = None
    if "enum_config_id" in kwargs:
        _raw_enum_config_id = kwargs["enum_config_id"]
    elif len(args) > 1:
        _raw_enum_config_id = args[1]
    enum_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_enum_config_id)
    _raw_match_mode: object | None = None
    if "match_mode" in kwargs:
        _raw_match_mode = kwargs["match_mode"]
    elif len(args) > 2:
        _raw_match_mode = args[2]
    if _raw_match_mode is None:
        _raw_match_mode = EnumMatchMode.any_of
    match_mode: EnumMatchMode = TypeAdapter(EnumMatchMode).validate_python(_raw_match_mode)
    _raw_enum_option_ids: object | None = None
    if "enum_option_ids" in kwargs:
        _raw_enum_option_ids = kwargs["enum_option_ids"]
    elif len(args) > 3:
        _raw_enum_option_ids = args[3]
    if _raw_enum_option_ids is None:
        _raw_enum_option_ids = []
    enum_option_ids: list[UUID] = TypeAdapter(list[UUID]).validate_python(_raw_enum_option_ids)
    result = await _impl(
        condition_config_attribute_config_id=condition_config_attribute_config_id,
        enum_config_id=enum_config_id,
        match_mode=match_mode,
        enum_option_ids=enum_option_ids,
    )
    return result, result


async def condition_config_enum_option__create_via_condition_config_enum_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_enum_option import (
        create_via_condition_config_enum_config as _impl,
    )
    from uuid import UUID

    _raw_condition_config_enum_config_id: object | None = None
    if "condition_config_enum_config_id" in kwargs:
        _raw_condition_config_enum_config_id = kwargs["condition_config_enum_config_id"]
    elif len(args) > 0:
        _raw_condition_config_enum_config_id = args[0]
    condition_config_enum_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_config_enum_config_id)
    _raw_enum_option_id: object | None = None
    if "enum_option_id" in kwargs:
        _raw_enum_option_id = kwargs["enum_option_id"]
    elif len(args) > 1:
        _raw_enum_option_id = args[1]
    enum_option_id: UUID = TypeAdapter(UUID).validate_python(_raw_enum_option_id)
    result = await _impl(condition_config_enum_config_id=condition_config_enum_config_id, enum_option_id=enum_option_id)
    return result, result


async def condition_config_primitive_config__create_via_condition_config_attribute_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_primitive_config import (
        create_via_condition_config_attribute_config as _impl,
    )
    from uuid import UUID

    _raw_condition_config_attribute_config_id: object | None = None
    if "condition_config_attribute_config_id" in kwargs:
        _raw_condition_config_attribute_config_id = kwargs["condition_config_attribute_config_id"]
    elif len(args) > 0:
        _raw_condition_config_attribute_config_id = args[0]
    condition_config_attribute_config_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_condition_config_attribute_config_id
    )
    _raw_primitive_config_id: object | None = None
    if "primitive_config_id" in kwargs:
        _raw_primitive_config_id = kwargs["primitive_config_id"]
    elif len(args) > 1:
        _raw_primitive_config_id = args[1]
    primitive_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_primitive_config_id)
    _raw_primitive_value: object | None = None
    if "primitive_value" in kwargs:
        _raw_primitive_value = kwargs["primitive_value"]
    elif len(args) > 2:
        _raw_primitive_value = args[2]
    primitive_value: str = TypeAdapter(str).validate_python(_raw_primitive_value)
    _raw_range_min: object | None = None
    if "range_min" in kwargs:
        _raw_range_min = kwargs["range_min"]
    elif len(args) > 3:
        _raw_range_min = args[3]
    if _raw_range_min is None:
        _raw_range_min = None
    range_min: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_range_min))
    _raw_range_max: object | None = None
    if "range_max" in kwargs:
        _raw_range_max = kwargs["range_max"]
    elif len(args) > 4:
        _raw_range_max = args[4]
    if _raw_range_max is None:
        _raw_range_max = None
    range_max: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_range_max))
    result = await _impl(
        condition_config_attribute_config_id=condition_config_attribute_config_id,
        primitive_config_id=primitive_config_id,
        primitive_value=primitive_value,
        range_min=range_min,
        range_max=range_max,
    )
    return result, result


async def condition_config_relationship_config__create_via_condition_config_attribute_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.condition.condition_config_relationship_config import (
        create_via_condition_config_attribute_config as _impl,
    )
    from aware_reactivity_ontology.condition.condition_enums import RelationshipEvalMode
    from uuid import UUID

    _raw_condition_config_attribute_config_id: object | None = None
    if "condition_config_attribute_config_id" in kwargs:
        _raw_condition_config_attribute_config_id = kwargs["condition_config_attribute_config_id"]
    elif len(args) > 0:
        _raw_condition_config_attribute_config_id = args[0]
    condition_config_attribute_config_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_condition_config_attribute_config_id
    )
    _raw_class_config_relationship_id: object | None = None
    if "class_config_relationship_id" in kwargs:
        _raw_class_config_relationship_id = kwargs["class_config_relationship_id"]
    elif len(args) > 1:
        _raw_class_config_relationship_id = args[1]
    class_config_relationship_id: UUID = TypeAdapter(UUID).validate_python(_raw_class_config_relationship_id)
    _raw_eval_mode: object | None = None
    if "eval_mode" in kwargs:
        _raw_eval_mode = kwargs["eval_mode"]
    elif len(args) > 2:
        _raw_eval_mode = args[2]
    if _raw_eval_mode is None:
        _raw_eval_mode = RelationshipEvalMode.exists
    eval_mode: RelationshipEvalMode = TypeAdapter(RelationshipEvalMode).validate_python(_raw_eval_mode)
    _raw_count_threshold: object | None = None
    if "count_threshold" in kwargs:
        _raw_count_threshold = kwargs["count_threshold"]
    elif len(args) > 3:
        _raw_count_threshold = args[3]
    if _raw_count_threshold is None:
        _raw_count_threshold = None
    count_threshold: int | None = cast(int | None, TypeAdapter(int | None).validate_python(_raw_count_threshold))
    result = await _impl(
        condition_config_attribute_config_id=condition_config_attribute_config_id,
        class_config_relationship_id=class_config_relationship_id,
        eval_mode=eval_mode,
        count_threshold=count_threshold,
    )
    return result, result


async def event__create__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event import create as _impl
    from aware_reactivity_ontology.event.event_enums import EventStatus
    from uuid import UUID

    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 0:
        _raw_config_id = args[0]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_activation_id: object | None = None
    if "activation_id" in kwargs:
        _raw_activation_id = kwargs["activation_id"]
    elif len(args) > 1:
        _raw_activation_id = args[1]
    activation_id: UUID = TypeAdapter(UUID).validate_python(_raw_activation_id)
    _raw_event_type: object | None = None
    if "event_type" in kwargs:
        _raw_event_type = kwargs["event_type"]
    elif len(args) > 2:
        _raw_event_type = args[2]
    event_type: str = TypeAdapter(str).validate_python(_raw_event_type)
    _raw_source: object | None = None
    if "source" in kwargs:
        _raw_source = kwargs["source"]
    elif len(args) > 3:
        _raw_source = args[3]
    source: str = TypeAdapter(str).validate_python(_raw_source)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 4:
        _raw_status = args[4]
    if _raw_status is None:
        _raw_status = EventStatus.raised
    status: EventStatus = TypeAdapter(EventStatus).validate_python(_raw_status)
    result = await _impl(
        config_id=config_id, activation_id=activation_id, event_type=event_type, source=source, status=status
    )
    return result, result


async def event__add_event_condition__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event import add_event_condition as _impl
    from aware_code.types import JsonObject
    from uuid import UUID

    _raw_condition_id: object | None = None
    if "condition_id" in kwargs:
        _raw_condition_id = kwargs["condition_id"]
    elif len(args) > 0:
        _raw_condition_id = args[0]
    condition_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_id)
    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 1:
        _raw_config_id = args[1]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_matched: object | None = None
    if "matched" in kwargs:
        _raw_matched = kwargs["matched"]
    elif len(args) > 2:
        _raw_matched = args[2]
    if _raw_matched is None:
        _raw_matched = True
    matched: bool = TypeAdapter(bool).validate_python(_raw_matched)
    _raw_evaluation_context: object | None = None
    if "evaluation_context" in kwargs:
        _raw_evaluation_context = kwargs["evaluation_context"]
    elif len(args) > 3:
        _raw_evaluation_context = args[3]
    if _raw_evaluation_context is None:
        _raw_evaluation_context = JsonObject()
    evaluation_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_evaluation_context)
    result = await _impl(
        event=orm_model,
        condition_id=condition_id,
        config_id=config_id,
        matched=matched,
        evaluation_context=evaluation_context,
    )
    return result


async def event__add_action__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event import add_action as _impl
    from aware_code.types import JsonObject
    from uuid import UUID

    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 0:
        _raw_config_id = args[0]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_execution_context: object | None = None
    if "execution_context" in kwargs:
        _raw_execution_context = kwargs["execution_context"]
    elif len(args) > 1:
        _raw_execution_context = args[1]
    if _raw_execution_context is None:
        _raw_execution_context = JsonObject()
    execution_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_execution_context)
    result = await _impl(event=orm_model, config_id=config_id, execution_context=execution_context)
    return result


async def event__add_action_intent__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event import add_action_intent as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.action.action_enums import ActionIntentStatus
    from uuid import UUID

    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 0:
        _raw_config_id = args[0]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_actor_subscription_id: object | None = None
    if "actor_subscription_id" in kwargs:
        _raw_actor_subscription_id = kwargs["actor_subscription_id"]
    elif len(args) > 1:
        _raw_actor_subscription_id = args[1]
    actor_subscription_id: UUID = TypeAdapter(UUID).validate_python(_raw_actor_subscription_id)
    _raw_action_type: object | None = None
    if "action_type" in kwargs:
        _raw_action_type = kwargs["action_type"]
    elif len(args) > 2:
        _raw_action_type = args[2]
    if _raw_action_type is None:
        _raw_action_type = None
    action_type: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_action_type))
    _raw_actor_id: object | None = None
    if "actor_id" in kwargs:
        _raw_actor_id = kwargs["actor_id"]
    elif len(args) > 3:
        _raw_actor_id = args[3]
    if _raw_actor_id is None:
        _raw_actor_id = None
    actor_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_actor_id))
    _raw_target_actor_id: object | None = None
    if "target_actor_id" in kwargs:
        _raw_target_actor_id = kwargs["target_actor_id"]
    elif len(args) > 4:
        _raw_target_actor_id = args[4]
    if _raw_target_actor_id is None:
        _raw_target_actor_id = None
    target_actor_id: UUID | None = cast(UUID | None, TypeAdapter(UUID | None).validate_python(_raw_target_actor_id))
    _raw_action_payload: object | None = None
    if "action_payload" in kwargs:
        _raw_action_payload = kwargs["action_payload"]
    elif len(args) > 5:
        _raw_action_payload = args[5]
    if _raw_action_payload is None:
        _raw_action_payload = JsonObject()
    action_payload: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_action_payload)
    _raw_subscription_filter_config: object | None = None
    if "subscription_filter_config" in kwargs:
        _raw_subscription_filter_config = kwargs["subscription_filter_config"]
    elif len(args) > 6:
        _raw_subscription_filter_config = args[6]
    if _raw_subscription_filter_config is None:
        _raw_subscription_filter_config = JsonObject()
    subscription_filter_config: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_subscription_filter_config)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 7:
        _raw_priority = args[7]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_status: object | None = None
    if "status" in kwargs:
        _raw_status = kwargs["status"]
    elif len(args) > 8:
        _raw_status = args[8]
    if _raw_status is None:
        _raw_status = ActionIntentStatus.requested
    status: ActionIntentStatus = TypeAdapter(ActionIntentStatus).validate_python(_raw_status)
    result = await _impl(
        event=orm_model,
        config_id=config_id,
        actor_subscription_id=actor_subscription_id,
        action_type=action_type,
        actor_id=actor_id,
        target_actor_id=target_actor_id,
        action_payload=action_payload,
        subscription_filter_config=subscription_filter_config,
        priority=priority,
        status=status,
    )
    return result


async def event_condition__create_via_event__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_condition import create_via_event as _impl
    from aware_code.types import JsonObject
    from uuid import UUID

    _raw_event_id: object | None = None
    if "event_id" in kwargs:
        _raw_event_id = kwargs["event_id"]
    elif len(args) > 0:
        _raw_event_id = args[0]
    event_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_id)
    _raw_condition_id: object | None = None
    if "condition_id" in kwargs:
        _raw_condition_id = kwargs["condition_id"]
    elif len(args) > 1:
        _raw_condition_id = args[1]
    condition_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_id)
    _raw_config_id: object | None = None
    if "config_id" in kwargs:
        _raw_config_id = kwargs["config_id"]
    elif len(args) > 2:
        _raw_config_id = args[2]
    config_id: UUID = TypeAdapter(UUID).validate_python(_raw_config_id)
    _raw_matched: object | None = None
    if "matched" in kwargs:
        _raw_matched = kwargs["matched"]
    elif len(args) > 3:
        _raw_matched = args[3]
    if _raw_matched is None:
        _raw_matched = True
    matched: bool = TypeAdapter(bool).validate_python(_raw_matched)
    _raw_evaluation_context: object | None = None
    if "evaluation_context" in kwargs:
        _raw_evaluation_context = kwargs["evaluation_context"]
    elif len(args) > 4:
        _raw_evaluation_context = args[4]
    if _raw_evaluation_context is None:
        _raw_evaluation_context = JsonObject()
    evaluation_context: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_evaluation_context)
    result = await _impl(
        event_id=event_id,
        condition_id=condition_id,
        config_id=config_id,
        matched=matched,
        evaluation_context=evaluation_context,
    )
    return result, result


async def event_config__create__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config import create as _impl
    from aware_code.types import JsonObject
    from aware_reactivity_ontology.event.event_enums import EventDeliveryMode, EventPriority, EventType

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    description: str = TypeAdapter(str).validate_python(_raw_description)
    _raw_event_type: object | None = None
    if "event_type" in kwargs:
        _raw_event_type = kwargs["event_type"]
    elif len(args) > 2:
        _raw_event_type = args[2]
    if _raw_event_type is None:
        _raw_event_type = EventType.condition
    event_type: EventType = TypeAdapter(EventType).validate_python(_raw_event_type)
    _raw_delivery_mode: object | None = None
    if "delivery_mode" in kwargs:
        _raw_delivery_mode = kwargs["delivery_mode"]
    elif len(args) > 3:
        _raw_delivery_mode = args[3]
    if _raw_delivery_mode is None:
        _raw_delivery_mode = EventDeliveryMode.immediate
    delivery_mode: EventDeliveryMode = TypeAdapter(EventDeliveryMode).validate_python(_raw_delivery_mode)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 4:
        _raw_priority = args[4]
    if _raw_priority is None:
        _raw_priority = EventPriority.normal
    priority: EventPriority = TypeAdapter(EventPriority).validate_python(_raw_priority)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 5:
        _raw_is_enabled = args[5]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_system: object | None = None
    if "is_system" in kwargs:
        _raw_is_system = kwargs["is_system"]
    elif len(args) > 6:
        _raw_is_system = args[6]
    if _raw_is_system is None:
        _raw_is_system = False
    is_system: bool = TypeAdapter(bool).validate_python(_raw_is_system)
    _raw_require_authentication: object | None = None
    if "require_authentication" in kwargs:
        _raw_require_authentication = kwargs["require_authentication"]
    elif len(args) > 7:
        _raw_require_authentication = args[7]
    if _raw_require_authentication is None:
        _raw_require_authentication = True
    require_authentication: bool = TypeAdapter(bool).validate_python(_raw_require_authentication)
    _raw_valid_sources: object | None = None
    if "valid_sources" in kwargs:
        _raw_valid_sources = kwargs["valid_sources"]
    elif len(args) > 8:
        _raw_valid_sources = args[8]
    if _raw_valid_sources is None:
        _raw_valid_sources = []
    valid_sources: list[str] = TypeAdapter(list[str]).validate_python(_raw_valid_sources)
    _raw_allowed_roles: object | None = None
    if "allowed_roles" in kwargs:
        _raw_allowed_roles = kwargs["allowed_roles"]
    elif len(args) > 9:
        _raw_allowed_roles = args[9]
    if _raw_allowed_roles is None:
        _raw_allowed_roles = []
    allowed_roles: list[str] = TypeAdapter(list[str]).validate_python(_raw_allowed_roles)
    _raw_event_schema: object | None = None
    if "event_schema" in kwargs:
        _raw_event_schema = kwargs["event_schema"]
    elif len(args) > 10:
        _raw_event_schema = args[10]
    if _raw_event_schema is None:
        _raw_event_schema = JsonObject()
    event_schema: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_event_schema)
    _raw_batch_window_ms: object | None = None
    if "batch_window_ms" in kwargs:
        _raw_batch_window_ms = kwargs["batch_window_ms"]
    elif len(args) > 11:
        _raw_batch_window_ms = args[11]
    if _raw_batch_window_ms is None:
        _raw_batch_window_ms = None
    batch_window_ms: int | None = cast(int | None, TypeAdapter(int | None).validate_python(_raw_batch_window_ms))
    result = await _impl(
        name=name,
        description=description,
        event_type=event_type,
        delivery_mode=delivery_mode,
        priority=priority,
        is_enabled=is_enabled,
        is_system=is_system,
        require_authentication=require_authentication,
        valid_sources=valid_sources,
        allowed_roles=allowed_roles,
        event_schema=event_schema,
        batch_window_ms=batch_window_ms,
    )
    return result, result


async def event_config__add_condition_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config import add_condition_config as _impl
    from uuid import UUID

    _raw_condition_config_id: object | None = None
    if "condition_config_id" in kwargs:
        _raw_condition_config_id = kwargs["condition_config_id"]
    elif len(args) > 0:
        _raw_condition_config_id = args[0]
    condition_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_config_id)
    _raw_execution_order: object | None = None
    if "execution_order" in kwargs:
        _raw_execution_order = kwargs["execution_order"]
    elif len(args) > 1:
        _raw_execution_order = args[1]
    if _raw_execution_order is None:
        _raw_execution_order = 0
    execution_order: int = TypeAdapter(int).validate_python(_raw_execution_order)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 2:
        _raw_priority = args[2]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 3:
        _raw_is_enabled = args[3]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_required: object | None = None
    if "is_required" in kwargs:
        _raw_is_required = kwargs["is_required"]
    elif len(args) > 4:
        _raw_is_required = args[4]
    if _raw_is_required is None:
        _raw_is_required = False
    is_required: bool = TypeAdapter(bool).validate_python(_raw_is_required)
    _raw_continue_on_fail: object | None = None
    if "continue_on_fail" in kwargs:
        _raw_continue_on_fail = kwargs["continue_on_fail"]
    elif len(args) > 5:
        _raw_continue_on_fail = args[5]
    if _raw_continue_on_fail is None:
        _raw_continue_on_fail = True
    continue_on_fail: bool = TypeAdapter(bool).validate_python(_raw_continue_on_fail)
    _raw_stop_on_match: object | None = None
    if "stop_on_match" in kwargs:
        _raw_stop_on_match = kwargs["stop_on_match"]
    elif len(args) > 6:
        _raw_stop_on_match = args[6]
    if _raw_stop_on_match is None:
        _raw_stop_on_match = False
    stop_on_match: bool = TypeAdapter(bool).validate_python(_raw_stop_on_match)
    _raw_cache_result: object | None = None
    if "cache_result" in kwargs:
        _raw_cache_result = kwargs["cache_result"]
    elif len(args) > 7:
        _raw_cache_result = args[7]
    if _raw_cache_result is None:
        _raw_cache_result = False
    cache_result: bool = TypeAdapter(bool).validate_python(_raw_cache_result)
    _raw_cache_ttl_seconds: object | None = None
    if "cache_ttl_seconds" in kwargs:
        _raw_cache_ttl_seconds = kwargs["cache_ttl_seconds"]
    elif len(args) > 8:
        _raw_cache_ttl_seconds = args[8]
    if _raw_cache_ttl_seconds is None:
        _raw_cache_ttl_seconds = None
    cache_ttl_seconds: int | None = cast(int | None, TypeAdapter(int | None).validate_python(_raw_cache_ttl_seconds))
    result = await _impl(
        event_config=orm_model,
        condition_config_id=condition_config_id,
        execution_order=execution_order,
        priority=priority,
        is_enabled=is_enabled,
        is_required=is_required,
        continue_on_fail=continue_on_fail,
        stop_on_match=stop_on_match,
        cache_result=cache_result,
        cache_ttl_seconds=cache_ttl_seconds,
    )
    return result


async def event_config__add_action_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config import add_action_config as _impl
    from uuid import UUID

    _raw_action_config_id: object | None = None
    if "action_config_id" in kwargs:
        _raw_action_config_id = kwargs["action_config_id"]
    elif len(args) > 0:
        _raw_action_config_id = args[0]
    action_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_action_config_id)
    _raw_execution_order: object | None = None
    if "execution_order" in kwargs:
        _raw_execution_order = kwargs["execution_order"]
    elif len(args) > 1:
        _raw_execution_order = args[1]
    if _raw_execution_order is None:
        _raw_execution_order = 0
    execution_order: int = TypeAdapter(int).validate_python(_raw_execution_order)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 2:
        _raw_priority = args[2]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 3:
        _raw_is_enabled = args[3]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_required: object | None = None
    if "is_required" in kwargs:
        _raw_is_required = kwargs["is_required"]
    elif len(args) > 4:
        _raw_is_required = args[4]
    if _raw_is_required is None:
        _raw_is_required = False
    is_required: bool = TypeAdapter(bool).validate_python(_raw_is_required)
    _raw_continue_on_fail: object | None = None
    if "continue_on_fail" in kwargs:
        _raw_continue_on_fail = kwargs["continue_on_fail"]
    elif len(args) > 5:
        _raw_continue_on_fail = args[5]
    if _raw_continue_on_fail is None:
        _raw_continue_on_fail = True
    continue_on_fail: bool = TypeAdapter(bool).validate_python(_raw_continue_on_fail)
    result = await _impl(
        event_config=orm_model,
        action_config_id=action_config_id,
        execution_order=execution_order,
        priority=priority,
        is_enabled=is_enabled,
        is_required=is_required,
        continue_on_fail=continue_on_fail,
    )
    return result


async def event_config__update_sources__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config import update_sources as _impl
    from uuid import UUID

    _raw_p_event_config_id: object | None = None
    if "p_event_config_id" in kwargs:
        _raw_p_event_config_id = kwargs["p_event_config_id"]
    elif len(args) > 0:
        _raw_p_event_config_id = args[0]
    p_event_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_p_event_config_id)
    _raw_p_valid_sources: object | None = None
    if "p_valid_sources" in kwargs:
        _raw_p_valid_sources = kwargs["p_valid_sources"]
    elif len(args) > 1:
        _raw_p_valid_sources = args[1]
    p_valid_sources: list[str] = TypeAdapter(list[str]).validate_python(_raw_p_valid_sources)
    result = await _impl(event_config=orm_model, p_event_config_id=p_event_config_id, p_valid_sources=p_valid_sources)
    return result


async def event_config_action_config__create_via_event_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_action_config import create_via_event_config as _impl
    from uuid import UUID

    _raw_event_config_id: object | None = None
    if "event_config_id" in kwargs:
        _raw_event_config_id = kwargs["event_config_id"]
    elif len(args) > 0:
        _raw_event_config_id = args[0]
    event_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_config_id)
    _raw_action_config_id: object | None = None
    if "action_config_id" in kwargs:
        _raw_action_config_id = kwargs["action_config_id"]
    elif len(args) > 1:
        _raw_action_config_id = args[1]
    action_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_action_config_id)
    _raw_execution_order: object | None = None
    if "execution_order" in kwargs:
        _raw_execution_order = kwargs["execution_order"]
    elif len(args) > 2:
        _raw_execution_order = args[2]
    if _raw_execution_order is None:
        _raw_execution_order = 0
    execution_order: int = TypeAdapter(int).validate_python(_raw_execution_order)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 3:
        _raw_priority = args[3]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 4:
        _raw_is_enabled = args[4]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_required: object | None = None
    if "is_required" in kwargs:
        _raw_is_required = kwargs["is_required"]
    elif len(args) > 5:
        _raw_is_required = args[5]
    if _raw_is_required is None:
        _raw_is_required = False
    is_required: bool = TypeAdapter(bool).validate_python(_raw_is_required)
    _raw_continue_on_fail: object | None = None
    if "continue_on_fail" in kwargs:
        _raw_continue_on_fail = kwargs["continue_on_fail"]
    elif len(args) > 6:
        _raw_continue_on_fail = args[6]
    if _raw_continue_on_fail is None:
        _raw_continue_on_fail = True
    continue_on_fail: bool = TypeAdapter(bool).validate_python(_raw_continue_on_fail)
    result = await _impl(
        event_config_id=event_config_id,
        action_config_id=action_config_id,
        execution_order=execution_order,
        priority=priority,
        is_enabled=is_enabled,
        is_required=is_required,
        continue_on_fail=continue_on_fail,
    )
    return result, result


async def event_config_condition_config__create_scope__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_condition_config import create_scope as _impl
    from uuid import UUID

    _raw_object_instance_graph_identity_id: object | None = None
    if "object_instance_graph_identity_id" in kwargs:
        _raw_object_instance_graph_identity_id = kwargs["object_instance_graph_identity_id"]
    elif len(args) > 0:
        _raw_object_instance_graph_identity_id = args[0]
    object_instance_graph_identity_id: UUID = TypeAdapter(UUID).validate_python(_raw_object_instance_graph_identity_id)
    _raw_object_instance_graph_branch_id: object | None = None
    if "object_instance_graph_branch_id" in kwargs:
        _raw_object_instance_graph_branch_id = kwargs["object_instance_graph_branch_id"]
    elif len(args) > 1:
        _raw_object_instance_graph_branch_id = args[1]
    if _raw_object_instance_graph_branch_id is None:
        _raw_object_instance_graph_branch_id = None
    object_instance_graph_branch_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_object_instance_graph_branch_id)
    )
    result = await _impl(
        event_config_condition_config=orm_model,
        object_instance_graph_identity_id=object_instance_graph_identity_id,
        object_instance_graph_branch_id=object_instance_graph_branch_id,
    )
    return result


async def event_config_condition_config__create_via_event_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_condition_config import create_via_event_config as _impl
    from uuid import UUID

    _raw_event_config_id: object | None = None
    if "event_config_id" in kwargs:
        _raw_event_config_id = kwargs["event_config_id"]
    elif len(args) > 0:
        _raw_event_config_id = args[0]
    event_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_config_id)
    _raw_condition_config_id: object | None = None
    if "condition_config_id" in kwargs:
        _raw_condition_config_id = kwargs["condition_config_id"]
    elif len(args) > 1:
        _raw_condition_config_id = args[1]
    condition_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_condition_config_id)
    _raw_execution_order: object | None = None
    if "execution_order" in kwargs:
        _raw_execution_order = kwargs["execution_order"]
    elif len(args) > 2:
        _raw_execution_order = args[2]
    if _raw_execution_order is None:
        _raw_execution_order = 0
    execution_order: int = TypeAdapter(int).validate_python(_raw_execution_order)
    _raw_priority: object | None = None
    if "priority" in kwargs:
        _raw_priority = kwargs["priority"]
    elif len(args) > 3:
        _raw_priority = args[3]
    if _raw_priority is None:
        _raw_priority = 0
    priority: int = TypeAdapter(int).validate_python(_raw_priority)
    _raw_is_enabled: object | None = None
    if "is_enabled" in kwargs:
        _raw_is_enabled = kwargs["is_enabled"]
    elif len(args) > 4:
        _raw_is_enabled = args[4]
    if _raw_is_enabled is None:
        _raw_is_enabled = True
    is_enabled: bool = TypeAdapter(bool).validate_python(_raw_is_enabled)
    _raw_is_required: object | None = None
    if "is_required" in kwargs:
        _raw_is_required = kwargs["is_required"]
    elif len(args) > 5:
        _raw_is_required = args[5]
    if _raw_is_required is None:
        _raw_is_required = False
    is_required: bool = TypeAdapter(bool).validate_python(_raw_is_required)
    _raw_continue_on_fail: object | None = None
    if "continue_on_fail" in kwargs:
        _raw_continue_on_fail = kwargs["continue_on_fail"]
    elif len(args) > 6:
        _raw_continue_on_fail = args[6]
    if _raw_continue_on_fail is None:
        _raw_continue_on_fail = True
    continue_on_fail: bool = TypeAdapter(bool).validate_python(_raw_continue_on_fail)
    _raw_stop_on_match: object | None = None
    if "stop_on_match" in kwargs:
        _raw_stop_on_match = kwargs["stop_on_match"]
    elif len(args) > 7:
        _raw_stop_on_match = args[7]
    if _raw_stop_on_match is None:
        _raw_stop_on_match = False
    stop_on_match: bool = TypeAdapter(bool).validate_python(_raw_stop_on_match)
    _raw_cache_result: object | None = None
    if "cache_result" in kwargs:
        _raw_cache_result = kwargs["cache_result"]
    elif len(args) > 8:
        _raw_cache_result = args[8]
    if _raw_cache_result is None:
        _raw_cache_result = False
    cache_result: bool = TypeAdapter(bool).validate_python(_raw_cache_result)
    _raw_cache_ttl_seconds: object | None = None
    if "cache_ttl_seconds" in kwargs:
        _raw_cache_ttl_seconds = kwargs["cache_ttl_seconds"]
    elif len(args) > 9:
        _raw_cache_ttl_seconds = args[9]
    if _raw_cache_ttl_seconds is None:
        _raw_cache_ttl_seconds = None
    cache_ttl_seconds: int | None = cast(int | None, TypeAdapter(int | None).validate_python(_raw_cache_ttl_seconds))
    result = await _impl(
        event_config_id=event_config_id,
        condition_config_id=condition_config_id,
        execution_order=execution_order,
        priority=priority,
        is_enabled=is_enabled,
        is_required=is_required,
        continue_on_fail=continue_on_fail,
        stop_on_match=stop_on_match,
        cache_result=cache_result,
        cache_ttl_seconds=cache_ttl_seconds,
    )
    return result, result


async def event_config_condition_config_scope__add_event__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_condition_config_scope import add_event as _impl
    from uuid import UUID

    _raw_event_id: object | None = None
    if "event_id" in kwargs:
        _raw_event_id = kwargs["event_id"]
    elif len(args) > 0:
        _raw_event_id = args[0]
    event_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_id)
    result = await _impl(event_config_condition_config_scope=orm_model, event_id=event_id)
    return result


async def event_config_condition_config_scope__create_via_event_config_condition_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_condition_config_scope import (
        create_via_event_config_condition_config as _impl,
    )
    from uuid import UUID

    _raw_event_config_condition_config_id: object | None = None
    if "event_config_condition_config_id" in kwargs:
        _raw_event_config_condition_config_id = kwargs["event_config_condition_config_id"]
    elif len(args) > 0:
        _raw_event_config_condition_config_id = args[0]
    event_config_condition_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_config_condition_config_id)
    _raw_object_instance_graph_identity_id: object | None = None
    if "object_instance_graph_identity_id" in kwargs:
        _raw_object_instance_graph_identity_id = kwargs["object_instance_graph_identity_id"]
    elif len(args) > 1:
        _raw_object_instance_graph_identity_id = args[1]
    object_instance_graph_identity_id: UUID = TypeAdapter(UUID).validate_python(_raw_object_instance_graph_identity_id)
    _raw_object_instance_graph_branch_id: object | None = None
    if "object_instance_graph_branch_id" in kwargs:
        _raw_object_instance_graph_branch_id = kwargs["object_instance_graph_branch_id"]
    elif len(args) > 2:
        _raw_object_instance_graph_branch_id = args[2]
    if _raw_object_instance_graph_branch_id is None:
        _raw_object_instance_graph_branch_id = None
    object_instance_graph_branch_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_object_instance_graph_branch_id)
    )
    result = await _impl(
        event_config_condition_config_id=event_config_condition_config_id,
        object_instance_graph_identity_id=object_instance_graph_identity_id,
        object_instance_graph_branch_id=object_instance_graph_branch_id,
    )
    return result, result


async def event_config_condition_config_scope_event__create_via_event_config_condition_config_scope__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_reactivity.handlers.impl.event.event_config_condition_config_scope_event import (
        create_via_event_config_condition_config_scope as _impl,
    )
    from uuid import UUID

    _raw_event_config_condition_config_scope_id: object | None = None
    if "event_config_condition_config_scope_id" in kwargs:
        _raw_event_config_condition_config_scope_id = kwargs["event_config_condition_config_scope_id"]
    elif len(args) > 0:
        _raw_event_config_condition_config_scope_id = args[0]
    event_config_condition_config_scope_id: UUID = TypeAdapter(UUID).validate_python(
        _raw_event_config_condition_config_scope_id
    )
    _raw_event_id: object | None = None
    if "event_id" in kwargs:
        _raw_event_id = kwargs["event_id"]
    elif len(args) > 1:
        _raw_event_id = args[1]
    event_id: UUID = TypeAdapter(UUID).validate_python(_raw_event_id)
    result = await _impl(
        event_config_condition_config_scope_id=event_config_condition_config_scope_id, event_id=event_id
    )
    return result, result


AWARE_HANDLERS = [
    instance("aware_reactivity_ontology.action.action.Action", "set_status", action__set_status__handler),
    constructor(
        "aware_reactivity_ontology.action.action.Action", "create_via_event", action__create_via_event__handler
    ),
    constructor(
        "aware_reactivity_ontology.action.action_config.ActionConfig", "create", action_config__create__handler
    ),
    instance(
        "aware_reactivity_ontology.action.action_execution.ActionExecution",
        "add_feedback",
        action_execution__add_feedback__handler,
    ),
    instance(
        "aware_reactivity_ontology.action.action_execution.ActionExecution",
        "set_status",
        action_execution__set_status__handler,
    ),
    constructor(
        "aware_reactivity_ontology.action.action_execution.ActionExecution",
        "create_via_action_intent",
        action_execution__create_via_action_intent__handler,
    ),
    constructor(
        "aware_reactivity_ontology.action.action_feedback.ActionFeedback",
        "create_via_action_execution",
        action_feedback__create_via_action_execution__handler,
    ),
    instance(
        "aware_reactivity_ontology.action.action_intent.ActionIntent",
        "start_execution",
        action_intent__start_execution__handler,
    ),
    instance(
        "aware_reactivity_ontology.action.action_intent.ActionIntent", "set_status", action_intent__set_status__handler
    ),
    constructor(
        "aware_reactivity_ontology.action.action_intent.ActionIntent",
        "create_via_event",
        action_intent__create_via_event__handler,
    ),
    constructor("aware_reactivity_ontology.condition.condition.Condition", "create", condition__create__handler),
    constructor(
        "aware_reactivity_ontology.condition.condition_config.ConditionConfig",
        "create",
        condition_config__create__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config.ConditionConfig",
        "add_class_config",
        condition_config__add_class_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config_attribute_config.ConditionConfigAttributeConfig",
        "set_primitive_config",
        condition_config_attribute_config__set_primitive_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config_attribute_config.ConditionConfigAttributeConfig",
        "set_enum_config",
        condition_config_attribute_config__set_enum_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config_attribute_config.ConditionConfigAttributeConfig",
        "set_relationship_config",
        condition_config_attribute_config__set_relationship_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_attribute_config.ConditionConfigAttributeConfig",
        "create_via_condition_config_class_config",
        condition_config_attribute_config__create_via_condition_config_class_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config_class_config.ConditionConfigClassConfig",
        "add_attribute_config",
        condition_config_class_config__add_attribute_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_class_config.ConditionConfigClassConfig",
        "create_via_condition_config",
        condition_config_class_config__create_via_condition_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.condition.condition_config_enum_config.ConditionConfigEnumConfig",
        "add_enum_option",
        condition_config_enum_config__add_enum_option__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_enum_config.ConditionConfigEnumConfig",
        "create_via_condition_config_attribute_config",
        condition_config_enum_config__create_via_condition_config_attribute_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_enum_option.ConditionConfigEnumOption",
        "create_via_condition_config_enum_config",
        condition_config_enum_option__create_via_condition_config_enum_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_primitive_config.ConditionConfigPrimitiveConfig",
        "create_via_condition_config_attribute_config",
        condition_config_primitive_config__create_via_condition_config_attribute_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.condition.condition_config_relationship_config.ConditionConfigRelationshipConfig",
        "create_via_condition_config_attribute_config",
        condition_config_relationship_config__create_via_condition_config_attribute_config__handler,
    ),
    constructor("aware_reactivity_ontology.event.event.Event", "create", event__create__handler),
    instance("aware_reactivity_ontology.event.event.Event", "add_event_condition", event__add_event_condition__handler),
    instance("aware_reactivity_ontology.event.event.Event", "add_action", event__add_action__handler),
    instance("aware_reactivity_ontology.event.event.Event", "add_action_intent", event__add_action_intent__handler),
    constructor(
        "aware_reactivity_ontology.event.event_condition.EventCondition",
        "create_via_event",
        event_condition__create_via_event__handler,
    ),
    constructor("aware_reactivity_ontology.event.event_config.EventConfig", "create", event_config__create__handler),
    instance(
        "aware_reactivity_ontology.event.event_config.EventConfig",
        "add_condition_config",
        event_config__add_condition_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.event.event_config.EventConfig",
        "add_action_config",
        event_config__add_action_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.event.event_config.EventConfig",
        "update_sources",
        event_config__update_sources__handler,
    ),
    constructor(
        "aware_reactivity_ontology.event.event_config_action_config.EventConfigActionConfig",
        "create_via_event_config",
        event_config_action_config__create_via_event_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.event.event_config_condition_config.EventConfigConditionConfig",
        "create_scope",
        event_config_condition_config__create_scope__handler,
    ),
    constructor(
        "aware_reactivity_ontology.event.event_config_condition_config.EventConfigConditionConfig",
        "create_via_event_config",
        event_config_condition_config__create_via_event_config__handler,
    ),
    instance(
        "aware_reactivity_ontology.event.event_config_condition_config_scope.EventConfigConditionConfigScope",
        "add_event",
        event_config_condition_config_scope__add_event__handler,
    ),
    constructor(
        "aware_reactivity_ontology.event.event_config_condition_config_scope.EventConfigConditionConfigScope",
        "create_via_event_config_condition_config",
        event_config_condition_config_scope__create_via_event_config_condition_config__handler,
    ),
    constructor(
        "aware_reactivity_ontology.event.event_config_condition_config_scope_event.EventConfigConditionConfigScopeEvent",
        "create_via_event_config_condition_config_scope",
        event_config_condition_config_scope_event__create_via_event_config_condition_config_scope__handler,
    ),
]

__all__ = ["AWARE_HANDLERS"]
