from __future__ import annotations

from aware_meta.function.impl.deltas.ontology_execution import (
    FUNCTION_IMPL_CREATE_INSTRUCTION_REF,
    FUNCTION_IMPL_INSTRUCTION_ATTACH_SET_REF,
    FUNCTION_IMPL_INSTRUCTION_CREATE_VALUE_SOURCE_REF,
    FUNCTION_IMPL_INSTRUCTION_IDENTITY_CONTRACT,
    FUNCTION_IMPL_INSTRUCTION_IDENTITY_FIELDS,
    FUNCTION_IMPL_INSTRUCTION_SET_UPDATE_ASSIGNMENT_REF,
    FUNCTION_IMPL_REMOVE_INSTRUCTION_REF,
    FUNCTION_IMPL_VALUE_SOURCE_UPDATE_FUNCTION_INPUT_REF,
    HANDLER_KEY,
    plan_function_impl_operation,
)


__all__ = [
    "FUNCTION_IMPL_CREATE_INSTRUCTION_REF",
    "FUNCTION_IMPL_INSTRUCTION_ATTACH_SET_REF",
    "FUNCTION_IMPL_INSTRUCTION_CREATE_VALUE_SOURCE_REF",
    "FUNCTION_IMPL_INSTRUCTION_IDENTITY_CONTRACT",
    "FUNCTION_IMPL_INSTRUCTION_IDENTITY_FIELDS",
    "FUNCTION_IMPL_INSTRUCTION_SET_UPDATE_ASSIGNMENT_REF",
    "FUNCTION_IMPL_REMOVE_INSTRUCTION_REF",
    "FUNCTION_IMPL_VALUE_SOURCE_UPDATE_FUNCTION_INPUT_REF",
    "HANDLER_KEY",
    "plan_function_impl_operation",
]
