# Generated by aware_experience language contracts. Do not edit by hand.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from pydantic import BaseModel



@dataclass(frozen=True, slots=True)
class ExperienceViewModelContract:
    view_ref: str
    view_key: str
    state_model_ref: str
    version: str
    model: type[BaseModel]


VIEW_MODEL_CONTRACTS: tuple[ExperienceViewModelContract, ...] = (
)

VIEW_MODEL_DECODERS: dict[str, Callable[[Any], BaseModel]] = {
}
