# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from typing import cast
from uuid import UUID

# Third-party
from aware_meta.graph.instance.builder import build_object_instance_graph
from aware_meta.graph.instance.diff_orm import build_object_instance_graph_changes_from_orm_change_set
from aware_meta.runtime.handler_executor.argument_coercion import coerce_meta_handler_call_kwargs
from aware_meta.runtime.handler_executor.contracts import MetaGraphHandlerExecutionRequest, MetaGraphPreState
from aware_meta.runtime.handler_executor.language_handler import (
    MetaGraphGeneratedInvocationHandlerCallable,
    MetaGraphGeneratedLanguageHandlerCallable,
    MetaGraphGeneratedLanguageHandlerKey,
    MetaGraphLanguageHandlerExecution,
    MetaGraphLanguageHandlerExecutionError,
)
from aware_meta.runtime.handler_executor.pre_state import (
    MetaGraphEmptyLaneBootstrap,
    MetaGraphEmptyLaneBootstrapCallable,
)
from aware_meta.runtime.oig_model_reifier import reify_oig_root_model
from aware_meta.runtime.value_resolvers import default_meta_enum_option_resolver
from aware_meta_ontology.class_.class_config import ClassConfig
from aware_meta_ontology.graph.instance.object_instance_graph import ObjectInstanceGraph
from pydantic import BaseModel

# Code
from aware_code.types import JsonArray, JsonObject

# Orm
from aware_orm.models.orm_model import ORMModel
from aware_orm.registry import ORMModelRegistry
from aware_orm.session.change_collector import current_change_collector


def _bind_keyword_payload(
    *,
    positional: JsonArray,
    keyword: JsonObject,
    field_names: tuple[str, ...],
    function_name: str,
) -> JsonObject:
    if len(positional) > len(field_names):
        raise MetaGraphLanguageHandlerExecutionError(
            "Too many positional arguments for generated Meta language handler: "
            f"function_name={function_name} have={len(positional)} max={len(field_names)}"
        )
    payload = JsonObject(dict(keyword))
    unknown_names = sorted(set(payload) - set(field_names))
    if unknown_names:
        raise MetaGraphLanguageHandlerExecutionError(
            "Unknown generated Meta language-handler argument(s): "
            f"function_name={function_name} names={unknown_names}"
        )
    for position, value in enumerate(positional):
        field_name = field_names[position]
        if field_name in payload:
            raise MetaGraphLanguageHandlerExecutionError(
                "Generated Meta language-handler argument provided twice: "
                f"function_name={function_name} name={field_name}"
            )
        payload[field_name] = value
    return payload


def _assert_constructor_owner_class(*, request: MetaGraphHandlerExecutionRequest, expected_class_name: str) -> None:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )


def _post_oig_with_root_model(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    root_model: ORMModel,
) -> ObjectInstanceGraph:
    before_oig = pre_state.before_oig
    return build_object_instance_graph(
        root_instance=root_model,
        object_config_graph=request.execution_plan.index.ocg,
        object_projection_graph=request.execution_plan.object_projection_graph,
        key=before_oig.key or str(before_oig.id),
        name=before_oig.name or request.execution_plan.object_projection_graph.name,
        description=before_oig.description or "",
        oig_id=before_oig.id,
        enum_option_resolver=default_meta_enum_option_resolver,
    )


def _changes_from_current_collector(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
):
    collector = current_change_collector()
    if collector is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires an active ORM change collector."
        )
    change_set = collector.snapshot()
    changes = tuple(
        build_object_instance_graph_changes_from_orm_change_set(
            before_oig=pre_state.before_oig,
            object_instance_graph_identity_id=(request.staged_call.lane_scope.object_instance_graph_identity_id),
            ocg=request.execution_plan.index.ocg,
            opg=request.execution_plan.object_projection_graph,
            change_set=change_set,
            class_configs_by_id=dict(request.execution_plan.index.class_configs_by_id),
            relationships_by_id=dict(request.execution_plan.index.relationships_by_id),
            enum_option_resolver=default_meta_enum_option_resolver,
        )
    )
    constructed_class_instance_ids = tuple(
        class_change.class_instance_id
        for root_change in changes
        for class_change in root_change.class_instance_changes
        if class_change.change.type.value == "create"
    )
    return changes, constructed_class_instance_ids


def _root_and_target_models_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    expected_class_name: str,
) -> tuple[ORMModel, ORMModel]:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )
    target_object_id = (
        pre_state.target_object_id
        or request.execution_plan.target_object_id
        or request.request.target_object_id
        or pre_state.root_object_id
    )
    if target_object_id is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance handler requires a target object id.")
    root_model = _root_model_from_pre_state(request=request, pre_state=pre_state)
    target_source_object_id = _target_source_object_id_from_pre_state(
        pre_state=pre_state,
        target_class_instance_id=target_object_id,
    )
    target = _find_orm_model_by_id(root_model, target_source_object_id)
    target_orm_class = ORMModelRegistry.get_class_by_class_config_id(owner_class_config.id)
    if target_orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve ORM class: "
            f"class_config_id={owner_class_config.id} class_name={owner_class_config.name}"
        )
    if not isinstance(target, target_orm_class):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve target model in "
            "the rooted projection model: "
            f"class_name={owner_class_config.name} target_object_id={target_object_id}"
        )
    return root_model, target


def _root_model_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
) -> ORMModel:
    root_orm_class = _root_orm_class_from_projection(request)
    root_object_id = _root_source_object_id_from_pre_state(pre_state)
    root = reify_oig_root_model(
        index=request.execution_plan.index,
        opg=request.execution_plan.object_projection_graph,
        oig=pre_state.before_oig,
        model_type=root_orm_class,
        root_id=root_object_id,
        branch_id=request.execution_plan.staged_call.lane_scope.domain_branch_id,
    )
    if root is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot reify rooted projection model: " f"root_object_id={root_object_id}"
        )
    return root


def _root_orm_class_from_projection(
    request: MetaGraphHandlerExecutionRequest,
) -> type[ORMModel]:
    root_nodes = [
        node for node in request.execution_plan.object_projection_graph.object_projection_graph_nodes if node.is_root
    ]
    if len(root_nodes) != 1:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler requires exactly one OPG root node: "
            f"have={len(root_nodes)} "
            f"object_projection_graph_id={request.execution_plan.object_projection_graph.id}"
        )
    orm_class = ORMModelRegistry.get_class_by_class_config_id(root_nodes[0].class_config_id)
    if orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve root ORM class: " f"class_config_id={root_nodes[0].class_config_id}"
        )
    return cast(type[ORMModel], orm_class)


def _root_source_object_id_from_pre_state(pre_state: MetaGraphPreState):
    if pre_state.root_object_id is not None:
        return pre_state.root_object_id
    root_class_instance = pre_state.before_oig.root_class_instance
    if root_class_instance is None and pre_state.before_oig.root_class_instance_id is not None:
        root_class_instance = next(
            (
                instance
                for instance in pre_state.before_oig.class_instances
                if instance.id == pre_state.before_oig.root_class_instance_id
            ),
            None,
        )
    if root_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler cannot resolve root source object id.")
    return root_class_instance.source_object_id


def _target_source_object_id_from_pre_state(
    *,
    pre_state: MetaGraphPreState,
    target_class_instance_id,
):
    if pre_state.oig_index is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler requires pre-state OIG index.")
    target_class_instance = pre_state.oig_index.class_instances_by_id.get(target_class_instance_id)
    if target_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve target class instance: "
            f"target_class_instance_id={target_class_instance_id}"
        )
    return target_class_instance.source_object_id


def _find_orm_model_by_id(root_model: ORMModel, object_id) -> ORMModel | None:
    stack: list[object] = [root_model]
    seen: set[int] = set()
    while stack:
        current = stack.pop()
        identity = id(current)
        if identity in seen:
            continue
        seen.add(identity)
        if isinstance(current, ORMModel):
            if current.id == object_id:
                return current
            stack.extend(current.__dict__.values())
            continue
        if isinstance(current, (list, tuple, set)):
            stack.extend(current)
            continue
        if isinstance(current, dict):
            stack.extend(current.values())
    return None


def _constructed_class_instance_ids_from_post_oig(
    *,
    pre_state: MetaGraphPreState,
    post_oig: ObjectInstanceGraph,
) -> tuple:
    before_ids = {instance.id for instance in pre_state.before_oig.class_instances}
    return tuple(instance.id for instance in post_oig.class_instances if instance.id not in before_ids)


def _json_payload_value(value: object) -> object:
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    if isinstance(value, tuple):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, list):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_payload_value(item) for key, item in value.items()}
    return value


def _bind_branch__create(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("branch_id", "lane_hash", "key", "is_main", "name"),
        function_name="create",
    )


async def _call_branch__create(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.branch.branch import create as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_branch__create(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    branch_id = bound_input.get("branch_id")
    lane_hash = bound_input.get("lane_hash")
    key = bound_input.get("key")
    if key is None:
        key = "default"
    is_main = bound_input.get("is_main")
    if is_main is None:
        is_main = False
    name = bound_input.get("name")
    if name is None:
        name = None
    _aware_self_values = {"branch_id": branch_id, "lane_hash": lane_hash, "key": key, "is_main": is_main, "name": name}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("e36537cd-48ae-5626-8ae7-f11bdfd88778")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Branch.create"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Branch.create"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_branch__attach_lane(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("lane_hash",),
        function_name="attach_lane",
    )


async def _call_branch__attach_lane(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.branch.branch import attach_lane as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Branch.attach_lane"
        )
    result = await _impl(branch=target, **call_kwargs)
    return result


def _bind_branch__create_version(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("version_number", "head_commit_id"),
        function_name="create_version",
    )


async def _call_branch__create_version(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.branch.branch import create_version as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Branch.create_version"
        )
    result = await _impl(branch=target, **call_kwargs)
    return result


def _bind_change__create(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("key", "created_at", "type"),
        function_name="create",
    )


async def _call_change__create(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.change.change import create as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_change__create(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    key = bound_input.get("key")
    created_at = bound_input.get("created_at")
    type = bound_input.get("type")
    _aware_self_values = {"key": key, "created_at": created_at, "type": type}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("d97967be-b972-58f6-a5bc-4369809201e0")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Change.create"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Change.create"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_change__create_delta(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("position", "kind", "payload", "property"),
        function_name="create_delta",
    )


async def _call_change__create_delta(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.change.change import create_delta as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Change.create_delta"
        )
    result = await _impl(change=target, **call_kwargs)
    return result


def _bind_change_delta__create_via_change(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("change_id", "position", "kind", "payload", "property"),
        function_name="create_via_change",
    )


async def _call_change_delta__create_via_change(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.change.change_delta import create_via_change as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_change_delta__create_via_change(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    change_id = bound_input.get("change_id")
    position = bound_input.get("position")
    kind = bound_input.get("kind")
    payload = bound_input.get("payload")
    property = bound_input.get("property")
    if property is None:
        property = None
    _aware_self_values = {
        "change_id": change_id,
        "position": position,
        "kind": kind,
        "payload": payload,
        "property": property,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("98e38a0c-9140-514d-8359-9364124e108a")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: ChangeDelta.create_via_change"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: ChangeDelta.create_via_change"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_commit__add_parent(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("parent_id",),
        function_name="add_parent",
    )


async def _call_commit__add_parent(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.commit.commit import add_parent as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Commit.add_parent"
        )
    result = await _impl(commit=target, **call_kwargs)
    return result


def _bind_commit__create_via_lane(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("lane_id", "key", "author_id", "created_at", "status"),
        function_name="create_via_lane",
    )


async def _call_commit__create_via_lane(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.commit.commit import create_via_lane as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_commit__create_via_lane(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    lane_id = bound_input.get("lane_id")
    key = bound_input.get("key")
    author_id = bound_input.get("author_id")
    created_at = bound_input.get("created_at")
    status = bound_input.get("status")
    if status is None:
        status = "local"
    _aware_self_values = {
        "lane_id": lane_id,
        "key": key,
        "author_id": author_id,
        "created_at": created_at,
        "status": status,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("01af5be3-7da4-5303-bcb2-20f6751ca879")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Commit.create_via_lane"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Commit.create_via_lane"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_commit_parent__create_via_commit(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("commit_id", "parent_commit_id"),
        function_name="create_via_commit",
    )


async def _call_commit_parent__create_via_commit(
    *, bound_input: JsonObject, target: ORMModel | None = None
) -> ORMModel:
    from aware_history.handlers.impl.commit.commit_parent import create_via_commit as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_commit_parent__create_via_commit(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    commit_id = bound_input.get("commit_id")
    parent_commit_id = bound_input.get("parent_commit_id")
    _aware_self_values = {"commit_id": commit_id, "parent_commit_id": parent_commit_id}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("23dcf35c-8f94-5e4f-832d-a367a61aa3d4")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: CommitParent.create_via_commit"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: CommitParent.create_via_commit"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_lane__create_commit(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("key", "author_id", "created_at", "status"),
        function_name="create_commit",
    )


async def _call_lane__create_commit(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.lane.lane import create_commit as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Lane.create_commit"
        )
    result = await _impl(lane=target, **call_kwargs)
    return result


def _bind_lane__advance_head(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("commit_id",),
        function_name="advance_head",
    )


async def _call_lane__advance_head(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.lane.lane import advance_head as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Lane.advance_head"
        )
    result = await _impl(lane=target, **call_kwargs)
    return result


def _bind_lane__create_via_branch(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("branch_id", "lane_hash"),
        function_name="create_via_branch",
    )


async def _call_lane__create_via_branch(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.lane.lane import create_via_branch as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_lane__create_via_branch(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    branch_id = bound_input.get("branch_id")
    lane_hash = bound_input.get("lane_hash")
    _aware_self_values = {"branch_id": branch_id, "lane_hash": lane_hash}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("caafb6e4-eead-528b-9f14-697a9f6b4751")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Lane.create_via_branch"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Lane.create_via_branch"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_migration__create_via_version(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("version_id", "name", "description", "applied_at", "status"),
        function_name="create_via_version",
    )


async def _call_migration__create_via_version(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.migration.migration import create_via_version as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_migration__create_via_version(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    version_id = bound_input.get("version_id")
    name = bound_input.get("name")
    description = bound_input.get("description")
    if description is None:
        description = None
    applied_at = bound_input.get("applied_at")
    if applied_at is None:
        applied_at = None
    status = bound_input.get("status")
    if status is None:
        status = "pending"
    _aware_self_values = {
        "version_id": version_id,
        "name": name,
        "description": description,
        "applied_at": applied_at,
        "status": status,
    }
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("d340fc06-56e4-5aff-b43d-7a39f2caa11a")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Migration.create_via_version"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Migration.create_via_version"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_version__create_migration(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("name", "description", "applied_at", "status"),
        function_name="create_migration",
    )


async def _call_version__create_migration(*, bound_input: JsonObject, target: ORMModel | None = None) -> object:
    from aware_history.handlers.impl.version.version import create_migration as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    if target is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance invocation requires target: Version.create_migration"
        )
    result = await _impl(version=target, **call_kwargs)
    return result


def _bind_version__create_via_branch(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("branch_id", "version_number", "head_commit_id"),
        function_name="create_via_branch",
    )


async def _call_version__create_via_branch(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_history.handlers.impl.version.version import create_via_branch as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_version__create_via_branch(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_history_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    branch_id = bound_input.get("branch_id")
    version_number = bound_input.get("version_number")
    head_commit_id = bound_input.get("head_commit_id")
    if head_commit_id is None:
        head_commit_id = None
    _aware_self_values = {"branch_id": branch_id, "version_number": version_number, "head_commit_id": head_commit_id}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("763370ab-b44f-5269-8df8-231531b293d8")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: Version.create_via_branch"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: Version.create_via_branch"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_history_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


async def branch__create__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_branch__create(positional=positional, keyword=keyword)
    result = await _call_branch__create(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Branch")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def branch__create__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_branch__create(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_branch__create(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Branch",
        description="Meta constructor bootstrap for Branch.",
    )


async def branch__attach_lane__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_branch__attach_lane(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Branch",
    )
    result = await _call_branch__attach_lane(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def branch__create_version__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_branch__create_version(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Branch",
    )
    result = await _call_branch__create_version(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def change__create__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_change__create(positional=positional, keyword=keyword)
    result = await _call_change__create(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Change")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def change__create__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_change__create(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_change__create(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Change",
        description="Meta constructor bootstrap for Change.",
    )


async def change__create_delta__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_change__create_delta(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Change",
    )
    result = await _call_change__create_delta(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def change_delta__create_via_change__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_change_delta__create_via_change(positional=positional, keyword=keyword)
    result = await _call_change_delta__create_via_change(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="ChangeDelta")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def change_delta__create_via_change__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_change_delta__create_via_change(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_change_delta__create_via_change(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="ChangeDelta",
        description="Meta constructor bootstrap for ChangeDelta.",
    )


async def commit__add_parent__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_commit__add_parent(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Commit",
    )
    result = await _call_commit__add_parent(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def commit__create_via_lane__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_commit__create_via_lane(positional=positional, keyword=keyword)
    result = await _call_commit__create_via_lane(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Commit")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def commit__create_via_lane__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_commit__create_via_lane(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_commit__create_via_lane(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Commit",
        description="Meta constructor bootstrap for Commit.",
    )


async def commit_parent__create_via_commit__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_commit_parent__create_via_commit(positional=positional, keyword=keyword)
    result = await _call_commit_parent__create_via_commit(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="CommitParent")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def commit_parent__create_via_commit__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_commit_parent__create_via_commit(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_commit_parent__create_via_commit(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="CommitParent",
        description="Meta constructor bootstrap for CommitParent.",
    )


async def lane__create_commit__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_lane__create_commit(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Lane",
    )
    result = await _call_lane__create_commit(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def lane__advance_head__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_lane__advance_head(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Lane",
    )
    result = await _call_lane__advance_head(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def lane__create_via_branch__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_lane__create_via_branch(positional=positional, keyword=keyword)
    result = await _call_lane__create_via_branch(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Lane")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def lane__create_via_branch__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_lane__create_via_branch(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_lane__create_via_branch(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Lane",
        description="Meta constructor bootstrap for Lane.",
    )


async def migration__create_via_version__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_migration__create_via_version(positional=positional, keyword=keyword)
    result = await _call_migration__create_via_version(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Migration")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def migration__create_via_version__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_migration__create_via_version(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_migration__create_via_version(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Migration",
        description="Meta constructor bootstrap for Migration.",
    )


async def version__create_migration__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_version__create_migration(positional=positional, keyword=keyword)
    root_model, target = _root_and_target_models_from_pre_state(
        request=request,
        pre_state=pre_state,
        expected_class_name="Version",
    )
    result = await _call_version__create_migration(bound_input=bound_input, target=target)
    changes, constructed_class_instance_ids = _changes_from_current_collector(
        request=request,
        pre_state=pre_state,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        changes=changes,
        root_object_id=root_model.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=constructed_class_instance_ids,
    )


async def version__create_via_branch__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_version__create_via_branch(positional=positional, keyword=keyword)
    result = await _call_version__create_via_branch(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="Version")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def version__create_via_branch__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_version__create_via_branch(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_version__create_via_branch(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="Version",
        description="Meta constructor bootstrap for Version.",
    )


async def branch__create__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_branch__create(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_branch__create(bound_input=bound_input)


async def branch__attach_lane__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_branch__attach_lane(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_branch__attach_lane(bound_input=bound_input, target=target)


async def branch__create_version__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_branch__create_version(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_branch__create_version(bound_input=bound_input, target=target)


async def change__create__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_change__create(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_change__create(bound_input=bound_input)


async def change__create_delta__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_change__create_delta(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_change__create_delta(bound_input=bound_input, target=target)


async def change_delta__create_via_change__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_change_delta__create_via_change(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_change_delta__create_via_change(bound_input=bound_input)


async def commit__add_parent__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_commit__add_parent(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_commit__add_parent(bound_input=bound_input, target=target)


async def commit__create_via_lane__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_commit__create_via_lane(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_commit__create_via_lane(bound_input=bound_input)


async def commit_parent__create_via_commit__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_commit_parent__create_via_commit(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_commit_parent__create_via_commit(bound_input=bound_input)


async def lane__create_commit__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_lane__create_commit(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_lane__create_commit(bound_input=bound_input, target=target)


async def lane__advance_head__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_lane__advance_head(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_lane__advance_head(bound_input=bound_input, target=target)


async def lane__create_via_branch__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_lane__create_via_branch(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_lane__create_via_branch(bound_input=bound_input)


async def migration__create_via_version__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_migration__create_via_version(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_migration__create_via_version(bound_input=bound_input)


async def version__create_migration__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_version__create_migration(positional=positional, keyword=keyword)
    if not isinstance(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance invocation requires ORMModel target.")
    return await _call_version__create_migration(bound_input=bound_input, target=target)


async def version__create_via_branch__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_version__create_via_branch(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_version__create_via_branch(bound_input=bound_input)


AWARE_META_GRAPH_HANDLERS: dict[MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedLanguageHandlerCallable] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__create__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="attach_lane",
        is_constructor=False,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__attach_lane__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="create_version",
        is_constructor=False,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__create_version__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.Change",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.change.Change",
        owner_class_name="Change",
    ): change__create__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.Change",
        function_name="create_delta",
        is_constructor=False,
        owner_class_fqn="aware_history.change.Change",
        owner_class_name="Change",
    ): change__create_delta__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.ChangeDelta",
        function_name="create_via_change",
        is_constructor=True,
        owner_class_fqn="aware_history.change.ChangeDelta",
        owner_class_name="ChangeDelta",
    ): change_delta__create_via_change__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.Commit",
        function_name="add_parent",
        is_constructor=False,
        owner_class_fqn="aware_history.commit.Commit",
        owner_class_name="Commit",
    ): commit__add_parent__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.Commit",
        function_name="create_via_lane",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.Commit",
        owner_class_name="Commit",
    ): commit__create_via_lane__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.CommitParent",
        function_name="create_via_commit",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.CommitParent",
        owner_class_name="CommitParent",
    ): commit_parent__create_via_commit__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="create_commit",
        is_constructor=False,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__create_commit__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="advance_head",
        is_constructor=False,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__advance_head__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__create_via_branch__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.migration.Migration",
        function_name="create_via_version",
        is_constructor=True,
        owner_class_fqn="aware_history.migration.Migration",
        owner_class_name="Migration",
    ): migration__create_via_version__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.version.Version",
        function_name="create_migration",
        is_constructor=False,
        owner_class_fqn="aware_history.version.Version",
        owner_class_name="Version",
    ): version__create_migration__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.version.Version",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.version.Version",
        owner_class_name="Version",
    ): version__create_via_branch__handler,
}

AWARE_META_GRAPH_INVOCATION_HANDLERS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedInvocationHandlerCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__create__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="attach_lane",
        is_constructor=False,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__attach_lane__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="create_version",
        is_constructor=False,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__create_version__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.Change",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.change.Change",
        owner_class_name="Change",
    ): change__create__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.Change",
        function_name="create_delta",
        is_constructor=False,
        owner_class_fqn="aware_history.change.Change",
        owner_class_name="Change",
    ): change__create_delta__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.ChangeDelta",
        function_name="create_via_change",
        is_constructor=True,
        owner_class_fqn="aware_history.change.ChangeDelta",
        owner_class_name="ChangeDelta",
    ): change_delta__create_via_change__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.Commit",
        function_name="add_parent",
        is_constructor=False,
        owner_class_fqn="aware_history.commit.Commit",
        owner_class_name="Commit",
    ): commit__add_parent__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.Commit",
        function_name="create_via_lane",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.Commit",
        owner_class_name="Commit",
    ): commit__create_via_lane__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.CommitParent",
        function_name="create_via_commit",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.CommitParent",
        owner_class_name="CommitParent",
    ): commit_parent__create_via_commit__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="create_commit",
        is_constructor=False,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__create_commit__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="advance_head",
        is_constructor=False,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__advance_head__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__create_via_branch__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.migration.Migration",
        function_name="create_via_version",
        is_constructor=True,
        owner_class_fqn="aware_history.migration.Migration",
        owner_class_name="Migration",
    ): migration__create_via_version__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.version.Version",
        function_name="create_migration",
        is_constructor=False,
        owner_class_fqn="aware_history.version.Version",
        owner_class_name="Version",
    ): version__create_migration__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.version.Version",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.version.Version",
        owner_class_name="Version",
    ): version__create_via_branch__invocation_handler,
}

AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphEmptyLaneBootstrapCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.branch.Branch",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.branch.Branch",
        owner_class_name="Branch",
    ): branch__create__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.Change",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_history.change.Change",
        owner_class_name="Change",
    ): change__create__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.change.ChangeDelta",
        function_name="create_via_change",
        is_constructor=True,
        owner_class_fqn="aware_history.change.ChangeDelta",
        owner_class_name="ChangeDelta",
    ): change_delta__create_via_change__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.Commit",
        function_name="create_via_lane",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.Commit",
        owner_class_name="Commit",
    ): commit__create_via_lane__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.commit.CommitParent",
        function_name="create_via_commit",
        is_constructor=True,
        owner_class_fqn="aware_history.commit.CommitParent",
        owner_class_name="CommitParent",
    ): commit_parent__create_via_commit__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.lane.Lane",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.lane.Lane",
        owner_class_name="Lane",
    ): lane__create_via_branch__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.migration.Migration",
        function_name="create_via_version",
        is_constructor=True,
        owner_class_fqn="aware_history.migration.Migration",
        owner_class_name="Migration",
    ): migration__create_via_version__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_history.version.Version",
        function_name="create_via_branch",
        is_constructor=True,
        owner_class_fqn="aware_history.version.Version",
        owner_class_name="Version",
    ): version__create_via_branch__empty_lane_bootstrap,
}

__all__ = [
    "AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS",
    "AWARE_META_GRAPH_HANDLERS",
    "AWARE_META_GRAPH_INVOCATION_HANDLERS",
]
