from __future__ import annotations

from aware_api_ontology.api.api import Api
from aware_api_ontology.api.api_capability import ApiCapability
from aware_meta.materialization.function_refs import meta_ontology_function_ref


API_CREATE_FUNCTION = meta_ontology_function_ref(Api.create)
API_CREATE_CAPABILITY_FUNCTION = meta_ontology_function_ref(Api.create_capability)
API_CAPABILITY_CREATE_ENDPOINT_FUNCTION = meta_ontology_function_ref(
    ApiCapability.create_endpoint
)

API_CREATE_FUNCTION_REF = API_CREATE_FUNCTION.ref
API_CREATE_CAPABILITY_FUNCTION_REF = API_CREATE_CAPABILITY_FUNCTION.ref
API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_REF = (
    API_CAPABILITY_CREATE_ENDPOINT_FUNCTION.ref
)

API_SEMANTIC_OPERATION_FUNCTION_CALL_RESOLUTION_CAPABILITY = (
    "semantic_operation_function_call_resolution"
)
API_SEMANTIC_OPERATION_FUNCTION_CALL_RESOLUTION_CONTRACT_VERSION = (
    "aware.api.semantic-operation-function-call-resolution.v0"
)
API_CREATE_OPERATION = "aware_api.api.create"
API_CAPABILITY_CREATE_OPERATION = "aware_api.api_capability.create"
API_CAPABILITY_ENDPOINT_CREATE_OPERATION = "aware_api.api_capability_endpoint.create"
API_SEMANTIC_OPERATION_TYPES = (
    API_CREATE_OPERATION,
    API_CAPABILITY_CREATE_OPERATION,
    API_CAPABILITY_ENDPOINT_CREATE_OPERATION,
)
API_CREATE_FUNCTION_CALL_BINDING_REF = "aware_api.api.upserted.api_create"
API_CREATE_CAPABILITY_FUNCTION_CALL_BINDING_REF = (
    "aware_api.api_capability.upserted.api_create_capability"
)
API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_CALL_BINDING_REF = (
    "aware_api.api_capability_endpoint.upserted.api_capability_create_endpoint"
)
API_SEMANTIC_FUNCTION_CALL_BINDING_REFS = (
    API_CREATE_FUNCTION_CALL_BINDING_REF,
    API_CREATE_CAPABILITY_FUNCTION_CALL_BINDING_REF,
    API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_CALL_BINDING_REF,
)
API_SEMANTIC_FUNCTION_REFS = frozenset(
    {
        API_CREATE_FUNCTION_REF,
        API_CREATE_CAPABILITY_FUNCTION_REF,
        API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_REF,
    }
)


__all__ = [
    "API_CAPABILITY_CREATE_ENDPOINT_FUNCTION",
    "API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_CALL_BINDING_REF",
    "API_CAPABILITY_CREATE_ENDPOINT_FUNCTION_REF",
    "API_CAPABILITY_ENDPOINT_CREATE_OPERATION",
    "API_CAPABILITY_CREATE_OPERATION",
    "API_CREATE_CAPABILITY_FUNCTION",
    "API_CREATE_CAPABILITY_FUNCTION_CALL_BINDING_REF",
    "API_CREATE_CAPABILITY_FUNCTION_REF",
    "API_CREATE_FUNCTION",
    "API_CREATE_FUNCTION_CALL_BINDING_REF",
    "API_CREATE_FUNCTION_REF",
    "API_CREATE_OPERATION",
    "API_SEMANTIC_FUNCTION_CALL_BINDING_REFS",
    "API_SEMANTIC_FUNCTION_REFS",
    "API_SEMANTIC_OPERATION_FUNCTION_CALL_RESOLUTION_CAPABILITY",
    "API_SEMANTIC_OPERATION_FUNCTION_CALL_RESOLUTION_CONTRACT_VERSION",
    "API_SEMANTIC_OPERATION_TYPES",
]
