from __future__ import annotations


META_PROVIDER_DELTA_TYPED_OPERATION_PLAN_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-typed-operation-plan.v1"
)
META_PROVIDER_DELTA_SEMANTIC_DIRTY_DIFF_CONTRACT_VERSION = (
    "aware.meta.ocg.semantic-dirty-diff.v1"
)
META_PROVIDER_DELTA_DIRTY_ENTRY_CONTRACT_VERSION = (
    "aware.meta.ocg.semantic-dirty-entry.v1"
)
META_PROVIDER_DELTA_TYPED_OPERATION_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-typed-operation.v1"
)
META_PROVIDER_DELTA_MUTATION_PLAN_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-mutation-plan.v1"
)
META_PROVIDER_DELTA_MUTATION_STEP_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-mutation-step.v1"
)
META_PROVIDER_DELTA_ONTOLOGY_EXECUTION_PLAN_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-ontology-execution-plan.v1"
)
META_PROVIDER_DELTA_FUNCTIONCALL_CAPABILITY_MATRIX_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-functioncall-capability-matrix.v1"
)
META_PROVIDER_DELTA_OIG_COMMIT_RECEIPT_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-execute-flag-commit-receipt.v1"
)
META_PROVIDER_DELTA_HEAD_MOVE_APPLIED_RECEIPT_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-head-move-applied-receipt.v1"
)
META_PROVIDER_DELTA_RUNTIME_PACKAGE_INDEX_PATCH_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-runtime-package-index-patch.v1"
)
META_PROVIDER_DELTA_OUTPUT_MATERIALIZATION_RECEIPT_CONTRACT_VERSION = (
    "aware.meta.provider-delta.output-materialization.v1"
)
META_PROVIDER_DELTA_SEMANTIC_COMMIT_EVIDENCE_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-semantic-commit-evidence.v1"
)
META_PROVIDER_DELTA_COMMITTED_SEMANTIC_CHANGE_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-committed-semantic-change.v1"
)
META_PROVIDER_DELTA_SEMANTIC_CHANGE_REPORT_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-semantic-change-report.v1"
)
META_PROVIDER_DELTA_SEMANTIC_WORLD_CHANGE_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-semantic-world-change.v1"
)
META_PROVIDER_DELTA_READABLE_SEMANTIC_CHANGE_CHAIN_CONTRACT_VERSION = (
    "aware.meta.ocg.provider-delta-readable-semantic-change-chain.v1"
)
META_PROVIDER_DELTA_RESULT_CONTRACT_VERSION = (
    "aware.workspace.semantic-materialization.provider-delta-result.v1"
)
META_PROVIDER_DELTA_COMMIT_REF_CONTRACT_VERSION = (
    "aware.workspace.semantic-materialization.provider-delta-commit-ref.v1"
)


__all__ = [
    "META_PROVIDER_DELTA_COMMITTED_SEMANTIC_CHANGE_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_COMMIT_REF_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_DIRTY_ENTRY_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_FUNCTIONCALL_CAPABILITY_MATRIX_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_HEAD_MOVE_APPLIED_RECEIPT_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_MUTATION_PLAN_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_MUTATION_STEP_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_OIG_COMMIT_RECEIPT_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_ONTOLOGY_EXECUTION_PLAN_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_OUTPUT_MATERIALIZATION_RECEIPT_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_READABLE_SEMANTIC_CHANGE_CHAIN_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_RESULT_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_RUNTIME_PACKAGE_INDEX_PATCH_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_SEMANTIC_DIRTY_DIFF_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_SEMANTIC_CHANGE_REPORT_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_SEMANTIC_COMMIT_EVIDENCE_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_SEMANTIC_WORLD_CHANGE_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_TYPED_OPERATION_CONTRACT_VERSION",
    "META_PROVIDER_DELTA_TYPED_OPERATION_PLAN_CONTRACT_VERSION",
]
