from importlib import import_module

# Canonical neutral operations and retained filesystem compatibility surfaces.
# Service/view facades live in the sibling internal Service adapter, not here.
_EXPORT_MODULES = {
    "IssueDraftInputResourceObservation": "aware_issue_sdk.draft_input_custody",
    "IssueDraftInputCustodyObservation": "aware_issue_sdk.draft_input_custody",
    "IssueDraftInputBinding": "aware_issue_sdk.draft_input_custody",
    "IssueDraftInputCustodyRefusal": "aware_issue_sdk.draft_input_custody",
    "ISSUE_DRAFT_PACKAGE_INTENT": "aware_issue_sdk.draft_package",
    "ISSUE_DRAFT_PACKAGE_MODE_PROFILE": "aware_issue_sdk.draft_package",
    "IssueDraftPackageRequest": "aware_issue_sdk.draft_package",
    "ISSUE_DRAFT_PACKAGE_OPERATION_REF": "aware_issue_sdk.draft_package",
    "IssueDraftPackageEffect": "aware_issue_sdk.draft_package",
    "IssueDraftPackageBinding": "aware_issue_sdk.draft_package",
    "IssueDraftPackageCleanupDisposition": "aware_issue_sdk.draft_package",
    "IssueDraftPackageEvidence": "aware_issue_sdk.draft_package",
    "IssueDraftPackageReceipt": "aware_issue_sdk.draft_package",
    "IssueDraftPackageRefusal": "aware_issue_sdk.draft_package",
    "IssueDraftPackageAdmission": "aware_issue_sdk.draft_package",
    "IssueDraftPackageProvider": "aware_issue_sdk.draft_package",
    "ISSUE_SOURCE_CHANGE_OPERATION_REF": "aware_issue_sdk.source_change",
    "IssueSourceChangeRequest": "aware_issue_sdk.source_change",
    "IssueSourceChangeEffect": "aware_issue_sdk.source_change",
    "IssueSourceChangeReceipt": "aware_issue_sdk.source_change",
    "IssueSourceChangeRefusal": "aware_issue_sdk.source_change",
    "IssueSourceChangeAdmission": "aware_issue_sdk.source_change",
    "IssueSourceChangeProvider": "aware_issue_sdk.source_change",
    "IssueSourceChangeClient": "aware_issue_sdk.source_change",
    "CommittedSpecificationMember": "aware_issue_sdk.specification_iteration",
    "IssueSpecificationIterationBindingError": "aware_issue_sdk.specification_iteration",
    "IssueSpecificationIterationBindingObserveRequest": "aware_issue_sdk.specification_iteration",
    "IssueSpecificationIterationBindingObservation": "aware_issue_sdk.specification_iteration",
    "SpecificationIterationBindingOutcome": "aware_issue_sdk.specification_iteration",
    # Provider-neutral canonical operations.
    "IssueProviderReport": "aware_issue_sdk.operation",
    "IssueOperationFailure": "aware_issue_sdk.operation",
    "IssueProviderResultError": "aware_issue_sdk.operation",
    "IssueReadProjectionResolveError": "aware_issue_sdk.operation",
    "IssueMutationError": "aware_issue_sdk.operation",
    "IssueCommitWorkspaceError": "aware_issue_sdk.operation",
    "ISSUE_APPEND_EVIDENCE_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_APPEND_EVIDENCE_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_APPEND_UPDATE_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_APPEND_UPDATE_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_BIND_SCOPE_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_BIND_SCOPE_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_BLOCK_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_BLOCK_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_CLOSE_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_CLOSE_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_COMMIT_WORKSPACE_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_COMMIT_WORKSPACE_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_COMMIT_WORKSPACE_RESULT_CONTRACT": "aware_issue_sdk.operation",
    "ISSUE_ENSURE_SNAPSHOT_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_ENSURE_SNAPSHOT_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_MUTATION_RESULT_CONTRACT": "aware_issue_sdk.operation",
    "ISSUE_READ_PROJECTION_RESOLVE_REQUEST_CONTRACT": "aware_issue_sdk.operation",
    "ISSUE_READ_PROJECTION_RESOLVE_RESULT_CONTRACT": "aware_issue_sdk.operation",
    "ISSUE_RESOLVE_READ_PROJECTION_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_RESOLVE_READ_PROJECTION_PROVIDER_OPERATION_REF": (
        "aware_issue_sdk.operation"
    ),
    "ISSUE_RESUME_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_RESUME_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_SET_OWNER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_SET_OWNER_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_START_PROGRESS_OPERATION_REF": "aware_issue_sdk.operation",
    "ISSUE_START_PROGRESS_PROVIDER_OPERATION_REF": "aware_issue_sdk.operation",
    "IssueAppendEvidenceRequest": "aware_issue_sdk.operation",
    "IssueAppendUpdateRequest": "aware_issue_sdk.operation",
    "IssueBindScopePathsRequest": "aware_issue_sdk.operation",
    "IssueBlockRequest": "aware_issue_sdk.operation",
    "IssueCloseRequest": "aware_issue_sdk.operation",
    "IssueCommitWorkspaceRequest": "aware_issue_sdk.operation",
    "IssueCommitWorkspaceResult": "aware_issue_sdk.operation",
    "IssueEnsureSnapshotRequest": "aware_issue_sdk.operation",
    "IssueMutationOutcome": "aware_issue_sdk.operation",
    "IssueMutationRequest": "aware_issue_sdk.operation",
    "IssueMutationResult": "aware_issue_sdk.operation",
    "IssueOperationContractError": "aware_issue_sdk.operation",
    "IssueOperationProvider": "aware_issue_sdk.operation",
    "IssuePublicationOutcome": "aware_issue_sdk.operation",
    "IssueReadProjectionResolveOutcome": "aware_issue_sdk.operation",
    "IssueReadProjectionResolveProvider": "aware_issue_sdk.operation",
    "IssueReadProjectionResolveRequest": "aware_issue_sdk.operation",
    "IssueReadProjectionResolveResult": "aware_issue_sdk.operation",
    "IssueResumeRequest": "aware_issue_sdk.operation",
    "IssueSetOwnerRequest": "aware_issue_sdk.operation",
    "IssueSdkOperationClient": "aware_issue_sdk.operation",
    "IssueStartProgressRequest": "aware_issue_sdk.operation",
    # Issue-owned Development read projection.
    "ISSUE_DEVELOPMENT_READ_PROJECTION_V2_SCHEMA": (
        "aware_issue_sdk.development_read_projection"
    ),
    "ClassifiedValueV1": "aware_issue_sdk.development_read_projection",
    "IssueDevelopmentActivityV2": "aware_issue_sdk.development_read_projection",
    "IssueDevelopmentAdditionalSectionV2": (
        "aware_issue_sdk.development_read_projection"
    ),
    "IssueDevelopmentAttentionCandidateV2": (
        "aware_issue_sdk.development_read_projection"
    ),
    "IssueDevelopmentIdentityV2": "aware_issue_sdk.development_read_projection",
    "IssueDevelopmentLatestActivityV2": ("aware_issue_sdk.development_read_projection"),
    "IssueDevelopmentListItemV2": "aware_issue_sdk.development_read_projection",
    "IssueDevelopmentReadProjectionV2": ("aware_issue_sdk.development_read_projection"),
    "IssueDevelopmentReferenceV2": "aware_issue_sdk.development_read_projection",
    "IssueDevelopmentSourceV2": "aware_issue_sdk.development_read_projection",
    "build_issue_development_read_projection_v2": (
        "aware_issue_sdk.development_read_projection"
    ),
    "issue_development_read_projection_v2_from_runtime": (
        "aware_issue_sdk.development_read_projection"
    ),
    "normalize_issue_activity_kind_v1": ("aware_issue_sdk.development_read_projection"),
    "normalize_issue_lifecycle_v1": ("aware_issue_sdk.development_read_projection"),
    # Local Markdown/filesystem surface.
    "FeedLocalAppendReceipt": "aware_issue_sdk.local_files",
    "FeedLocalFileSdk": "aware_issue_sdk.local_files",
    "IssueDocument": "aware_issue_sdk.local_files",
    "IssueHeaderLine": "aware_issue_sdk.local_files",
    "IssueLifecycleSnapshot": "aware_issue_sdk.local_files",
    "IssueSection": "aware_issue_sdk.local_files",
    "append_day_index_update": "aware_issue_sdk.local_files",
    "append_feed_line": "aware_issue_sdk.local_files",
    "append_update_line": "aware_issue_sdk.local_files",
    "build_issue_document": "aware_issue_sdk.local_files",
    "default_summary": "aware_issue_sdk.local_files",
    "get_header_value": "aware_issue_sdk.local_files",
    "get_section": "aware_issue_sdk.local_files",
    "now_utc_timestamp": "aware_issue_sdk.local_files",
    "parse_issue_document": "aware_issue_sdk.local_files",
    "parse_issue_document_text": "aware_issue_sdk.local_files",
    "render_issue_document": "aware_issue_sdk.local_files",
    "set_header_value": "aware_issue_sdk.local_files",
    "set_ownership_scope": "aware_issue_sdk.local_files",
    "set_resolution": "aware_issue_sdk.local_files",
    "set_verified_by": "aware_issue_sdk.local_files",
    "snapshot_issue_document": "aware_issue_sdk.local_files",
    "status_display_to_day_index": "aware_issue_sdk.local_files",
    "status_display_to_token": "aware_issue_sdk.local_files",
    "status_token_to_display": "aware_issue_sdk.local_files",
    "upsert_day_index_entry": "aware_issue_sdk.local_files",
    "write_issue_document": "aware_issue_sdk.local_files",
    "wrap_backticks": "aware_issue_sdk.local_files",
    # Local state surface (the commit rail's hot path).
    "IssueDocSnapshot": "aware_issue_sdk.local_state",
    "WorkflowIssueBootstrapResult": "aware_issue_sdk.local_state",
    "WorkflowIssueEvidenceRef": "aware_issue_sdk.local_state",
    "WorkflowIssueScopePath": "aware_issue_sdk.local_state",
    "WorkflowIssueStateEntry": "aware_issue_sdk.local_state",
    "WorkflowIssueStateStore": "aware_issue_sdk.local_state",
    "WorkflowIssueUpdateEntry": "aware_issue_sdk.local_state",
    "bootstrap_issue_state_from_doc": "aware_issue_sdk.local_state",
    "default_owner_execution_id": "aware_issue_sdk.local_state",
    "find_issue_entry_by_tag": "aware_issue_sdk.local_state",
    "load_workflow_issue_state_store": "aware_issue_sdk.local_state",
    "normalize_owner_session_id": "aware_issue_sdk.local_state",
    "normalize_owner_session_token": "aware_issue_sdk.local_state",
    "parse_issue_doc_snapshot": "aware_issue_sdk.local_state",
    "resolve_repo_relative_path": "aware_issue_sdk.local_state",
    "resolve_workflow_issue_state_path": "aware_issue_sdk.local_state",
    "save_workflow_issue_state_store": "aware_issue_sdk.local_state",
    "stable_issue_id": "aware_issue_sdk.local_state",
    "sync_issue_state_from_doc": "aware_issue_sdk.local_state",
}

__all__ = [
    "ISSUE_APPEND_EVIDENCE_OPERATION_REF",
    "ISSUE_APPEND_EVIDENCE_PROVIDER_OPERATION_REF",
    "ISSUE_APPEND_UPDATE_OPERATION_REF",
    "ISSUE_APPEND_UPDATE_PROVIDER_OPERATION_REF",
    "ISSUE_BIND_SCOPE_OPERATION_REF",
    "ISSUE_BIND_SCOPE_PROVIDER_OPERATION_REF",
    "ISSUE_BLOCK_OPERATION_REF",
    "ISSUE_BLOCK_PROVIDER_OPERATION_REF",
    "ISSUE_CLOSE_OPERATION_REF",
    "ISSUE_CLOSE_PROVIDER_OPERATION_REF",
    "ISSUE_COMMIT_WORKSPACE_OPERATION_REF",
    "ISSUE_COMMIT_WORKSPACE_PROVIDER_OPERATION_REF",
    "ISSUE_COMMIT_WORKSPACE_RESULT_CONTRACT",
    "ISSUE_DEVELOPMENT_READ_PROJECTION_V2_SCHEMA",
    "ISSUE_DRAFT_PACKAGE_INTENT",
    "ISSUE_DRAFT_PACKAGE_MODE_PROFILE",
    "ISSUE_DRAFT_PACKAGE_OPERATION_REF",
    "ISSUE_ENSURE_SNAPSHOT_OPERATION_REF",
    "ISSUE_ENSURE_SNAPSHOT_PROVIDER_OPERATION_REF",
    "ISSUE_MUTATION_RESULT_CONTRACT",
    "ISSUE_READ_PROJECTION_RESOLVE_REQUEST_CONTRACT",
    "ISSUE_READ_PROJECTION_RESOLVE_RESULT_CONTRACT",
    "ISSUE_RESOLVE_READ_PROJECTION_OPERATION_REF",
    "ISSUE_RESOLVE_READ_PROJECTION_PROVIDER_OPERATION_REF",
    "ISSUE_RESUME_OPERATION_REF",
    "ISSUE_RESUME_PROVIDER_OPERATION_REF",
    "ISSUE_SET_OWNER_OPERATION_REF",
    "ISSUE_SET_OWNER_PROVIDER_OPERATION_REF",
    "ISSUE_SOURCE_CHANGE_OPERATION_REF",
    "ISSUE_START_PROGRESS_OPERATION_REF",
    "ISSUE_START_PROGRESS_PROVIDER_OPERATION_REF",
    "ClassifiedValueV1",
    "CommittedSpecificationMember",
    "FeedLocalAppendReceipt",
    "FeedLocalFileSdk",
    "IssueAppendEvidenceRequest",
    "IssueAppendUpdateRequest",
    "IssueBindScopePathsRequest",
    "IssueBlockRequest",
    "IssueCloseRequest",
    "IssueCommitWorkspaceError",
    "IssueCommitWorkspaceRequest",
    "IssueCommitWorkspaceResult",
    "IssueDevelopmentActivityV2",
    "IssueDevelopmentAdditionalSectionV2",
    "IssueDevelopmentAttentionCandidateV2",
    "IssueDevelopmentIdentityV2",
    "IssueDevelopmentLatestActivityV2",
    "IssueDevelopmentListItemV2",
    "IssueDevelopmentReadProjectionV2",
    "IssueDevelopmentReferenceV2",
    "IssueDevelopmentSourceV2",
    "IssueDocSnapshot",
    "IssueDocument",
    "IssueDraftInputBinding",
    "IssueDraftInputCustodyObservation",
    "IssueDraftInputCustodyRefusal",
    "IssueDraftInputResourceObservation",
    "IssueDraftPackageAdmission",
    "IssueDraftPackageBinding",
    "IssueDraftPackageCleanupDisposition",
    "IssueDraftPackageEffect",
    "IssueDraftPackageEvidence",
    "IssueDraftPackageProvider",
    "IssueDraftPackageReceipt",
    "IssueDraftPackageRefusal",
    "IssueDraftPackageRequest",
    "IssueEnsureSnapshotRequest",
    "IssueHeaderLine",
    "IssueLifecycleSnapshot",
    "IssueMutationError",
    "IssueMutationOutcome",
    "IssueMutationRequest",
    "IssueMutationResult",
    "IssueOperationContractError",
    "IssueOperationFailure",
    "IssueOperationProvider",
    "IssueProviderReport",
    "IssueProviderResultError",
    "IssuePublicationOutcome",
    "IssueReadProjectionResolveError",
    "IssueReadProjectionResolveOutcome",
    "IssueReadProjectionResolveProvider",
    "IssueReadProjectionResolveRequest",
    "IssueReadProjectionResolveResult",
    "IssueResumeRequest",
    "IssueSdkOperationClient",
    "IssueSection",
    "IssueSetOwnerRequest",
    "IssueSourceChangeAdmission",
    "IssueSourceChangeClient",
    "IssueSourceChangeEffect",
    "IssueSourceChangeProvider",
    "IssueSourceChangeReceipt",
    "IssueSourceChangeRefusal",
    "IssueSourceChangeRequest",
    "IssueSpecificationIterationBindingError",
    "IssueSpecificationIterationBindingObservation",
    "IssueSpecificationIterationBindingObserveRequest",
    "IssueStartProgressRequest",
    "SpecificationIterationBindingOutcome",
    "WorkflowIssueBootstrapResult",
    "WorkflowIssueEvidenceRef",
    "WorkflowIssueScopePath",
    "WorkflowIssueStateEntry",
    "WorkflowIssueStateStore",
    "WorkflowIssueUpdateEntry",
    "append_day_index_update",
    "append_feed_line",
    "append_update_line",
    "bootstrap_issue_state_from_doc",
    "build_issue_development_read_projection_v2",
    "build_issue_document",
    "default_owner_execution_id",
    "default_summary",
    "find_issue_entry_by_tag",
    "get_header_value",
    "get_section",
    "issue_development_read_projection_v2_from_runtime",
    "load_workflow_issue_state_store",
    "normalize_issue_activity_kind_v1",
    "normalize_issue_lifecycle_v1",
    "normalize_owner_session_id",
    "normalize_owner_session_token",
    "now_utc_timestamp",
    "parse_issue_doc_snapshot",
    "parse_issue_document",
    "parse_issue_document_text",
    "render_issue_document",
    "resolve_repo_relative_path",
    "resolve_workflow_issue_state_path",
    "save_workflow_issue_state_store",
    "set_header_value",
    "set_ownership_scope",
    "set_resolution",
    "set_verified_by",
    "snapshot_issue_document",
    "stable_issue_id",
    "status_display_to_day_index",
    "status_display_to_token",
    "status_token_to_display",
    "sync_issue_state_from_doc",
    "upsert_day_index_entry",
    "wrap_backticks",
    "write_issue_document",
]


def __getattr__(name: str):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is not None:
        module = import_module(module_name)
        value = getattr(module, name)
        globals()[name] = value
        return value

    raise AttributeError(f"module 'aware_issue_sdk' has no attribute {name!r}")
