from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_meta.semantic_contract import (
    AWARE_META_SEMANTIC_CONTRACT,
    META_ANNOTATION_OWNER,
    META_CAPABILITY_BUNDLES,
    META_CAPABILITY_PARTICIPATION,
    META_CAPABILITY_PROFILES,
    META_DEFAULTS_OWNER,
    META_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    META_DIAGNOSTICS_CAPABILITY_PROFILES,
    META_IDENTITY_OWNER,
    META_OBJECT_CONFIG_GRAPH_OWNER,
    META_PROJECTION_OWNER,
    META_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION,
    META_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    META_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
    META_TYPE_MIRROR_OWNER,
)
from aware_code.semantic_capability import SEMANTIC_ANALYSIS_CAPABILITY

META_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_META_SEMANTIC_CONTRACT
)

META_SEMANTIC_ANALYSIS_CAPABILITY_METADATA = tuple(
    item
    for item in META_CAPABILITY_METADATA
    if item.capability == SEMANTIC_ANALYSIS_CAPABILITY
)

META_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in META_CAPABILITY_METADATA if item.capability == "diagnostics"
)

META_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in META_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)

__all__ = [
    "META_ANNOTATION_OWNER",
    "META_CAPABILITY_METADATA",
    "META_CAPABILITY_PARTICIPATION",
    "META_CAPABILITY_BUNDLES",
    "META_CAPABILITY_PROFILES",
    "META_DEFAULTS_OWNER",
    "META_DIAGNOSTICS_CAPABILITY_METADATA",
    "META_DIAGNOSTICS_CAPABILITY_PROFILES",
    "META_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "META_IDENTITY_OWNER",
    "META_OBJECT_CONFIG_GRAPH_OWNER",
    "META_PROJECTION_OWNER",
    "META_SEMANTIC_ANALYSIS_CAPABILITY_METADATA",
    "META_SEMANTIC_ANALYSIS_CAPABILITY_PARTICIPATION",
    "META_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "META_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "META_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
    "META_TYPE_MIRROR_OWNER",
]
