"""Enhanced type system for representing complex primitive types."""

from typing import Protocol

# Code
from aware_code_ontology.primitive.code_primitive_type import CodePrimitiveType


class CodePrimitiveCodec(Protocol):
    def parse_exact(self, type_text: str) -> CodePrimitiveType | None: ...
    def parse(self, type_text: str) -> CodePrimitiveType | None: ...
    def render(self, prim: CodePrimitiveType) -> str | None: ...
    def enum_ident(self, type_text: str) -> str: ...
    def get_inner_type(self, type_text: str) -> str: ...
    def is_void(self, type_text: str) -> bool: ...
    def is_list(self, type_text: str) -> bool: ...
    def is_set(self, type_text: str) -> bool: ...
    def parse_literal(self, literal: str) -> object: ...
    def to_literal_string(self, value: object) -> str: ...
    def any(self) -> CodePrimitiveType: ...
    def uuid(self) -> CodePrimitiveType: ...
    def datetime(self) -> CodePrimitiveType: ...
