"""Templates for Python package artifacts (render-only, no filesystem side-effects)."""

from __future__ import annotations

import textwrap


_DEF_TEMPLATE_ORM = """\
from __future__ import annotations

# Auto-generated by Aware package strategy.
#
# Stable delegator: load bootstrap metadata from embedded `_aware/python.bootstrap.json`
# and let the ORM runtime handle deterministic module import + Pydantic rebuild.
#
# NOTE: The actual bootstrap mechanics live in aware_orm runtime so this file
# stays tiny and stable across package generations.

from aware_orm.runtime.package_bootstrap import bootstrap_orm_package_from_artifacts
from aware_orm.runtime.package_install import install_package_runtime_artifacts

def _bootstrap_models() -> None:
    \"\"\"Import generated modules and rebuild ORM models once.\"\"\"
    bootstrap_orm_package_from_artifacts(package_prefix=__name__)
    install_package_runtime_artifacts(package_prefix=__name__, strict=True)


# Run bootstrap on import so Pydantic models are usable immediately.
_bootstrap_models()
"""

_DEF_TEMPLATE_DTO = """\
from __future__ import annotations

# Auto-generated by Aware package strategy.
#
# Import all generated modules under this package and deterministically rebuild
# Pydantic models (forward refs).
#
# NOTE: DTO-only packages do NOT install ORM runtime artifacts. They intentionally
# avoid OCG→ORM binding so they can be reused as pure wire contracts.

from aware_utils.pydantic.package_bootstrap import bootstrap_pydantic_package_from_artifacts


def _bootstrap_models() -> None:
    \"\"\"Import generated modules and rebuild Pydantic models once.\"\"\"
    bootstrap_pydantic_package_from_artifacts(package_prefix=__name__)


# Run bootstrap on import so Pydantic models are usable immediately.
_bootstrap_models()
"""


def render_root_init(
    *,
    module_names: list[str],
    dependency_import_roots: list[str] | None = None,
    install_runtime_artifacts: bool = True,
    root_export_refs: list[str] | None = None,
) -> str:
    """
    Render the import-root `__init__.py`.

    Design goals:
    - No leading indentation at file-level.
    - Deterministic ordering.
    - Readable, Pydantic-friendly bootstrap without type ignores.
    """

    template_src = _DEF_TEMPLATE_ORM if install_runtime_artifacts else _DEF_TEMPLATE_DTO
    template = template_src
    _ = module_names
    _ = dependency_import_roots

    rendered = textwrap.dedent(template).rstrip()

    export_lines: list[str] = []
    public_names: list[str] = []
    seen: set[str] = set()
    for ref in root_export_refs or []:
        normalized = ref.strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        module_name, _, symbol_name = normalized.rpartition(".")
        if not module_name or not symbol_name:
            continue
        export_lines.append(f"from .{module_name} import {symbol_name}")
        public_names.append(symbol_name)

    if export_lines:
        rendered += "\n\n" + "\n".join(export_lines)
        rendered += "\n\n__all__ = [\n"
        for symbol_name in public_names:
            rendered += f'    "{symbol_name}",\n'
        rendered += "]"

    return rendered.rstrip() + "\n"
