from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_experience.semantic_contract import (
    AWARE_EXPERIENCE_SEMANTIC_CONTRACT,
    EXPERIENCE_ACTION_OWNER,
    EXPERIENCE_ACTOR_OWNER,
    EXPERIENCE_CAPABILITY_BUNDLES,
    EXPERIENCE_CAPABILITY_PARTICIPATION,
    EXPERIENCE_CAPABILITY_PROFILES,
    EXPERIENCE_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    EXPERIENCE_DIAGNOSTICS_CAPABILITY_PROFILES,
    EXPERIENCE_ENVIRONMENT_OWNER,
    EXPERIENCE_EVENT_OWNER,
    EXPERIENCE_GRAPH_OWNER,
    EXPERIENCE_PROGRAM_OWNER,
    EXPERIENCE_PROJECTION_OWNER,
    EXPERIENCE_ROLE_OWNER,
    EXPERIENCE_SEMANTIC_SCOPE_KEYS,
    EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
)

EXPERIENCE_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_EXPERIENCE_SEMANTIC_CONTRACT
)

EXPERIENCE_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in EXPERIENCE_CAPABILITY_METADATA if item.capability == "diagnostics"
)

EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in EXPERIENCE_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)

__all__ = [
    "EXPERIENCE_ACTION_OWNER",
    "EXPERIENCE_ACTOR_OWNER",
    "EXPERIENCE_CAPABILITY_METADATA",
    "EXPERIENCE_CAPABILITY_PARTICIPATION",
    "EXPERIENCE_CAPABILITY_BUNDLES",
    "EXPERIENCE_CAPABILITY_PROFILES",
    "EXPERIENCE_DIAGNOSTICS_CAPABILITY_METADATA",
    "EXPERIENCE_DIAGNOSTICS_CAPABILITY_PROFILES",
    "EXPERIENCE_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "EXPERIENCE_ENVIRONMENT_OWNER",
    "EXPERIENCE_EVENT_OWNER",
    "EXPERIENCE_GRAPH_OWNER",
    "EXPERIENCE_PROGRAM_OWNER",
    "EXPERIENCE_PROJECTION_OWNER",
    "EXPERIENCE_ROLE_OWNER",
    "EXPERIENCE_SEMANTIC_SCOPE_KEYS",
    "EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "EXPERIENCE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
]
