# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from typing import (
    TYPE_CHECKING,
    cast,
)

# Runtime
from aware_meta.runtime.generated_handlers import (
    constructor,
    instance,
)

if TYPE_CHECKING:
    from aware_meta_ontology.function.function_call import FunctionCall
    from aware_orm.models.orm_model import ORMModel
    from aware_orm.session.session import Session
    from aware_meta.runtime.generated_handlers import HandlerContext


async def sdk_config__build__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_config import build as _impl

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 1:
        _raw_title = args[1]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(name=name, title=title, description=description)
    return result, result


async def sdk_config__add_operation__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_config import add_operation as _impl

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 1:
        _raw_title = args[1]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    _raw_implementation_ref: object | None = None
    if "implementation_ref" in kwargs:
        _raw_implementation_ref = kwargs["implementation_ref"]
    elif len(args) > 3:
        _raw_implementation_ref = args[3]
    if _raw_implementation_ref is None:
        _raw_implementation_ref = None
    implementation_ref: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_implementation_ref))
    result = await _impl(
        sdk_config=orm_model, name=name, title=title, description=description, implementation_ref=implementation_ref
    )
    return result


async def sdk_config__add_surface__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_config import add_surface as _impl

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 1:
        _raw_title = args[1]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(sdk_config=orm_model, name=name, title=title, description=description)
    return result


async def sdk_operation__bind_api_capability_endpoint__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_operation import bind_api_capability_endpoint as _impl
    from uuid import UUID

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_api_capability_endpoint_id: object | None = None
    if "api_capability_endpoint_id" in kwargs:
        _raw_api_capability_endpoint_id = kwargs["api_capability_endpoint_id"]
    elif len(args) > 1:
        _raw_api_capability_endpoint_id = args[1]
    api_capability_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_capability_endpoint_id)
    _raw_endpoint_ref: object | None = None
    if "endpoint_ref" in kwargs:
        _raw_endpoint_ref = kwargs["endpoint_ref"]
    elif len(args) > 2:
        _raw_endpoint_ref = args[2]
    if _raw_endpoint_ref is None:
        _raw_endpoint_ref = None
    endpoint_ref: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_endpoint_ref))
    _raw_discriminant: object | None = None
    if "discriminant" in kwargs:
        _raw_discriminant = kwargs["discriminant"]
    elif len(args) > 3:
        _raw_discriminant = args[3]
    if _raw_discriminant is None:
        _raw_discriminant = None
    discriminant: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_discriminant))
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 4:
        _raw_role = args[4]
    if _raw_role is None:
        _raw_role = "primary"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_order: object | None = None
    if "order" in kwargs:
        _raw_order = kwargs["order"]
    elif len(args) > 5:
        _raw_order = args[5]
    if _raw_order is None:
        _raw_order = 1
    order: int = TypeAdapter(int).validate_python(_raw_order)
    _raw_required: object | None = None
    if "required" in kwargs:
        _raw_required = kwargs["required"]
    elif len(args) > 6:
        _raw_required = args[6]
    if _raw_required is None:
        _raw_required = True
    required: bool = TypeAdapter(bool).validate_python(_raw_required)
    result = await _impl(
        sdk_operation=orm_model,
        name=name,
        api_capability_endpoint_id=api_capability_endpoint_id,
        endpoint_ref=endpoint_ref,
        discriminant=discriminant,
        role=role,
        order=order,
        required=required,
    )
    return result


async def sdk_operation__bind_sdk_operation_dependency__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_operation import bind_sdk_operation_dependency as _impl
    from uuid import UUID

    _raw_target_sdk_operation_id: object | None = None
    if "target_sdk_operation_id" in kwargs:
        _raw_target_sdk_operation_id = kwargs["target_sdk_operation_id"]
    elif len(args) > 0:
        _raw_target_sdk_operation_id = args[0]
    target_sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_operation_id)
    _raw_target_operation_ref: object | None = None
    if "target_operation_ref" in kwargs:
        _raw_target_operation_ref = kwargs["target_operation_ref"]
    elif len(args) > 1:
        _raw_target_operation_ref = args[1]
    target_operation_ref: str = TypeAdapter(str).validate_python(_raw_target_operation_ref)
    _raw_target_sdk_name: object | None = None
    if "target_sdk_name" in kwargs:
        _raw_target_sdk_name = kwargs["target_sdk_name"]
    elif len(args) > 2:
        _raw_target_sdk_name = args[2]
    target_sdk_name: str = TypeAdapter(str).validate_python(_raw_target_sdk_name)
    _raw_target_operation_name: object | None = None
    if "target_operation_name" in kwargs:
        _raw_target_operation_name = kwargs["target_operation_name"]
    elif len(args) > 3:
        _raw_target_operation_name = args[3]
    target_operation_name: str = TypeAdapter(str).validate_python(_raw_target_operation_name)
    _raw_target_package_name: object | None = None
    if "target_package_name" in kwargs:
        _raw_target_package_name = kwargs["target_package_name"]
    elif len(args) > 4:
        _raw_target_package_name = args[4]
    if _raw_target_package_name is None:
        _raw_target_package_name = None
    target_package_name: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_target_package_name)
    )
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 5:
        _raw_role = args[5]
    if _raw_role is None:
        _raw_role = "dependency"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_order: object | None = None
    if "order" in kwargs:
        _raw_order = kwargs["order"]
    elif len(args) > 6:
        _raw_order = args[6]
    if _raw_order is None:
        _raw_order = 1
    order: int = TypeAdapter(int).validate_python(_raw_order)
    _raw_required: object | None = None
    if "required" in kwargs:
        _raw_required = kwargs["required"]
    elif len(args) > 7:
        _raw_required = args[7]
    if _raw_required is None:
        _raw_required = True
    required: bool = TypeAdapter(bool).validate_python(_raw_required)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 8:
        _raw_description = args[8]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_operation=orm_model,
        target_sdk_operation_id=target_sdk_operation_id,
        target_operation_ref=target_operation_ref,
        target_sdk_name=target_sdk_name,
        target_operation_name=target_operation_name,
        target_package_name=target_package_name,
        role=role,
        order=order,
        required=required,
        description=description,
    )
    return result


async def sdk_operation__build_via_sdk_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_operation import build_via_sdk_config as _impl
    from uuid import UUID

    _raw_sdk_config_id: object | None = None
    if "sdk_config_id" in kwargs:
        _raw_sdk_config_id = kwargs["sdk_config_id"]
    elif len(args) > 0:
        _raw_sdk_config_id = args[0]
    sdk_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_config_id)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 1:
        _raw_name = args[1]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 2:
        _raw_title = args[2]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 3:
        _raw_description = args[3]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    _raw_implementation_ref: object | None = None
    if "implementation_ref" in kwargs:
        _raw_implementation_ref = kwargs["implementation_ref"]
    elif len(args) > 4:
        _raw_implementation_ref = args[4]
    if _raw_implementation_ref is None:
        _raw_implementation_ref = None
    implementation_ref: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_implementation_ref))
    result = await _impl(
        sdk_config_id=sdk_config_id,
        name=name,
        title=title,
        description=description,
        implementation_ref=implementation_ref,
    )
    return result, result


async def sdk_operation_api_capability_endpoint__create_via_sdk_operation__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_operation_api_capability_endpoint import (
        create_via_sdk_operation as _impl,
    )
    from uuid import UUID

    _raw_sdk_operation_id: object | None = None
    if "sdk_operation_id" in kwargs:
        _raw_sdk_operation_id = kwargs["sdk_operation_id"]
    elif len(args) > 0:
        _raw_sdk_operation_id = args[0]
    sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_operation_id)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 1:
        _raw_name = args[1]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_api_capability_endpoint_id: object | None = None
    if "api_capability_endpoint_id" in kwargs:
        _raw_api_capability_endpoint_id = kwargs["api_capability_endpoint_id"]
    elif len(args) > 2:
        _raw_api_capability_endpoint_id = args[2]
    api_capability_endpoint_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_capability_endpoint_id)
    _raw_endpoint_ref: object | None = None
    if "endpoint_ref" in kwargs:
        _raw_endpoint_ref = kwargs["endpoint_ref"]
    elif len(args) > 3:
        _raw_endpoint_ref = args[3]
    if _raw_endpoint_ref is None:
        _raw_endpoint_ref = None
    endpoint_ref: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_endpoint_ref))
    _raw_discriminant: object | None = None
    if "discriminant" in kwargs:
        _raw_discriminant = kwargs["discriminant"]
    elif len(args) > 4:
        _raw_discriminant = args[4]
    if _raw_discriminant is None:
        _raw_discriminant = None
    discriminant: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_discriminant))
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 5:
        _raw_role = args[5]
    if _raw_role is None:
        _raw_role = "primary"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_order: object | None = None
    if "order" in kwargs:
        _raw_order = kwargs["order"]
    elif len(args) > 6:
        _raw_order = args[6]
    if _raw_order is None:
        _raw_order = 1
    order: int = TypeAdapter(int).validate_python(_raw_order)
    _raw_required: object | None = None
    if "required" in kwargs:
        _raw_required = kwargs["required"]
    elif len(args) > 7:
        _raw_required = args[7]
    if _raw_required is None:
        _raw_required = True
    required: bool = TypeAdapter(bool).validate_python(_raw_required)
    result = await _impl(
        sdk_operation_id=sdk_operation_id,
        name=name,
        api_capability_endpoint_id=api_capability_endpoint_id,
        endpoint_ref=endpoint_ref,
        discriminant=discriminant,
        role=role,
        order=order,
        required=required,
    )
    return result, result


async def sdk_operation_dependency__create_via_sdk_operation__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_operation_dependency import create_via_sdk_operation as _impl
    from uuid import UUID

    _raw_sdk_operation_id: object | None = None
    if "sdk_operation_id" in kwargs:
        _raw_sdk_operation_id = kwargs["sdk_operation_id"]
    elif len(args) > 0:
        _raw_sdk_operation_id = args[0]
    sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_operation_id)
    _raw_target_sdk_operation_id: object | None = None
    if "target_sdk_operation_id" in kwargs:
        _raw_target_sdk_operation_id = kwargs["target_sdk_operation_id"]
    elif len(args) > 1:
        _raw_target_sdk_operation_id = args[1]
    target_sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_operation_id)
    _raw_target_operation_ref: object | None = None
    if "target_operation_ref" in kwargs:
        _raw_target_operation_ref = kwargs["target_operation_ref"]
    elif len(args) > 2:
        _raw_target_operation_ref = args[2]
    target_operation_ref: str = TypeAdapter(str).validate_python(_raw_target_operation_ref)
    _raw_target_sdk_name: object | None = None
    if "target_sdk_name" in kwargs:
        _raw_target_sdk_name = kwargs["target_sdk_name"]
    elif len(args) > 3:
        _raw_target_sdk_name = args[3]
    target_sdk_name: str = TypeAdapter(str).validate_python(_raw_target_sdk_name)
    _raw_target_operation_name: object | None = None
    if "target_operation_name" in kwargs:
        _raw_target_operation_name = kwargs["target_operation_name"]
    elif len(args) > 4:
        _raw_target_operation_name = args[4]
    target_operation_name: str = TypeAdapter(str).validate_python(_raw_target_operation_name)
    _raw_target_package_name: object | None = None
    if "target_package_name" in kwargs:
        _raw_target_package_name = kwargs["target_package_name"]
    elif len(args) > 5:
        _raw_target_package_name = args[5]
    if _raw_target_package_name is None:
        _raw_target_package_name = None
    target_package_name: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_target_package_name)
    )
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 6:
        _raw_role = args[6]
    if _raw_role is None:
        _raw_role = "dependency"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_order: object | None = None
    if "order" in kwargs:
        _raw_order = kwargs["order"]
    elif len(args) > 7:
        _raw_order = args[7]
    if _raw_order is None:
        _raw_order = 1
    order: int = TypeAdapter(int).validate_python(_raw_order)
    _raw_required: object | None = None
    if "required" in kwargs:
        _raw_required = kwargs["required"]
    elif len(args) > 8:
        _raw_required = args[8]
    if _raw_required is None:
        _raw_required = True
    required: bool = TypeAdapter(bool).validate_python(_raw_required)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 9:
        _raw_description = args[9]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_operation_id=sdk_operation_id,
        target_sdk_operation_id=target_sdk_operation_id,
        target_operation_ref=target_operation_ref,
        target_sdk_name=target_sdk_name,
        target_operation_name=target_operation_name,
        target_package_name=target_package_name,
        role=role,
        order=order,
        required=required,
        description=description,
    )
    return result, result


async def sdk_package__build__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import build as _impl
    from aware_code.types import JsonArray, JsonObject
    from uuid import UUID

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_sdk_config_id: object | None = None
    if "sdk_config_id" in kwargs:
        _raw_sdk_config_id = kwargs["sdk_config_id"]
    elif len(args) > 1:
        _raw_sdk_config_id = args[1]
    sdk_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_config_id)
    _raw_sdk_config_object_instance_graph_commit_id: object | None = None
    if "sdk_config_object_instance_graph_commit_id" in kwargs:
        _raw_sdk_config_object_instance_graph_commit_id = kwargs["sdk_config_object_instance_graph_commit_id"]
    elif len(args) > 2:
        _raw_sdk_config_object_instance_graph_commit_id = args[2]
    if _raw_sdk_config_object_instance_graph_commit_id is None:
        _raw_sdk_config_object_instance_graph_commit_id = None
    sdk_config_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_sdk_config_object_instance_graph_commit_id)
    )
    _raw_source_code_package_id: object | None = None
    if "source_code_package_id" in kwargs:
        _raw_source_code_package_id = kwargs["source_code_package_id"]
    elif len(args) > 3:
        _raw_source_code_package_id = args[3]
    if _raw_source_code_package_id is None:
        _raw_source_code_package_id = None
    source_code_package_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_source_code_package_id)
    )
    _raw_fqn_prefix: object | None = None
    if "fqn_prefix" in kwargs:
        _raw_fqn_prefix = kwargs["fqn_prefix"]
    elif len(args) > 4:
        _raw_fqn_prefix = args[4]
    if _raw_fqn_prefix is None:
        _raw_fqn_prefix = None
    fqn_prefix: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_fqn_prefix))
    _raw_version_number: object | None = None
    if "version_number" in kwargs:
        _raw_version_number = kwargs["version_number"]
    elif len(args) > 5:
        _raw_version_number = args[5]
    if _raw_version_number is None:
        _raw_version_number = 1
    version_number: int = TypeAdapter(int).validate_python(_raw_version_number)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 6:
        _raw_title = args[6]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 7:
        _raw_description = args[7]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    _raw_aware_sdk_version: object | None = None
    if "aware_sdk_version" in kwargs:
        _raw_aware_sdk_version = kwargs["aware_sdk_version"]
    elif len(args) > 8:
        _raw_aware_sdk_version = args[8]
    if _raw_aware_sdk_version is None:
        _raw_aware_sdk_version = 1
    aware_sdk_version: int = TypeAdapter(int).validate_python(_raw_aware_sdk_version)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 9:
        _raw_manifest_relative_path = args[9]
    if _raw_manifest_relative_path is None:
        _raw_manifest_relative_path = None
    manifest_relative_path: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_manifest_relative_path)
    )
    _raw_package_root: object | None = None
    if "package_root" in kwargs:
        _raw_package_root = kwargs["package_root"]
    elif len(args) > 10:
        _raw_package_root = args[10]
    if _raw_package_root is None:
        _raw_package_root = "."
    package_root: str = TypeAdapter(str).validate_python(_raw_package_root)
    _raw_sources_root: object | None = None
    if "sources_root" in kwargs:
        _raw_sources_root = kwargs["sources_root"]
    elif len(args) > 11:
        _raw_sources_root = args[11]
    if _raw_sources_root is None:
        _raw_sources_root = "sdks"
    sources_root: str = TypeAdapter(str).validate_python(_raw_sources_root)
    _raw_include_paths: object | None = None
    if "include_paths" in kwargs:
        _raw_include_paths = kwargs["include_paths"]
    elif len(args) > 12:
        _raw_include_paths = args[12]
    if _raw_include_paths is None:
        _raw_include_paths = JsonArray()
    include_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_include_paths)
    _raw_exclude_paths: object | None = None
    if "exclude_paths" in kwargs:
        _raw_exclude_paths = kwargs["exclude_paths"]
    elif len(args) > 13:
        _raw_exclude_paths = args[13]
    if _raw_exclude_paths is None:
        _raw_exclude_paths = JsonArray()
    exclude_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_exclude_paths)
    _raw_force_fresh_scan: object | None = None
    if "force_fresh_scan" in kwargs:
        _raw_force_fresh_scan = kwargs["force_fresh_scan"]
    elif len(args) > 14:
        _raw_force_fresh_scan = args[14]
    if _raw_force_fresh_scan is None:
        _raw_force_fresh_scan = True
    force_fresh_scan: bool = TypeAdapter(bool).validate_python(_raw_force_fresh_scan)
    _raw_compilation_mode: object | None = None
    if "compilation_mode" in kwargs:
        _raw_compilation_mode = kwargs["compilation_mode"]
    elif len(args) > 15:
        _raw_compilation_mode = args[15]
    if _raw_compilation_mode is None:
        _raw_compilation_mode = "raw_xor"
    compilation_mode: str = TypeAdapter(str).validate_python(_raw_compilation_mode)
    _raw_dependencies: object | None = None
    if "dependencies" in kwargs:
        _raw_dependencies = kwargs["dependencies"]
    elif len(args) > 16:
        _raw_dependencies = args[16]
    if _raw_dependencies is None:
        _raw_dependencies = JsonArray()
    dependencies: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_dependencies)
    _raw_targets: object | None = None
    if "targets" in kwargs:
        _raw_targets = kwargs["targets"]
    elif len(args) > 17:
        _raw_targets = args[17]
    if _raw_targets is None:
        _raw_targets = JsonObject()
    targets: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_targets)
    result = await _impl(
        name=name,
        sdk_config_id=sdk_config_id,
        sdk_config_object_instance_graph_commit_id=sdk_config_object_instance_graph_commit_id,
        source_code_package_id=source_code_package_id,
        fqn_prefix=fqn_prefix,
        version_number=version_number,
        title=title,
        description=description,
        aware_sdk_version=aware_sdk_version,
        manifest_relative_path=manifest_relative_path,
        package_root=package_root,
        sources_root=sources_root,
        include_paths=include_paths,
        exclude_paths=exclude_paths,
        force_fresh_scan=force_fresh_scan,
        compilation_mode=compilation_mode,
        dependencies=dependencies,
        targets=targets,
    )
    return result, result


async def sdk_package__sync_manifest_truth__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import sync_manifest_truth as _impl
    from aware_code.types import JsonArray, JsonObject
    from uuid import UUID

    _raw_sdk_config_object_instance_graph_commit_id: object | None = None
    if "sdk_config_object_instance_graph_commit_id" in kwargs:
        _raw_sdk_config_object_instance_graph_commit_id = kwargs["sdk_config_object_instance_graph_commit_id"]
    elif len(args) > 0:
        _raw_sdk_config_object_instance_graph_commit_id = args[0]
    if _raw_sdk_config_object_instance_graph_commit_id is None:
        _raw_sdk_config_object_instance_graph_commit_id = None
    sdk_config_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_sdk_config_object_instance_graph_commit_id)
    )
    _raw_source_code_package_id: object | None = None
    if "source_code_package_id" in kwargs:
        _raw_source_code_package_id = kwargs["source_code_package_id"]
    elif len(args) > 1:
        _raw_source_code_package_id = args[1]
    if _raw_source_code_package_id is None:
        _raw_source_code_package_id = None
    source_code_package_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_source_code_package_id)
    )
    _raw_fqn_prefix: object | None = None
    if "fqn_prefix" in kwargs:
        _raw_fqn_prefix = kwargs["fqn_prefix"]
    elif len(args) > 2:
        _raw_fqn_prefix = args[2]
    if _raw_fqn_prefix is None:
        _raw_fqn_prefix = None
    fqn_prefix: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_fqn_prefix))
    _raw_version_number: object | None = None
    if "version_number" in kwargs:
        _raw_version_number = kwargs["version_number"]
    elif len(args) > 3:
        _raw_version_number = args[3]
    if _raw_version_number is None:
        _raw_version_number = 1
    version_number: int = TypeAdapter(int).validate_python(_raw_version_number)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 4:
        _raw_title = args[4]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 5:
        _raw_description = args[5]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    _raw_aware_sdk_version: object | None = None
    if "aware_sdk_version" in kwargs:
        _raw_aware_sdk_version = kwargs["aware_sdk_version"]
    elif len(args) > 6:
        _raw_aware_sdk_version = args[6]
    if _raw_aware_sdk_version is None:
        _raw_aware_sdk_version = 1
    aware_sdk_version: int = TypeAdapter(int).validate_python(_raw_aware_sdk_version)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 7:
        _raw_manifest_relative_path = args[7]
    if _raw_manifest_relative_path is None:
        _raw_manifest_relative_path = None
    manifest_relative_path: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_manifest_relative_path)
    )
    _raw_package_root: object | None = None
    if "package_root" in kwargs:
        _raw_package_root = kwargs["package_root"]
    elif len(args) > 8:
        _raw_package_root = args[8]
    if _raw_package_root is None:
        _raw_package_root = "."
    package_root: str = TypeAdapter(str).validate_python(_raw_package_root)
    _raw_sources_root: object | None = None
    if "sources_root" in kwargs:
        _raw_sources_root = kwargs["sources_root"]
    elif len(args) > 9:
        _raw_sources_root = args[9]
    if _raw_sources_root is None:
        _raw_sources_root = "sdks"
    sources_root: str = TypeAdapter(str).validate_python(_raw_sources_root)
    _raw_include_paths: object | None = None
    if "include_paths" in kwargs:
        _raw_include_paths = kwargs["include_paths"]
    elif len(args) > 10:
        _raw_include_paths = args[10]
    if _raw_include_paths is None:
        _raw_include_paths = JsonArray()
    include_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_include_paths)
    _raw_exclude_paths: object | None = None
    if "exclude_paths" in kwargs:
        _raw_exclude_paths = kwargs["exclude_paths"]
    elif len(args) > 11:
        _raw_exclude_paths = args[11]
    if _raw_exclude_paths is None:
        _raw_exclude_paths = JsonArray()
    exclude_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_exclude_paths)
    _raw_force_fresh_scan: object | None = None
    if "force_fresh_scan" in kwargs:
        _raw_force_fresh_scan = kwargs["force_fresh_scan"]
    elif len(args) > 12:
        _raw_force_fresh_scan = args[12]
    if _raw_force_fresh_scan is None:
        _raw_force_fresh_scan = True
    force_fresh_scan: bool = TypeAdapter(bool).validate_python(_raw_force_fresh_scan)
    _raw_compilation_mode: object | None = None
    if "compilation_mode" in kwargs:
        _raw_compilation_mode = kwargs["compilation_mode"]
    elif len(args) > 13:
        _raw_compilation_mode = args[13]
    if _raw_compilation_mode is None:
        _raw_compilation_mode = "raw_xor"
    compilation_mode: str = TypeAdapter(str).validate_python(_raw_compilation_mode)
    _raw_dependencies: object | None = None
    if "dependencies" in kwargs:
        _raw_dependencies = kwargs["dependencies"]
    elif len(args) > 14:
        _raw_dependencies = args[14]
    if _raw_dependencies is None:
        _raw_dependencies = JsonArray()
    dependencies: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_dependencies)
    _raw_targets: object | None = None
    if "targets" in kwargs:
        _raw_targets = kwargs["targets"]
    elif len(args) > 15:
        _raw_targets = args[15]
    if _raw_targets is None:
        _raw_targets = JsonObject()
    targets: JsonObject = TypeAdapter(JsonObject).validate_python(_raw_targets)
    result = await _impl(
        sdk_package=orm_model,
        sdk_config_object_instance_graph_commit_id=sdk_config_object_instance_graph_commit_id,
        source_code_package_id=source_code_package_id,
        fqn_prefix=fqn_prefix,
        version_number=version_number,
        title=title,
        description=description,
        aware_sdk_version=aware_sdk_version,
        manifest_relative_path=manifest_relative_path,
        package_root=package_root,
        sources_root=sources_root,
        include_paths=include_paths,
        exclude_paths=exclude_paths,
        force_fresh_scan=force_fresh_scan,
        compilation_mode=compilation_mode,
        dependencies=dependencies,
        targets=targets,
    )
    return result


async def sdk_package__attach_api_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import attach_api_package as _impl
    from uuid import UUID

    _raw_api_package_id: object | None = None
    if "api_package_id" in kwargs:
        _raw_api_package_id = kwargs["api_package_id"]
    elif len(args) > 0:
        _raw_api_package_id = args[0]
    api_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_package_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 1:
        _raw_description = args[1]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(sdk_package=orm_model, api_package_id=api_package_id, description=description)
    return result


async def sdk_package__attach_implementation_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import attach_implementation_package as _impl
    from aware_code.types import JsonArray
    from aware_code_ontology.code.code_enums import CodeLanguage
    from uuid import UUID

    _raw_code_package_id: object | None = None
    if "code_package_id" in kwargs:
        _raw_code_package_id = kwargs["code_package_id"]
    elif len(args) > 0:
        _raw_code_package_id = args[0]
    code_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_code_package_id)
    _raw_package_name: object | None = None
    if "package_name" in kwargs:
        _raw_package_name = kwargs["package_name"]
    elif len(args) > 1:
        _raw_package_name = args[1]
    package_name: str = TypeAdapter(str).validate_python(_raw_package_name)
    _raw_language: object | None = None
    if "language" in kwargs:
        _raw_language = kwargs["language"]
    elif len(args) > 2:
        _raw_language = args[2]
    language: CodeLanguage = TypeAdapter(CodeLanguage).validate_python(_raw_language)
    _raw_import_root: object | None = None
    if "import_root" in kwargs:
        _raw_import_root = kwargs["import_root"]
    elif len(args) > 3:
        _raw_import_root = args[3]
    import_root: str = TypeAdapter(str).validate_python(_raw_import_root)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 4:
        _raw_manifest_relative_path = args[4]
    manifest_relative_path: str = TypeAdapter(str).validate_python(_raw_manifest_relative_path)
    _raw_package_root: object | None = None
    if "package_root" in kwargs:
        _raw_package_root = kwargs["package_root"]
    elif len(args) > 5:
        _raw_package_root = args[5]
    if _raw_package_root is None:
        _raw_package_root = "."
    package_root: str = TypeAdapter(str).validate_python(_raw_package_root)
    _raw_entrypoint: object | None = None
    if "entrypoint" in kwargs:
        _raw_entrypoint = kwargs["entrypoint"]
    elif len(args) > 6:
        _raw_entrypoint = args[6]
    if _raw_entrypoint is None:
        _raw_entrypoint = None
    entrypoint: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_entrypoint))
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 7:
        _raw_role = args[7]
    if _raw_role is None:
        _raw_role = "public_package"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_include_paths: object | None = None
    if "include_paths" in kwargs:
        _raw_include_paths = kwargs["include_paths"]
    elif len(args) > 8:
        _raw_include_paths = args[8]
    if _raw_include_paths is None:
        _raw_include_paths = JsonArray()
    include_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_include_paths)
    _raw_exclude_paths: object | None = None
    if "exclude_paths" in kwargs:
        _raw_exclude_paths = kwargs["exclude_paths"]
    elif len(args) > 9:
        _raw_exclude_paths = args[9]
    if _raw_exclude_paths is None:
        _raw_exclude_paths = JsonArray()
    exclude_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_exclude_paths)
    result = await _impl(
        sdk_package=orm_model,
        code_package_id=code_package_id,
        package_name=package_name,
        language=language,
        import_root=import_root,
        manifest_relative_path=manifest_relative_path,
        package_root=package_root,
        entrypoint=entrypoint,
        role=role,
        include_paths=include_paths,
        exclude_paths=exclude_paths,
    )
    return result


async def sdk_package__attach_object_config_graph_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import attach_object_config_graph_package as _impl
    from uuid import UUID

    _raw_object_config_graph_package_id: object | None = None
    if "object_config_graph_package_id" in kwargs:
        _raw_object_config_graph_package_id = kwargs["object_config_graph_package_id"]
    elif len(args) > 0:
        _raw_object_config_graph_package_id = args[0]
    object_config_graph_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_object_config_graph_package_id)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 1:
        _raw_manifest_relative_path = args[1]
    manifest_relative_path: str = TypeAdapter(str).validate_python(_raw_manifest_relative_path)
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 2:
        _raw_role = args[2]
    if _raw_role is None:
        _raw_role = "local_state"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_package_kind: object | None = None
    if "package_kind" in kwargs:
        _raw_package_kind = kwargs["package_kind"]
    elif len(args) > 3:
        _raw_package_kind = args[3]
    if _raw_package_kind is None:
        _raw_package_kind = "state"
    package_kind: str = TypeAdapter(str).validate_python(_raw_package_kind)
    _raw_object_config_graph_package_object_instance_graph_commit_id: object | None = None
    if "object_config_graph_package_object_instance_graph_commit_id" in kwargs:
        _raw_object_config_graph_package_object_instance_graph_commit_id = kwargs[
            "object_config_graph_package_object_instance_graph_commit_id"
        ]
    elif len(args) > 4:
        _raw_object_config_graph_package_object_instance_graph_commit_id = args[4]
    if _raw_object_config_graph_package_object_instance_graph_commit_id is None:
        _raw_object_config_graph_package_object_instance_graph_commit_id = None
    object_config_graph_package_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None,
        TypeAdapter(UUID | None).validate_python(_raw_object_config_graph_package_object_instance_graph_commit_id),
    )
    _raw_expected_hash_sha256: object | None = None
    if "expected_hash_sha256" in kwargs:
        _raw_expected_hash_sha256 = kwargs["expected_hash_sha256"]
    elif len(args) > 5:
        _raw_expected_hash_sha256 = args[5]
    if _raw_expected_hash_sha256 is None:
        _raw_expected_hash_sha256 = None
    expected_hash_sha256: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_expected_hash_sha256)
    )
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 6:
        _raw_description = args[6]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_package=orm_model,
        object_config_graph_package_id=object_config_graph_package_id,
        manifest_relative_path=manifest_relative_path,
        role=role,
        package_kind=package_kind,
        object_config_graph_package_object_instance_graph_commit_id=object_config_graph_package_object_instance_graph_commit_id,
        expected_hash_sha256=expected_hash_sha256,
        description=description,
    )
    return result


async def sdk_package__attach_sdk_package_dependency__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package import attach_sdk_package_dependency as _impl
    from uuid import UUID

    _raw_target_sdk_package_id: object | None = None
    if "target_sdk_package_id" in kwargs:
        _raw_target_sdk_package_id = kwargs["target_sdk_package_id"]
    elif len(args) > 0:
        _raw_target_sdk_package_id = args[0]
    target_sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_package_id)
    _raw_target_package_name: object | None = None
    if "target_package_name" in kwargs:
        _raw_target_package_name = kwargs["target_package_name"]
    elif len(args) > 1:
        _raw_target_package_name = args[1]
    target_package_name: str = TypeAdapter(str).validate_python(_raw_target_package_name)
    _raw_target_sdk_package_object_instance_graph_commit_id: object | None = None
    if "target_sdk_package_object_instance_graph_commit_id" in kwargs:
        _raw_target_sdk_package_object_instance_graph_commit_id = kwargs[
            "target_sdk_package_object_instance_graph_commit_id"
        ]
    elif len(args) > 2:
        _raw_target_sdk_package_object_instance_graph_commit_id = args[2]
    if _raw_target_sdk_package_object_instance_graph_commit_id is None:
        _raw_target_sdk_package_object_instance_graph_commit_id = None
    target_sdk_package_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_target_sdk_package_object_instance_graph_commit_id)
    )
    _raw_target_version_number: object | None = None
    if "target_version_number" in kwargs:
        _raw_target_version_number = kwargs["target_version_number"]
    elif len(args) > 3:
        _raw_target_version_number = args[3]
    if _raw_target_version_number is None:
        _raw_target_version_number = None
    target_version_number: int | None = cast(
        int | None, TypeAdapter(int | None).validate_python(_raw_target_version_number)
    )
    _raw_expected_hash_sha256: object | None = None
    if "expected_hash_sha256" in kwargs:
        _raw_expected_hash_sha256 = kwargs["expected_hash_sha256"]
    elif len(args) > 4:
        _raw_expected_hash_sha256 = args[4]
    if _raw_expected_hash_sha256 is None:
        _raw_expected_hash_sha256 = None
    expected_hash_sha256: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_expected_hash_sha256)
    )
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 5:
        _raw_description = args[5]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_package=orm_model,
        target_sdk_package_id=target_sdk_package_id,
        target_package_name=target_package_name,
        target_sdk_package_object_instance_graph_commit_id=target_sdk_package_object_instance_graph_commit_id,
        target_version_number=target_version_number,
        expected_hash_sha256=expected_hash_sha256,
        description=description,
    )
    return result


async def sdk_package_api_package__build_via_sdk_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package_api_package import build_via_sdk_package as _impl
    from uuid import UUID

    _raw_sdk_package_id: object | None = None
    if "sdk_package_id" in kwargs:
        _raw_sdk_package_id = kwargs["sdk_package_id"]
    elif len(args) > 0:
        _raw_sdk_package_id = args[0]
    sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_package_id)
    _raw_api_package_id: object | None = None
    if "api_package_id" in kwargs:
        _raw_api_package_id = kwargs["api_package_id"]
    elif len(args) > 1:
        _raw_api_package_id = args[1]
    api_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_api_package_id)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 2:
        _raw_description = args[2]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(sdk_package_id=sdk_package_id, api_package_id=api_package_id, description=description)
    return result, result


async def sdk_package_dependency__build_via_sdk_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package_dependency import build_via_sdk_package as _impl
    from uuid import UUID

    _raw_sdk_package_id: object | None = None
    if "sdk_package_id" in kwargs:
        _raw_sdk_package_id = kwargs["sdk_package_id"]
    elif len(args) > 0:
        _raw_sdk_package_id = args[0]
    sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_package_id)
    _raw_target_sdk_package_id: object | None = None
    if "target_sdk_package_id" in kwargs:
        _raw_target_sdk_package_id = kwargs["target_sdk_package_id"]
    elif len(args) > 1:
        _raw_target_sdk_package_id = args[1]
    target_sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_package_id)
    _raw_target_package_name: object | None = None
    if "target_package_name" in kwargs:
        _raw_target_package_name = kwargs["target_package_name"]
    elif len(args) > 2:
        _raw_target_package_name = args[2]
    target_package_name: str = TypeAdapter(str).validate_python(_raw_target_package_name)
    _raw_target_sdk_package_object_instance_graph_commit_id: object | None = None
    if "target_sdk_package_object_instance_graph_commit_id" in kwargs:
        _raw_target_sdk_package_object_instance_graph_commit_id = kwargs[
            "target_sdk_package_object_instance_graph_commit_id"
        ]
    elif len(args) > 3:
        _raw_target_sdk_package_object_instance_graph_commit_id = args[3]
    if _raw_target_sdk_package_object_instance_graph_commit_id is None:
        _raw_target_sdk_package_object_instance_graph_commit_id = None
    target_sdk_package_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None, TypeAdapter(UUID | None).validate_python(_raw_target_sdk_package_object_instance_graph_commit_id)
    )
    _raw_target_version_number: object | None = None
    if "target_version_number" in kwargs:
        _raw_target_version_number = kwargs["target_version_number"]
    elif len(args) > 4:
        _raw_target_version_number = args[4]
    if _raw_target_version_number is None:
        _raw_target_version_number = None
    target_version_number: int | None = cast(
        int | None, TypeAdapter(int | None).validate_python(_raw_target_version_number)
    )
    _raw_expected_hash_sha256: object | None = None
    if "expected_hash_sha256" in kwargs:
        _raw_expected_hash_sha256 = kwargs["expected_hash_sha256"]
    elif len(args) > 5:
        _raw_expected_hash_sha256 = args[5]
    if _raw_expected_hash_sha256 is None:
        _raw_expected_hash_sha256 = None
    expected_hash_sha256: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_expected_hash_sha256)
    )
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 6:
        _raw_description = args[6]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_package_id=sdk_package_id,
        target_sdk_package_id=target_sdk_package_id,
        target_package_name=target_package_name,
        target_sdk_package_object_instance_graph_commit_id=target_sdk_package_object_instance_graph_commit_id,
        target_version_number=target_version_number,
        expected_hash_sha256=expected_hash_sha256,
        description=description,
    )
    return result, result


async def sdk_package_implementation_package__build_via_sdk_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package_implementation_package import build_via_sdk_package as _impl
    from aware_code.types import JsonArray
    from aware_code_ontology.code.code_enums import CodeLanguage
    from uuid import UUID

    _raw_sdk_package_id: object | None = None
    if "sdk_package_id" in kwargs:
        _raw_sdk_package_id = kwargs["sdk_package_id"]
    elif len(args) > 0:
        _raw_sdk_package_id = args[0]
    sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_package_id)
    _raw_code_package_id: object | None = None
    if "code_package_id" in kwargs:
        _raw_code_package_id = kwargs["code_package_id"]
    elif len(args) > 1:
        _raw_code_package_id = args[1]
    code_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_code_package_id)
    _raw_package_name: object | None = None
    if "package_name" in kwargs:
        _raw_package_name = kwargs["package_name"]
    elif len(args) > 2:
        _raw_package_name = args[2]
    package_name: str = TypeAdapter(str).validate_python(_raw_package_name)
    _raw_language: object | None = None
    if "language" in kwargs:
        _raw_language = kwargs["language"]
    elif len(args) > 3:
        _raw_language = args[3]
    language: CodeLanguage = TypeAdapter(CodeLanguage).validate_python(_raw_language)
    _raw_import_root: object | None = None
    if "import_root" in kwargs:
        _raw_import_root = kwargs["import_root"]
    elif len(args) > 4:
        _raw_import_root = args[4]
    import_root: str = TypeAdapter(str).validate_python(_raw_import_root)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 5:
        _raw_manifest_relative_path = args[5]
    manifest_relative_path: str = TypeAdapter(str).validate_python(_raw_manifest_relative_path)
    _raw_package_root: object | None = None
    if "package_root" in kwargs:
        _raw_package_root = kwargs["package_root"]
    elif len(args) > 6:
        _raw_package_root = args[6]
    if _raw_package_root is None:
        _raw_package_root = "."
    package_root: str = TypeAdapter(str).validate_python(_raw_package_root)
    _raw_entrypoint: object | None = None
    if "entrypoint" in kwargs:
        _raw_entrypoint = kwargs["entrypoint"]
    elif len(args) > 7:
        _raw_entrypoint = args[7]
    if _raw_entrypoint is None:
        _raw_entrypoint = None
    entrypoint: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_entrypoint))
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 8:
        _raw_role = args[8]
    if _raw_role is None:
        _raw_role = "public_package"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_include_paths: object | None = None
    if "include_paths" in kwargs:
        _raw_include_paths = kwargs["include_paths"]
    elif len(args) > 9:
        _raw_include_paths = args[9]
    if _raw_include_paths is None:
        _raw_include_paths = JsonArray()
    include_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_include_paths)
    _raw_exclude_paths: object | None = None
    if "exclude_paths" in kwargs:
        _raw_exclude_paths = kwargs["exclude_paths"]
    elif len(args) > 10:
        _raw_exclude_paths = args[10]
    if _raw_exclude_paths is None:
        _raw_exclude_paths = JsonArray()
    exclude_paths: JsonArray = TypeAdapter(JsonArray).validate_python(_raw_exclude_paths)
    result = await _impl(
        sdk_package_id=sdk_package_id,
        code_package_id=code_package_id,
        package_name=package_name,
        language=language,
        import_root=import_root,
        manifest_relative_path=manifest_relative_path,
        package_root=package_root,
        entrypoint=entrypoint,
        role=role,
        include_paths=include_paths,
        exclude_paths=exclude_paths,
    )
    return result, result


async def sdk_package_object_config_graph_package__build_via_sdk_package__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_package_object_config_graph_package import (
        build_via_sdk_package as _impl,
    )
    from uuid import UUID

    _raw_sdk_package_id: object | None = None
    if "sdk_package_id" in kwargs:
        _raw_sdk_package_id = kwargs["sdk_package_id"]
    elif len(args) > 0:
        _raw_sdk_package_id = args[0]
    sdk_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_package_id)
    _raw_object_config_graph_package_id: object | None = None
    if "object_config_graph_package_id" in kwargs:
        _raw_object_config_graph_package_id = kwargs["object_config_graph_package_id"]
    elif len(args) > 1:
        _raw_object_config_graph_package_id = args[1]
    object_config_graph_package_id: UUID = TypeAdapter(UUID).validate_python(_raw_object_config_graph_package_id)
    _raw_manifest_relative_path: object | None = None
    if "manifest_relative_path" in kwargs:
        _raw_manifest_relative_path = kwargs["manifest_relative_path"]
    elif len(args) > 2:
        _raw_manifest_relative_path = args[2]
    manifest_relative_path: str = TypeAdapter(str).validate_python(_raw_manifest_relative_path)
    _raw_role: object | None = None
    if "role" in kwargs:
        _raw_role = kwargs["role"]
    elif len(args) > 3:
        _raw_role = args[3]
    if _raw_role is None:
        _raw_role = "local_state"
    role: str = TypeAdapter(str).validate_python(_raw_role)
    _raw_package_kind: object | None = None
    if "package_kind" in kwargs:
        _raw_package_kind = kwargs["package_kind"]
    elif len(args) > 4:
        _raw_package_kind = args[4]
    if _raw_package_kind is None:
        _raw_package_kind = "state"
    package_kind: str = TypeAdapter(str).validate_python(_raw_package_kind)
    _raw_object_config_graph_package_object_instance_graph_commit_id: object | None = None
    if "object_config_graph_package_object_instance_graph_commit_id" in kwargs:
        _raw_object_config_graph_package_object_instance_graph_commit_id = kwargs[
            "object_config_graph_package_object_instance_graph_commit_id"
        ]
    elif len(args) > 5:
        _raw_object_config_graph_package_object_instance_graph_commit_id = args[5]
    if _raw_object_config_graph_package_object_instance_graph_commit_id is None:
        _raw_object_config_graph_package_object_instance_graph_commit_id = None
    object_config_graph_package_object_instance_graph_commit_id: UUID | None = cast(
        UUID | None,
        TypeAdapter(UUID | None).validate_python(_raw_object_config_graph_package_object_instance_graph_commit_id),
    )
    _raw_expected_hash_sha256: object | None = None
    if "expected_hash_sha256" in kwargs:
        _raw_expected_hash_sha256 = kwargs["expected_hash_sha256"]
    elif len(args) > 6:
        _raw_expected_hash_sha256 = args[6]
    if _raw_expected_hash_sha256 is None:
        _raw_expected_hash_sha256 = None
    expected_hash_sha256: str | None = cast(
        str | None, TypeAdapter(str | None).validate_python(_raw_expected_hash_sha256)
    )
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 7:
        _raw_description = args[7]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_package_id=sdk_package_id,
        object_config_graph_package_id=object_config_graph_package_id,
        manifest_relative_path=manifest_relative_path,
        role=role,
        package_kind=package_kind,
        object_config_graph_package_object_instance_graph_commit_id=object_config_graph_package_object_instance_graph_commit_id,
        expected_hash_sha256=expected_hash_sha256,
        description=description,
    )
    return result, result


async def sdk_surface__add_method__handler(
    session: Session,
    ctx: HandlerContext,
    orm_model: ORMModel,
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> object:
    _ = session, ctx, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_surface import add_method as _impl
    from uuid import UUID

    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 0:
        _raw_name = args[0]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_target_sdk_operation_id: object | None = None
    if "target_sdk_operation_id" in kwargs:
        _raw_target_sdk_operation_id = kwargs["target_sdk_operation_id"]
    elif len(args) > 1:
        _raw_target_sdk_operation_id = args[1]
    target_sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_operation_id)
    _raw_operation_ref: object | None = None
    if "operation_ref" in kwargs:
        _raw_operation_ref = kwargs["operation_ref"]
    elif len(args) > 2:
        _raw_operation_ref = args[2]
    operation_ref: str = TypeAdapter(str).validate_python(_raw_operation_ref)
    _raw_operation_name: object | None = None
    if "operation_name" in kwargs:
        _raw_operation_name = kwargs["operation_name"]
    elif len(args) > 3:
        _raw_operation_name = args[3]
    operation_name: str = TypeAdapter(str).validate_python(_raw_operation_name)
    _raw_method_family: object | None = None
    if "method_family" in kwargs:
        _raw_method_family = kwargs["method_family"]
    elif len(args) > 4:
        _raw_method_family = args[4]
    method_family: str = TypeAdapter(str).validate_python(_raw_method_family)
    _raw_effect: object | None = None
    if "effect" in kwargs:
        _raw_effect = kwargs["effect"]
    elif len(args) > 5:
        _raw_effect = args[5]
    if _raw_effect is None:
        _raw_effect = "read"
    effect: str = TypeAdapter(str).validate_python(_raw_effect)
    _raw_mutation_scope: object | None = None
    if "mutation_scope" in kwargs:
        _raw_mutation_scope = kwargs["mutation_scope"]
    elif len(args) > 6:
        _raw_mutation_scope = args[6]
    if _raw_mutation_scope is None:
        _raw_mutation_scope = "none"
    mutation_scope: str = TypeAdapter(str).validate_python(_raw_mutation_scope)
    _raw_confirmation_policy: object | None = None
    if "confirmation_policy" in kwargs:
        _raw_confirmation_policy = kwargs["confirmation_policy"]
    elif len(args) > 7:
        _raw_confirmation_policy = args[7]
    if _raw_confirmation_policy is None:
        _raw_confirmation_policy = "none"
    confirmation_policy: str = TypeAdapter(str).validate_python(_raw_confirmation_policy)
    _raw_execution_mode: object | None = None
    if "execution_mode" in kwargs:
        _raw_execution_mode = kwargs["execution_mode"]
    elif len(args) > 8:
        _raw_execution_mode = args[8]
    if _raw_execution_mode is None:
        _raw_execution_mode = "request_response"
    execution_mode: str = TypeAdapter(str).validate_python(_raw_execution_mode)
    _raw_runtime_binding_kind: object | None = None
    if "runtime_binding_kind" in kwargs:
        _raw_runtime_binding_kind = kwargs["runtime_binding_kind"]
    elif len(args) > 9:
        _raw_runtime_binding_kind = args[9]
    if _raw_runtime_binding_kind is None:
        _raw_runtime_binding_kind = "unbound"
    runtime_binding_kind: str = TypeAdapter(str).validate_python(_raw_runtime_binding_kind)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 10:
        _raw_description = args[10]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_surface=orm_model,
        name=name,
        target_sdk_operation_id=target_sdk_operation_id,
        operation_ref=operation_ref,
        operation_name=operation_name,
        method_family=method_family,
        effect=effect,
        mutation_scope=mutation_scope,
        confirmation_policy=confirmation_policy,
        execution_mode=execution_mode,
        runtime_binding_kind=runtime_binding_kind,
        description=description,
    )
    return result


async def sdk_surface__build_via_sdk_config__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_surface import build_via_sdk_config as _impl
    from uuid import UUID

    _raw_sdk_config_id: object | None = None
    if "sdk_config_id" in kwargs:
        _raw_sdk_config_id = kwargs["sdk_config_id"]
    elif len(args) > 0:
        _raw_sdk_config_id = args[0]
    sdk_config_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_config_id)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 1:
        _raw_name = args[1]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_title: object | None = None
    if "title" in kwargs:
        _raw_title = kwargs["title"]
    elif len(args) > 2:
        _raw_title = args[2]
    if _raw_title is None:
        _raw_title = None
    title: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_title))
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 3:
        _raw_description = args[3]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(sdk_config_id=sdk_config_id, name=name, title=title, description=description)
    return result, result


async def sdk_surface_method__create_via_sdk_surface__handler(
    session: Session,
    ctx: HandlerContext,
    orm_class: type[ORMModel],
    args: list[object],
    kwargs: dict[str, object],
    function_call: FunctionCall,
) -> tuple[ORMModel, object]:
    _ = session, ctx, orm_class, kwargs, function_call
    from pydantic import TypeAdapter
    from aware_sdk_runtime.handlers.impl.sdk.sdk_surface_method import create_via_sdk_surface as _impl
    from uuid import UUID

    _raw_sdk_surface_id: object | None = None
    if "sdk_surface_id" in kwargs:
        _raw_sdk_surface_id = kwargs["sdk_surface_id"]
    elif len(args) > 0:
        _raw_sdk_surface_id = args[0]
    sdk_surface_id: UUID = TypeAdapter(UUID).validate_python(_raw_sdk_surface_id)
    _raw_name: object | None = None
    if "name" in kwargs:
        _raw_name = kwargs["name"]
    elif len(args) > 1:
        _raw_name = args[1]
    name: str = TypeAdapter(str).validate_python(_raw_name)
    _raw_target_sdk_operation_id: object | None = None
    if "target_sdk_operation_id" in kwargs:
        _raw_target_sdk_operation_id = kwargs["target_sdk_operation_id"]
    elif len(args) > 2:
        _raw_target_sdk_operation_id = args[2]
    target_sdk_operation_id: UUID = TypeAdapter(UUID).validate_python(_raw_target_sdk_operation_id)
    _raw_operation_ref: object | None = None
    if "operation_ref" in kwargs:
        _raw_operation_ref = kwargs["operation_ref"]
    elif len(args) > 3:
        _raw_operation_ref = args[3]
    operation_ref: str = TypeAdapter(str).validate_python(_raw_operation_ref)
    _raw_operation_name: object | None = None
    if "operation_name" in kwargs:
        _raw_operation_name = kwargs["operation_name"]
    elif len(args) > 4:
        _raw_operation_name = args[4]
    operation_name: str = TypeAdapter(str).validate_python(_raw_operation_name)
    _raw_method_family: object | None = None
    if "method_family" in kwargs:
        _raw_method_family = kwargs["method_family"]
    elif len(args) > 5:
        _raw_method_family = args[5]
    method_family: str = TypeAdapter(str).validate_python(_raw_method_family)
    _raw_effect: object | None = None
    if "effect" in kwargs:
        _raw_effect = kwargs["effect"]
    elif len(args) > 6:
        _raw_effect = args[6]
    if _raw_effect is None:
        _raw_effect = "read"
    effect: str = TypeAdapter(str).validate_python(_raw_effect)
    _raw_mutation_scope: object | None = None
    if "mutation_scope" in kwargs:
        _raw_mutation_scope = kwargs["mutation_scope"]
    elif len(args) > 7:
        _raw_mutation_scope = args[7]
    if _raw_mutation_scope is None:
        _raw_mutation_scope = "none"
    mutation_scope: str = TypeAdapter(str).validate_python(_raw_mutation_scope)
    _raw_confirmation_policy: object | None = None
    if "confirmation_policy" in kwargs:
        _raw_confirmation_policy = kwargs["confirmation_policy"]
    elif len(args) > 8:
        _raw_confirmation_policy = args[8]
    if _raw_confirmation_policy is None:
        _raw_confirmation_policy = "none"
    confirmation_policy: str = TypeAdapter(str).validate_python(_raw_confirmation_policy)
    _raw_execution_mode: object | None = None
    if "execution_mode" in kwargs:
        _raw_execution_mode = kwargs["execution_mode"]
    elif len(args) > 9:
        _raw_execution_mode = args[9]
    if _raw_execution_mode is None:
        _raw_execution_mode = "request_response"
    execution_mode: str = TypeAdapter(str).validate_python(_raw_execution_mode)
    _raw_runtime_binding_kind: object | None = None
    if "runtime_binding_kind" in kwargs:
        _raw_runtime_binding_kind = kwargs["runtime_binding_kind"]
    elif len(args) > 10:
        _raw_runtime_binding_kind = args[10]
    if _raw_runtime_binding_kind is None:
        _raw_runtime_binding_kind = "unbound"
    runtime_binding_kind: str = TypeAdapter(str).validate_python(_raw_runtime_binding_kind)
    _raw_description: object | None = None
    if "description" in kwargs:
        _raw_description = kwargs["description"]
    elif len(args) > 11:
        _raw_description = args[11]
    if _raw_description is None:
        _raw_description = None
    description: str | None = cast(str | None, TypeAdapter(str | None).validate_python(_raw_description))
    result = await _impl(
        sdk_surface_id=sdk_surface_id,
        name=name,
        target_sdk_operation_id=target_sdk_operation_id,
        operation_ref=operation_ref,
        operation_name=operation_name,
        method_family=method_family,
        effect=effect,
        mutation_scope=mutation_scope,
        confirmation_policy=confirmation_policy,
        execution_mode=execution_mode,
        runtime_binding_kind=runtime_binding_kind,
        description=description,
    )
    return result, result


AWARE_HANDLERS = [
    constructor("aware_sdk_ontology.sdk.sdk_config.SdkConfig", "build", sdk_config__build__handler),
    instance("aware_sdk_ontology.sdk.sdk_config.SdkConfig", "add_operation", sdk_config__add_operation__handler),
    instance("aware_sdk_ontology.sdk.sdk_config.SdkConfig", "add_surface", sdk_config__add_surface__handler),
    instance(
        "aware_sdk_ontology.sdk.sdk_operation.SdkOperation",
        "bind_api_capability_endpoint",
        sdk_operation__bind_api_capability_endpoint__handler,
    ),
    instance(
        "aware_sdk_ontology.sdk.sdk_operation.SdkOperation",
        "bind_sdk_operation_dependency",
        sdk_operation__bind_sdk_operation_dependency__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_operation.SdkOperation",
        "build_via_sdk_config",
        sdk_operation__build_via_sdk_config__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_operation_api_capability_endpoint.SdkOperationApiCapabilityEndpoint",
        "create_via_sdk_operation",
        sdk_operation_api_capability_endpoint__create_via_sdk_operation__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_operation_dependency.SdkOperationDependency",
        "create_via_sdk_operation",
        sdk_operation_dependency__create_via_sdk_operation__handler,
    ),
    constructor("aware_sdk_ontology.sdk.sdk_package.SdkPackage", "build", sdk_package__build__handler),
    instance(
        "aware_sdk_ontology.sdk.sdk_package.SdkPackage",
        "sync_manifest_truth",
        sdk_package__sync_manifest_truth__handler,
    ),
    instance(
        "aware_sdk_ontology.sdk.sdk_package.SdkPackage", "attach_api_package", sdk_package__attach_api_package__handler
    ),
    instance(
        "aware_sdk_ontology.sdk.sdk_package.SdkPackage",
        "attach_implementation_package",
        sdk_package__attach_implementation_package__handler,
    ),
    instance(
        "aware_sdk_ontology.sdk.sdk_package.SdkPackage",
        "attach_object_config_graph_package",
        sdk_package__attach_object_config_graph_package__handler,
    ),
    instance(
        "aware_sdk_ontology.sdk.sdk_package.SdkPackage",
        "attach_sdk_package_dependency",
        sdk_package__attach_sdk_package_dependency__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_package_api_package.SdkPackageApiPackage",
        "build_via_sdk_package",
        sdk_package_api_package__build_via_sdk_package__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_package_dependency.SdkPackageDependency",
        "build_via_sdk_package",
        sdk_package_dependency__build_via_sdk_package__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_package_implementation_package.SdkPackageImplementationPackage",
        "build_via_sdk_package",
        sdk_package_implementation_package__build_via_sdk_package__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_package_object_config_graph_package.SdkPackageObjectConfigGraphPackage",
        "build_via_sdk_package",
        sdk_package_object_config_graph_package__build_via_sdk_package__handler,
    ),
    instance("aware_sdk_ontology.sdk.sdk_surface.SdkSurface", "add_method", sdk_surface__add_method__handler),
    constructor(
        "aware_sdk_ontology.sdk.sdk_surface.SdkSurface",
        "build_via_sdk_config",
        sdk_surface__build_via_sdk_config__handler,
    ),
    constructor(
        "aware_sdk_ontology.sdk.sdk_surface_method.SdkSurfaceMethod",
        "create_via_sdk_surface",
        sdk_surface_method__create_via_sdk_surface__handler,
    ),
]

__all__ = ["AWARE_HANDLERS"]
