"""Canonical shared service runtime contracts and compatibility adapters.

Environment-shaped compatibility types remain re-exported here for migration
only. New Environment-bound imports should prefer
`aware_service_runtime.adapters.environment`.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

_MODULE_EXPORTS: dict[str, tuple[str, ...]] = {
    ".contracts": (
        "ActivateServiceHostLifecyclesHostControlRequest",
        "ActivateServiceHostLifecyclesHostControlResponse",
        "coerce_request_status",
        "ConfigureServiceApiDependencyRoutesHostControlRequest",
        "ConfigureServiceApiDependencyRoutesHostControlResponse",
        "MetaTemporalGraphRoute",
        "RequestStatus",
        "ServiceGraphContextProvider",
        "ServiceGraphGateway",
        "ServiceHostControlRequest",
        "ServiceHostControlResponse",
        "ServiceLaneSubscriptionBinding",
        "ServiceHostTransport",
        "ServiceOperationContext",
        "ServiceOperationHandler",
        "ServiceOperationInvocation",
        "ServiceOperationInvocationHandler",
        "ServiceOperationPluginHandler",
        "ServiceOperationRequest",
        "ServiceOperationResponse",
        "ServiceOperationResult",
        "ServiceOperationTransport",
        "ServiceStreamControlKind",
        "ServiceStreamControlRequest",
        "ServiceStreamControlResponse",
        "ServiceStreamEventEnvelope",
        "ServiceStreamEventKind",
        "ServiceStreamPublisher",
        "ServiceStreamSession",
        "ServiceStreamSubscriber",
        "StreamLifecycle",
    ),
    ".api_ingress": (
        "ResolvedServiceApiDispatch",
        "ResolvedServiceApiDispatchCandidate",
        "ServiceApiGraphExecutionBinding",
        "ServiceApiGraphExecutionPlan",
        "build_service_api_graph_execution_plan",
        "require_single_service_api_dispatch_candidate",
        "resolve_service_api_dispatch",
    ),
    ".duplex": (
        "JsonValue",
        "ServiceDuplexHostControlRequest",
        "ServiceDuplexHostControlResponse",
        "ServiceDuplexLaneCommitReceiptNotification",
        "ServiceDuplexOperationContext",
        "ServiceDuplexOperationRequest",
        "ServiceDuplexOperationResponse",
        "ServiceDuplexStreamControlRequest",
        "ServiceDuplexStreamControlResponse",
        "ServiceDuplexStreamEvent",
        "ServiceDuplexStreamEventEnvelope",
        "ServiceDuplexStreamEventKind",
        "ServiceDuplexStreamSession",
        "dump_service_duplex_payload",
        "service_duplex_operation_response_payload_from_contract",
        "service_duplex_trusted_json_payload",
    ),
    ".duplex_client": (
        "build_service_host_duplex_client_from_env",
        "ServiceHostDuplexClient",
        "ServiceHostDuplexRequestHandle",
    ),
    ".local_service_host_api_client": (
        "build_service_api_client_for_api_package",
        "build_service_api_client_for_route",
        "build_local_service_host_api_client_for_route",
        "build_local_service_host_duplex_client_factory_for_route",
        "build_remote_node_api_client_for_route",
        "LocalServiceHostApiConfig",
        "LocalServiceHostAwareApiClient",
        "RemoteNodeApiEndpointConfig",
        "RemoteNodeAwareApiClient",
    ),
    ".local_authority": (
        "SERVICE_HOST_ATTACHMENT_CONTRACT_VERSION",
        "SERVICE_HOST_LIFECYCLE_UPDATE_CONTRACT_VERSION",
        "SERVICE_HOST_LIFECYCLE_UPDATE_JOURNAL_CONTRACT_VERSION",
        "SERVICE_HOST_AUTHORITY_ID_ENV",
        "SERVICE_HOST_GENERATION_ID_ENV",
        "SERVICE_HOST_LIFECYCLE_CONTRACT_VERSION",
        "SERVICE_HOST_PACKAGE_ENV",
        "SERVICE_HOST_STARTUP_FAILURE_CONTRACT_VERSION",
        "SERVICE_HOST_STARTUP_FAILURE_PATH_ENV",
        "ServiceHostControlDecision",
        "ServiceHostAttachmentDecision",
        "ServiceHostAttachmentEvidence",
        "ServiceHostHealthStatus",
        "ServiceHostLifecycleEvidence",
        "ServiceHostLifecycleTransition",
        "ServiceHostLifecycleUpdate",
        "ServiceHostLifecycleUpdateBatch",
        "ServiceHostStartupFailureCause",
        "ServiceHostStartupFailureEvidence",
        "ServiceHostStartupPhase",
        "authorize_service_host_control",
        "authorize_service_host_attachment",
        "append_service_host_lifecycle_update",
        "classify_service_host_lifecycle",
        "new_service_host_generation_id",
        "observe_service_host_lifecycle_updates",
        "read_service_host_startup_failure",
        "service_host_authority_id",
        "service_host_attachment",
        "service_host_attachment_from_payload",
        "service_host_lifecycle_from_payload",
        "service_host_lifecycle_update_from_payload",
        "service_host_startup_failure_for_process_exit",
        "service_host_startup_failure_from_exception",
        "service_host_startup_failure_from_payload",
        "service_host_startup_failure_with_process_exit",
        "write_service_host_startup_failure",
        "write_service_host_startup_failure_from_environment",
    ),
    ".service_api_dependency_routes": (
        "ServiceApiDependencyRouteDescriptor",
        "ServiceApiDependencyRouteKind",
        "ServiceApiRouteAuthority",
        "ServiceApiRouteAuthoritySelector",
        "service_api_dependency_routes_from_payload",
        "service_api_dependency_routes_to_payload",
    ),
    ".service_api_dependency_resolution": (
        "HostedServiceRuntimeLike",
        "RemoteHostedServiceRuntimeLike",
        "RemoteServiceApiProviderRuntime",
        "ServiceApiDependencyAuthoritySelectorError",
        "ServiceApiDependencyDuplicateProviderError",
        "ServiceApiDependencyMissingProviderError",
        "ServiceApiDependencyProviderRuntimeError",
        "ServiceApiDependencyResolutionError",
        "ServiceApiPackageBridgeLike",
        "ServiceApiProviderRuntime",
        "ServicePackageLike",
        "resolve_local_service_api_dependency_routes",
        "resolve_service_api_dependency_routes",
    ),
    ".service_api_dependency_installation": (
        "ServiceApiDependencyRouteInstallationError",
        "ServiceHostLifecycleActivationError",
        "ServiceHostControlClientLike",
        "activate_service_host_lifecycles",
        "activate_service_host_lifecycles_for_endpoint",
        "install_service_api_dependency_routes",
        "install_service_api_dependency_routes_for_endpoint",
        "install_service_api_dependency_routes_for_socket",
    ),
    ".view_provider_routes": (
        "ServiceViewProviderRouteDescriptor",
        "ServiceViewProviderRouteResolutionError",
        "build_service_view_provider_routes",
        "require_service_view_provider_route",
        "resolve_service_view_provider_route",
    ),
    ".service_provider_sets": (
        "SERVICE_API_PROVIDER_SET_CONTRACT_VERSION",
        "ServiceApiProviderRef",
        "ServiceApiProviderSet",
        "load_service_api_provider_set",
        "load_service_api_provider_sets",
        "service_api_provider_refs_from_payload",
        "service_api_provider_refs_from_provider_sets",
        "service_api_provider_refs_to_json",
        "service_api_provider_refs_to_payload",
        "write_service_api_provider_set",
    ),
    ".host": ("ServiceRuntimeHost",),
    ".router": ("ServiceOperationRouter", "UnsupportedServiceError"),
    ".stream_controller": ("InMemoryServiceStreamController",),
}

_EXPORT_TO_MODULE: dict[str, str] = {
    export_name: module_name
    for module_name, export_names in _MODULE_EXPORTS.items()
    for export_name in export_names
}

__all__ = [
    "dump_service_duplex_payload",
    "build_service_host_duplex_client_from_env",
    "JsonValue",
    "LocalServiceHostApiConfig",
    "LocalServiceHostAwareApiClient",
    "RemoteNodeApiEndpointConfig",
    "RemoteNodeAwareApiClient",
    "InMemoryServiceStreamController",
    "MetaTemporalGraphRoute",
    "ResolvedServiceApiDispatch",
    "ResolvedServiceApiDispatchCandidate",
    "ServiceApiGraphExecutionBinding",
    "ServiceApiGraphExecutionPlan",
    "build_service_api_graph_execution_plan",
    "build_service_view_provider_routes",
    "ActivateServiceHostLifecyclesHostControlRequest",
    "ActivateServiceHostLifecyclesHostControlResponse",
    "activate_service_host_lifecycles",
    "activate_service_host_lifecycles_for_endpoint",
    "coerce_request_status",
    "build_service_api_client_for_api_package",
    "build_service_api_client_for_route",
    "build_local_service_host_api_client_for_route",
    "build_local_service_host_duplex_client_factory_for_route",
    "build_remote_node_api_client_for_route",
    "ConfigureServiceApiDependencyRoutesHostControlRequest",
    "ConfigureServiceApiDependencyRoutesHostControlResponse",
    "HostedServiceRuntimeLike",
    "RemoteHostedServiceRuntimeLike",
    "RemoteServiceApiProviderRuntime",
    "RequestStatus",
    "require_single_service_api_dispatch_candidate",
    "resolve_local_service_api_dependency_routes",
    "resolve_service_api_dependency_routes",
    "resolve_service_api_dispatch",
    "service_api_dependency_routes_from_payload",
    "service_api_dependency_routes_to_payload",
    "service_api_provider_refs_from_payload",
    "service_api_provider_refs_from_provider_sets",
    "service_api_provider_refs_to_json",
    "service_api_provider_refs_to_payload",
    "ServiceApiDependencyRouteDescriptor",
    "ServiceApiDependencyRouteKind",
    "ServiceApiDependencyAuthoritySelectorError",
    "ServiceApiDependencyDuplicateProviderError",
    "ServiceApiDependencyMissingProviderError",
    "ServiceApiDependencyProviderRuntimeError",
    "ServiceApiDependencyResolutionError",
    "ServiceApiDependencyRouteInstallationError",
    "ServiceHostLifecycleActivationError",
    "ServiceApiPackageBridgeLike",
    "ServiceApiProviderRuntime",
    "SERVICE_API_PROVIDER_SET_CONTRACT_VERSION",
    "ServiceApiProviderRef",
    "ServiceApiProviderSet",
    "ServiceApiRouteAuthority",
    "ServiceApiRouteAuthoritySelector",
    "ServiceGraphContextProvider",
    "ServiceGraphGateway",
    "ServiceHostControlRequest",
    "ServiceHostControlResponse",
    "ServiceHostControlClientLike",
    "SERVICE_HOST_ATTACHMENT_CONTRACT_VERSION",
    "SERVICE_HOST_LIFECYCLE_UPDATE_CONTRACT_VERSION",
    "SERVICE_HOST_LIFECYCLE_UPDATE_JOURNAL_CONTRACT_VERSION",
    "SERVICE_HOST_AUTHORITY_ID_ENV",
    "SERVICE_HOST_GENERATION_ID_ENV",
    "SERVICE_HOST_LIFECYCLE_CONTRACT_VERSION",
    "SERVICE_HOST_PACKAGE_ENV",
    "SERVICE_HOST_STARTUP_FAILURE_CONTRACT_VERSION",
    "SERVICE_HOST_STARTUP_FAILURE_PATH_ENV",
    "ServiceHostControlDecision",
    "ServiceHostAttachmentDecision",
    "ServiceHostAttachmentEvidence",
    "ServiceHostHealthStatus",
    "ServiceHostLifecycleEvidence",
    "ServiceHostLifecycleTransition",
    "ServiceHostLifecycleUpdate",
    "ServiceHostLifecycleUpdateBatch",
    "ServiceHostStartupFailureCause",
    "ServiceHostStartupFailureEvidence",
    "ServiceHostStartupPhase",
    "ServiceLaneSubscriptionBinding",
    "ServiceDuplexHostControlRequest",
    "ServiceDuplexHostControlResponse",
    "ServiceDuplexLaneCommitReceiptNotification",
    "ServiceDuplexOperationContext",
    "ServiceDuplexOperationRequest",
    "ServiceDuplexOperationResponse",
    "ServiceDuplexStreamControlRequest",
    "ServiceDuplexStreamControlResponse",
    "ServiceDuplexStreamEventEnvelope",
    "ServiceDuplexStreamEvent",
    "ServiceDuplexStreamEventKind",
    "ServiceDuplexStreamSession",
    "service_duplex_operation_response_payload_from_contract",
    "service_duplex_trusted_json_payload",
    "ServiceHostDuplexClient",
    "ServiceHostDuplexRequestHandle",
    "ServiceHostTransport",
    "ServiceOperationContext",
    "ServiceOperationHandler",
    "ServiceOperationInvocation",
    "ServiceOperationInvocationHandler",
    "ServiceOperationPluginHandler",
    "ServiceOperationRequest",
    "ServiceOperationResponse",
    "ServiceOperationResult",
    "ServiceOperationRouter",
    "ServiceOperationTransport",
    "ServicePackageLike",
    "ServiceRuntimeHost",
    "ServiceStreamControlKind",
    "ServiceStreamControlRequest",
    "ServiceStreamControlResponse",
    "ServiceStreamEventEnvelope",
    "ServiceStreamEventKind",
    "ServiceStreamPublisher",
    "ServiceStreamSession",
    "ServiceStreamSubscriber",
    "ServiceViewProviderRouteDescriptor",
    "ServiceViewProviderRouteResolutionError",
    "StreamLifecycle",
    "UnsupportedServiceError",
    "load_service_api_provider_set",
    "load_service_api_provider_sets",
    "install_service_api_dependency_routes",
    "install_service_api_dependency_routes_for_endpoint",
    "install_service_api_dependency_routes_for_socket",
    "require_service_view_provider_route",
    "read_service_host_startup_failure",
    "observe_service_host_lifecycle_updates",
    "resolve_service_view_provider_route",
    "service_host_authority_id",
    "service_host_attachment",
    "service_host_attachment_from_payload",
    "service_host_lifecycle_from_payload",
    "service_host_lifecycle_update_from_payload",
    "service_host_startup_failure_for_process_exit",
    "service_host_startup_failure_from_exception",
    "service_host_startup_failure_from_payload",
    "service_host_startup_failure_with_process_exit",
    "authorize_service_host_control",
    "authorize_service_host_attachment",
    "append_service_host_lifecycle_update",
    "classify_service_host_lifecycle",
    "new_service_host_generation_id",
    "write_service_host_startup_failure",
    "write_service_host_startup_failure_from_environment",
    "write_service_api_provider_set",
]

if TYPE_CHECKING:
    from aware_service_runtime.api_ingress import (
        ResolvedServiceApiDispatch,
        ResolvedServiceApiDispatchCandidate,
        ServiceApiGraphExecutionBinding,
        ServiceApiGraphExecutionPlan,
        build_service_api_graph_execution_plan,
        require_single_service_api_dispatch_candidate,
        resolve_service_api_dispatch,
    )
    from aware_service_runtime.contracts import (
        ActivateServiceHostLifecyclesHostControlRequest,
        ActivateServiceHostLifecyclesHostControlResponse,
        coerce_request_status,
        ConfigureServiceApiDependencyRoutesHostControlRequest,
        ConfigureServiceApiDependencyRoutesHostControlResponse,
        RequestStatus,
        ServiceGraphContextProvider,
        ServiceGraphGateway,
        ServiceHostControlRequest,
        ServiceHostControlResponse,
        ServiceHostTransport,
        ServiceLaneSubscriptionBinding,
        ServiceOperationContext,
        ServiceOperationHandler,
        ServiceOperationInvocation,
        ServiceOperationInvocationHandler,
        ServiceOperationPluginHandler,
        ServiceOperationRequest,
        ServiceOperationResponse,
        ServiceOperationResult,
        ServiceOperationTransport,
        ServiceStreamControlKind,
        ServiceStreamControlRequest,
        ServiceStreamControlResponse,
        ServiceStreamEventEnvelope,
        ServiceStreamEventKind,
        ServiceStreamPublisher,
        ServiceStreamSession,
        ServiceStreamSubscriber,
        StreamLifecycle,
    )
    from aware_service_runtime.duplex import (
        JsonValue,
        ServiceDuplexHostControlRequest,
        ServiceDuplexHostControlResponse,
        ServiceDuplexLaneCommitReceiptNotification,
        ServiceDuplexOperationContext,
        ServiceDuplexOperationRequest,
        ServiceDuplexOperationResponse,
        ServiceDuplexStreamControlRequest,
        ServiceDuplexStreamControlResponse,
        ServiceDuplexStreamEvent,
        ServiceDuplexStreamEventEnvelope,
        ServiceDuplexStreamEventKind,
        ServiceDuplexStreamSession,
        dump_service_duplex_payload,
        service_duplex_operation_response_payload_from_contract,
        service_duplex_trusted_json_payload,
    )
    from aware_service_runtime.duplex_client import (
        build_service_host_duplex_client_from_env,
        ServiceHostDuplexClient,
        ServiceHostDuplexRequestHandle,
    )
    from aware_service_runtime.local_service_host_api_client import (
        build_remote_node_api_client_for_route,
        build_service_api_client_for_api_package,
        build_service_api_client_for_route,
        build_local_service_host_api_client_for_route,
        build_local_service_host_duplex_client_factory_for_route,
        LocalServiceHostApiConfig,
        LocalServiceHostAwareApiClient,
        RemoteNodeApiEndpointConfig,
        RemoteNodeAwareApiClient,
    )
    from aware_service_runtime.service_api_dependency_routes import (
        service_api_dependency_routes_from_payload,
        service_api_dependency_routes_to_payload,
        ServiceApiDependencyRouteDescriptor,
        ServiceApiDependencyRouteKind,
        ServiceApiRouteAuthority,
        ServiceApiRouteAuthoritySelector,
    )
    from aware_service_runtime.service_api_dependency_resolution import (
        HostedServiceRuntimeLike,
        RemoteHostedServiceRuntimeLike,
        RemoteServiceApiProviderRuntime,
        ServiceApiDependencyAuthoritySelectorError,
        ServiceApiDependencyDuplicateProviderError,
        ServiceApiDependencyMissingProviderError,
        ServiceApiDependencyProviderRuntimeError,
        ServiceApiDependencyResolutionError,
        ServiceApiPackageBridgeLike,
        ServiceApiProviderRuntime,
        ServicePackageLike,
        resolve_local_service_api_dependency_routes,
        resolve_service_api_dependency_routes,
    )
    from aware_service_runtime.service_api_dependency_installation import (
        ServiceApiDependencyRouteInstallationError,
        ServiceHostLifecycleActivationError,
        ServiceHostControlClientLike,
        activate_service_host_lifecycles,
        activate_service_host_lifecycles_for_endpoint,
        install_service_api_dependency_routes,
        install_service_api_dependency_routes_for_endpoint,
        install_service_api_dependency_routes_for_socket,
    )
    from aware_service_runtime.view_provider_routes import (
        ServiceViewProviderRouteDescriptor,
        ServiceViewProviderRouteResolutionError,
        build_service_view_provider_routes,
        require_service_view_provider_route,
        resolve_service_view_provider_route,
    )
    from aware_service_runtime.service_provider_sets import (
        SERVICE_API_PROVIDER_SET_CONTRACT_VERSION,
        ServiceApiProviderRef,
        ServiceApiProviderSet,
        load_service_api_provider_set,
        load_service_api_provider_sets,
        service_api_provider_refs_from_payload,
        service_api_provider_refs_from_provider_sets,
        service_api_provider_refs_to_json,
        service_api_provider_refs_to_payload,
        write_service_api_provider_set,
    )
    from aware_service_runtime.host import ServiceRuntimeHost
    from aware_service_runtime.router import (
        ServiceOperationRouter,
        UnsupportedServiceError,
    )
    from aware_service_runtime.stream_controller import (
        InMemoryServiceStreamController,
    )


def __getattr__(name: str) -> object:
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
