from __future__ import annotations

from aware_code.language_service_capability_contract import (
    build_language_service_capability_metadata_from_semantic_contract,
)
from aware_service_runtime.semantic_contract import (
    AWARE_SERVICE_SEMANTIC_CONTRACT,
    SERVICE_API_OWNER,
    SERVICE_CAPABILITY_BUNDLES,
    SERVICE_CAPABILITY_PARTICIPATION,
    SERVICE_CAPABILITY_PROFILES,
    SERVICE_DIAGNOSTICS_CAPABILITY_PARTICIPATION,
    SERVICE_DIAGNOSTICS_CAPABILITY_PROFILES,
    SERVICE_ENDPOINT_OWNER,
    SERVICE_EXPERIENCE_OWNER,
    SERVICE_OPERATION_OWNER,
    SERVICE_PROJECTION_OWNER,
    SERVICE_ROOT_OWNER,
    SERVICE_SEMANTIC_SCOPE_KEYS,
    SERVICE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION,
    SERVICE_SEMANTIC_TOKENS_CAPABILITY_PROFILES,
)

SERVICE_CAPABILITY_METADATA = build_language_service_capability_metadata_from_semantic_contract(
    AWARE_SERVICE_SEMANTIC_CONTRACT
)

SERVICE_DIAGNOSTICS_CAPABILITY_METADATA = tuple(
    item for item in SERVICE_CAPABILITY_METADATA if item.capability == "diagnostics"
)

SERVICE_SEMANTIC_TOKENS_CAPABILITY_METADATA = tuple(
    item for item in SERVICE_CAPABILITY_METADATA if item.capability == "semantic_tokens"
)

__all__ = [
    "SERVICE_API_OWNER",
    "SERVICE_CAPABILITY_METADATA",
    "SERVICE_CAPABILITY_BUNDLES",
    "SERVICE_CAPABILITY_PARTICIPATION",
    "SERVICE_CAPABILITY_PROFILES",
    "SERVICE_DIAGNOSTICS_CAPABILITY_METADATA",
    "SERVICE_DIAGNOSTICS_CAPABILITY_PROFILES",
    "SERVICE_DIAGNOSTICS_CAPABILITY_PARTICIPATION",
    "SERVICE_EXPERIENCE_OWNER",
    "SERVICE_ENDPOINT_OWNER",
    "SERVICE_OPERATION_OWNER",
    "SERVICE_PROJECTION_OWNER",
    "SERVICE_ROOT_OWNER",
    "SERVICE_SEMANTIC_SCOPE_KEYS",
    "SERVICE_SEMANTIC_TOKENS_CAPABILITY_METADATA",
    "SERVICE_SEMANTIC_TOKENS_CAPABILITY_PROFILES",
    "SERVICE_SEMANTIC_TOKENS_CAPABILITY_PARTICIPATION",
]
