# This file is generated by AWARE. Do not edit.
from __future__ import annotations

# Standard
from importlib import import_module
from typing import cast
from uuid import UUID

# Third-party
from aware_code.types import JsonArray, JsonObject
from aware_meta.graph.instance.builder import build_object_instance_graph
from aware_meta.graph.instance.diff_orm import build_object_instance_graph_changes_from_orm_change_set
from aware_meta.runtime.handler_executor.argument_coercion import coerce_meta_handler_call_kwargs
from aware_meta.runtime.handler_executor.contracts import MetaGraphHandlerExecutionRequest, MetaGraphPreState
from aware_meta.runtime.handler_executor.language_handler import (
    MetaGraphGeneratedInvocationHandlerCallable,
    MetaGraphGeneratedLanguageHandlerCallable,
    MetaGraphGeneratedLanguageHandlerKey,
    MetaGraphLanguageHandlerExecution,
    MetaGraphLanguageHandlerExecutionError,
)
from aware_meta.runtime.handler_executor.pre_state import (
    MetaGraphEmptyLaneBootstrap,
    MetaGraphEmptyLaneBootstrapCallable,
)
from aware_meta.runtime.oig_model_reifier import reify_oig_root_model
from aware_meta.runtime.value_resolvers import default_meta_enum_option_resolver
from aware_meta_ontology.class_.class_config import ClassConfig
from aware_meta_ontology.graph.instance.object_instance_graph import ObjectInstanceGraph
from pydantic import BaseModel

# Orm
from aware_orm.models.orm_model import ORMModel
from aware_orm.registry import ORMModelRegistry
from aware_orm.session.change_collector import current_change_collector

# Storage Ontology
from aware_storage_ontology.blob.storage_blob import StorageBlob
from aware_storage_ontology.bucket.storage_bucket import StorageBucket
from aware_storage_ontology.bucket.storage_bucket_enums import StorageBackend
from aware_storage_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID


def _bind_keyword_payload(
    *,
    positional: JsonArray,
    keyword: JsonObject,
    field_names: tuple[str, ...],
    function_name: str,
) -> JsonObject:
    if len(positional) > len(field_names):
        raise MetaGraphLanguageHandlerExecutionError(
            "Too many positional arguments for generated Meta language handler: "
            f"function_name={function_name} have={len(positional)} max={len(field_names)}"
        )
    payload = JsonObject(dict(keyword))
    unknown_names = sorted(set(payload) - set(field_names))
    if unknown_names:
        raise MetaGraphLanguageHandlerExecutionError(
            "Unknown generated Meta language-handler argument(s): "
            f"function_name={function_name} names={unknown_names}"
        )
    for position, value in enumerate(positional):
        field_name = field_names[position]
        if field_name in payload:
            raise MetaGraphLanguageHandlerExecutionError(
                "Generated Meta language-handler argument provided twice: "
                f"function_name={function_name} name={field_name}"
            )
        payload[field_name] = value
    return payload


def _assert_constructor_owner_class(*, request: MetaGraphHandlerExecutionRequest, expected_class_name: str) -> None:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )


def _post_oig_with_root_model(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    root_model: ORMModel,
) -> ObjectInstanceGraph:
    before_oig = pre_state.before_oig
    return build_object_instance_graph(
        root_instance=root_model,
        object_config_graph=request.execution_plan.index.ocg,
        object_projection_graph=request.execution_plan.object_projection_graph,
        key=before_oig.key or str(before_oig.id),
        name=before_oig.name or request.execution_plan.object_projection_graph.name,
        description=before_oig.description or "",
        oig_id=before_oig.id,
        enum_option_resolver=default_meta_enum_option_resolver,
    )


def _changes_from_current_collector(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
):
    collector = current_change_collector()
    if collector is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires an active ORM change collector."
        )
    change_set = collector.snapshot()
    changes = tuple(
        build_object_instance_graph_changes_from_orm_change_set(
            before_oig=pre_state.before_oig,
            object_instance_graph_identity_id=(request.staged_call.lane_scope.object_instance_graph_identity_id),
            ocg=request.execution_plan.index.ocg,
            opg=request.execution_plan.object_projection_graph,
            change_set=change_set,
            class_configs_by_id=dict(request.execution_plan.index.class_configs_by_id),
            relationships_by_id=dict(request.execution_plan.index.relationships_by_id),
            enum_option_resolver=default_meta_enum_option_resolver,
        )
    )
    constructed_class_instance_ids = tuple(
        class_change.class_instance_id
        for root_change in changes
        for class_change in root_change.class_instance_changes
        if class_change.change.type.value == "create"
    )
    return changes, constructed_class_instance_ids


def _root_and_target_models_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    expected_class_name: str,
) -> tuple[ORMModel, ORMModel]:
    owner_class_config = request.execution_plan.implementation.owner_class_config
    if not isinstance(owner_class_config, ClassConfig):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler requires a resolved owner ClassConfig."
        )
    if owner_class_config.name != expected_class_name:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler owner mismatch: "
            f"expected={expected_class_name} got={owner_class_config.name}"
        )
    target_object_id = (
        pre_state.target_object_id
        or request.execution_plan.target_object_id
        or request.request.target_object_id
        or pre_state.root_object_id
    )
    if target_object_id is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta instance handler requires a target object id.")
    root_model = _root_model_from_pre_state(request=request, pre_state=pre_state)
    target_source_object_id = _target_source_object_id_from_pre_state(
        pre_state=pre_state,
        target_class_instance_id=target_object_id,
    )
    target = _find_orm_model_by_id(root_model, target_source_object_id)
    target_orm_class = ORMModelRegistry.get_class_by_class_config_id(owner_class_config.id)
    if target_orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve ORM class: "
            f"class_config_id={owner_class_config.id} class_name={owner_class_config.name}"
        )
    if not isinstance(target, target_orm_class):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot resolve target model in "
            "the rooted projection model: "
            f"class_name={owner_class_config.name} target_object_id={target_object_id}"
        )
    return root_model, target


def _root_model_from_pre_state(
    *,
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
) -> ORMModel:
    root_orm_class = _root_orm_class_from_projection(request)
    root_object_id = _root_source_object_id_from_pre_state(pre_state)
    root = reify_oig_root_model(
        index=request.execution_plan.index,
        opg=request.execution_plan.object_projection_graph,
        oig=pre_state.before_oig,
        model_type=root_orm_class,
        root_id=root_object_id,
        branch_id=request.execution_plan.staged_call.lane_scope.domain_branch_id,
    )
    if root is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta instance handler cannot reify rooted projection model: " f"root_object_id={root_object_id}"
        )
    return root


def _root_orm_class_from_projection(
    request: MetaGraphHandlerExecutionRequest,
) -> type[ORMModel]:
    root_nodes = [
        node for node in request.execution_plan.object_projection_graph.object_projection_graph_nodes if node.is_root
    ]
    if len(root_nodes) != 1:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler requires exactly one OPG root node: "
            f"have={len(root_nodes)} "
            f"object_projection_graph_id={request.execution_plan.object_projection_graph.id}"
        )
    orm_class = ORMModelRegistry.get_class_by_class_config_id(root_nodes[0].class_config_id)
    if orm_class is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve root ORM class: " f"class_config_id={root_nodes[0].class_config_id}"
        )
    return cast(type[ORMModel], orm_class)


def _root_source_object_id_from_pre_state(pre_state: MetaGraphPreState):
    if pre_state.root_object_id is not None:
        return pre_state.root_object_id
    root_class_instance = pre_state.before_oig.root_class_instance
    if root_class_instance is None and pre_state.before_oig.root_class_instance_id is not None:
        root_class_instance = next(
            (
                instance
                for instance in pre_state.before_oig.class_instances
                if instance.id == pre_state.before_oig.root_class_instance_id
            ),
            None,
        )
    if root_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler cannot resolve root source object id.")
    return root_class_instance.source_object_id


def _target_source_object_id_from_pre_state(
    *,
    pre_state: MetaGraphPreState,
    target_class_instance_id,
):
    if pre_state.oig_index is None:
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta handler requires pre-state OIG index.")
    target_class_instance = pre_state.oig_index.class_instances_by_id.get(target_class_instance_id)
    if target_class_instance is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta handler cannot resolve target class instance: "
            f"target_class_instance_id={target_class_instance_id}"
        )
    return target_class_instance.source_object_id


def _find_orm_model_by_id(root_model: ORMModel, object_id) -> ORMModel | None:
    stack: list[object] = [root_model]
    seen: set[int] = set()
    while stack:
        current = stack.pop()
        identity = id(current)
        if identity in seen:
            continue
        seen.add(identity)
        if isinstance(current, ORMModel):
            if current.id == object_id:
                return current
            stack.extend(current.__dict__.values())
            continue
        if isinstance(current, (list, tuple, set)):
            stack.extend(current)
            continue
        if isinstance(current, dict):
            stack.extend(current.values())
    return None


def _constructed_class_instance_ids_from_post_oig(
    *,
    pre_state: MetaGraphPreState,
    post_oig: ObjectInstanceGraph,
) -> tuple:
    before_ids = {instance.id for instance in pre_state.before_oig.class_instances}
    return tuple(instance.id for instance in post_oig.class_instances if instance.id not in before_ids)


def _json_payload_value(value: object) -> object:
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    if isinstance(value, tuple):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, list):
        return [_json_payload_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_payload_value(item) for key, item in value.items()}
    return value


def _bind_storage_blob__create(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("sha", "mime_type", "size_bytes"),
        function_name="create",
    )


async def _call_storage_blob__create(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_storage.handlers.impl.blob.storage_blob import create as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_storage_blob__create(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_storage_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    sha = bound_input.get("sha")
    mime_type = bound_input.get("mime_type")
    size_bytes = bound_input.get("size_bytes")
    _aware_self_values = {"sha": sha, "mime_type": mime_type, "size_bytes": size_bytes}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("20ce9a91-cb0a-5517-b919-e9256e5c4fa8")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: StorageBlob.create"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: StorageBlob.create"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_storage_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


def _bind_storage_bucket__build(*, positional: JsonArray, keyword: JsonObject) -> JsonObject:
    return _bind_keyword_payload(
        positional=positional,
        keyword=keyword,
        field_names=("name", "backend", "allowed_mime_types", "config"),
        function_name="build",
    )


async def _call_storage_bucket__build(*, bound_input: JsonObject, target: ORMModel | None = None) -> ORMModel:
    from aware_storage.handlers.impl.bucket.storage_bucket import build as _impl

    call_kwargs = coerce_meta_handler_call_kwargs(_impl, dict(bound_input))
    result = await _impl(**call_kwargs)
    return cast(ORMModel, result)


def _root_id_storage_bucket__build(*, request: MetaGraphHandlerExecutionRequest, bound_input: JsonObject):
    from importlib import import_module
    from aware_storage_ontology.stable_ids import CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID

    name = bound_input.get("name")
    backend = bound_input.get("backend")
    if backend is None:
        backend = "local"
    allowed_mime_types = bound_input.get("allowed_mime_types")
    if allowed_mime_types is None:
        allowed_mime_types = []
    config = bound_input.get("config")
    if config is None:
        config = None
    _aware_self_values = {"name": name, "backend": backend, "allowed_mime_types": allowed_mime_types, "config": config}
    _aware_self_binding = CONSTRUCTOR_STABLE_ID_BINDINGS_BY_CLASS_CONFIG_ID.get("972c654a-5d48-54f4-9a67-974fac6f96d1")
    if _aware_self_binding is None:
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor bootstrap cannot resolve stable-id binding: StorageBucket.build"
        )
    _aware_self_fn, _aware_self_key_names = _aware_self_binding
    _aware_missing_self_keys = [
        key for key in _aware_self_key_names if key not in _aware_self_values or _aware_self_values[key] is None
    ]
    if _aware_missing_self_keys:
        raise MetaGraphLanguageHandlerExecutionError(
            "Missing stable-id input for generated Meta constructor bootstrap: StorageBucket.build"
            + f": {_aware_missing_self_keys}"
        )
    _aware_self_stable_values = {
        key: getattr(_aware_self_values[key], "value", _aware_self_values[key]) for key in _aware_self_key_names
    }
    return getattr(import_module("aware_storage_ontology.stable_ids"), _aware_self_fn)(**_aware_self_stable_values)


async def storage_blob__create__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_storage_blob__create(positional=positional, keyword=keyword)
    result = await _call_storage_blob__create(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="StorageBlob")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def storage_blob__create__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_storage_blob__create(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_storage_blob__create(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="StorageBlob",
        description="Meta constructor bootstrap for StorageBlob.",
    )


async def storage_bucket__build__handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    positional: JsonArray,
    keyword: JsonObject,
) -> MetaGraphLanguageHandlerExecution:
    bound_input = _bind_storage_bucket__build(positional=positional, keyword=keyword)
    result = await _call_storage_bucket__build(bound_input=bound_input)
    if not isinstance(result, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError("Generated Meta constructor handler must return ORMModel.")
    _assert_constructor_owner_class(request=request, expected_class_name="StorageBucket")
    root_object_id = pre_state.root_object_id
    if isinstance(root_object_id, UUID):
        result.id = root_object_id
    post_oig = _post_oig_with_root_model(
        request=request,
        pre_state=pre_state,
        root_model=result,
    )
    return MetaGraphLanguageHandlerExecution(
        success=True,
        payload=JsonObject({"value": _json_payload_value(result)}),
        post_oig=post_oig,
        root_object_id=result.id,
        root_class_instance_identity_id=pre_state.root_class_instance_identity_id,
        constructed_class_instance_ids=_constructed_class_instance_ids_from_post_oig(
            pre_state=pre_state,
            post_oig=post_oig,
        ),
    )


def storage_bucket__build__empty_lane_bootstrap(
    request: MetaGraphHandlerExecutionRequest,
) -> MetaGraphEmptyLaneBootstrap:
    bound_input = _bind_storage_bucket__build(
        positional=JsonArray(list(request.request.args)),
        keyword=JsonObject(dict(request.request.kwargs)),
    )
    root_object_id = _root_id_storage_bucket__build(request=request, bound_input=bound_input)
    return MetaGraphEmptyLaneBootstrap(
        root_object_id=root_object_id,
        name="StorageBucket",
        description="Meta constructor bootstrap for StorageBucket.",
    )


async def storage_blob__create__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_storage_blob__create(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_storage_blob__create(bound_input=bound_input)


async def storage_bucket__build__invocation_handler(
    request: MetaGraphHandlerExecutionRequest,
    pre_state: MetaGraphPreState,
    target: ORMModel | type[ORMModel],
    positional: JsonArray,
    keyword: JsonObject,
) -> object:
    _ = request, pre_state
    bound_input = _bind_storage_bucket__build(positional=positional, keyword=keyword)
    if not isinstance(target, type) or not issubclass(target, ORMModel):
        raise MetaGraphLanguageHandlerExecutionError(
            "Generated Meta constructor invocation requires ORMModel class target."
        )
    return await _call_storage_bucket__build(bound_input=bound_input)


AWARE_META_GRAPH_HANDLERS: dict[MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedLanguageHandlerCallable] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.blob.StorageBlob",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_storage.blob.StorageBlob",
        owner_class_name="StorageBlob",
    ): storage_blob__create__handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.bucket.StorageBucket",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_storage.bucket.StorageBucket",
        owner_class_name="StorageBucket",
    ): storage_bucket__build__handler,
}

AWARE_META_GRAPH_INVOCATION_HANDLERS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphGeneratedInvocationHandlerCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.blob.StorageBlob",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_storage.blob.StorageBlob",
        owner_class_name="StorageBlob",
    ): storage_blob__create__invocation_handler,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.bucket.StorageBucket",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_storage.bucket.StorageBucket",
        owner_class_name="StorageBucket",
    ): storage_bucket__build__invocation_handler,
}

AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS: dict[
    MetaGraphGeneratedLanguageHandlerKey, MetaGraphEmptyLaneBootstrapCallable
] = {
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.blob.StorageBlob",
        function_name="create",
        is_constructor=True,
        owner_class_fqn="aware_storage.blob.StorageBlob",
        owner_class_name="StorageBlob",
    ): storage_blob__create__empty_lane_bootstrap,
    MetaGraphGeneratedLanguageHandlerKey(
        owner_key="aware_storage.bucket.StorageBucket",
        function_name="build",
        is_constructor=True,
        owner_class_fqn="aware_storage.bucket.StorageBucket",
        owner_class_name="StorageBucket",
    ): storage_bucket__build__empty_lane_bootstrap,
}

__all__ = [
    "AWARE_META_GRAPH_EMPTY_LANE_BOOTSTRAPS",
    "AWARE_META_GRAPH_HANDLERS",
    "AWARE_META_GRAPH_INVOCATION_HANDLERS",
]
