// Generated by aware_interface compile. Do not edit manually.

import 'package:aware_shell/aware_shell.dart';
import 'package:aware_pane_runtime/aware_pane_runtime.dart';
import 'package:aware_hub_package_selector_pane/aware_hub_package_selector_pane.dart' as aware_hub_package_selector_pane;
import 'package:aware_network_territory_pane/aware_network_territory_pane.dart' as aware_network_territory_pane;
import 'package:aware_content_render_components/aware_content_render_components.dart' as aware_content_render_components;
import 'package:aware_hub_service_api/aware_hub_service_api.dart' as aware_hub_service_api;
import 'package:aware_network_service_api/aware_network_service_api.dart' as aware_network_service_api;

void registerPanePackages(PanePackageRegistry registry) {
  aware_hub_package_selector_pane.registerPanePackage(registry);
  aware_network_territory_pane.registerPanePackage(registry);
}

void registerRenderComponents(RenderComponentRegistryBuilder registry) {
  aware_content_render_components.registerRenderComponents(registry);
}

InterfacePackageRuntime buildInterfacePackageRuntime() {
  final panePackageRegistry = PanePackageRegistry();
  final renderComponentRegistryBuilder = RenderComponentRegistryBuilder();
  registerPanePackages(panePackageRegistry);
  registerRenderComponents(renderComponentRegistryBuilder);
  return InterfacePackageRuntime(
    interfacePackageId: 'f6453e34-de79-5952-8581-eb671225f518',
    interfacePackageName: 'aware-control-interface',
    experienceKeys: const <String>[
      'aware_control',
      'aware_control_identity',
      'aware_hub',
      'aware_network',
    ],
    layouts: const <InterfacePackageRuntimeLayout>[
      InterfacePackageRuntimeLayout(layoutConfigId: 'b21adb2d-5b6e-5b6d-a773-73214ea1676e', layoutKey: 'coordination_center', label: 'Coordination Center', isDefault: true),
    ],
    sectionRepresentations: const <InterfacePackageRuntimeSectionRepresentation>[
      InterfacePackageRuntimeSectionRepresentation(representationId: 'd3d3e119-83c9-5bad-b76b-f864cd8cfcda', windowKey: 'main', layoutKey: 'coordination_center', sectionKey: 'inspector', paneName: 'network_territory', paneKind: 'network_territory', label: 'Territory', observableId: '22cac6c1-303f-58a7-b407-693ed6d96f3c', viewRef: 'aware_network.territory.discovery.v1', projectionViewKey: 'territory.discovery.v1', ),
      InterfacePackageRuntimeSectionRepresentation(representationId: 'cd452f5c-c142-5042-81c8-15978d9900b5', windowKey: 'main', layoutKey: 'coordination_center', sectionKey: 'orchestration', paneName: 'identity_admission', paneKind: 'identity_admission', label: 'Identity', observableId: '43abb1c1-cc28-542f-b4af-ff0825b5e929', viewRef: 'aware_control_identity.identity.admission.v1', projectionViewKey: 'identity.admission.v1', ),
      InterfacePackageRuntimeSectionRepresentation(representationId: '2af43b5b-81ec-5a8d-aaef-2a8d359aec2c', windowKey: 'main', layoutKey: 'coordination_center', sectionKey: 'primary', paneName: 'hub_package_selector', paneKind: 'hub_package_selector', label: 'Home', observableId: '1be1113f-c2d0-550a-b9fb-5f9ed6f362bd', viewRef: 'aware_hub.home.channel_heads.v1', projectionViewKey: 'home.channel_heads.v1', ),
    ],
    renderSpecs: <PaneRenderSpec>[
      PaneRenderSpec.fromJson(
        <String, dynamic>{
          "name": "identity_admission_default",
          "nodes": [
            {
              "node_key": "root",
              "node_kind": "column",
              "order": 0,
              "semantic_role": "pane",
              "style_tokens": [
                {
                  "token_key": "density",
                  "token_value": "comfortable"
                }
              ]
            },
            {
              "node_key": "header",
              "node_kind": "row",
              "order": 0,
              "parent_node_key": "root",
              "semantic_role": "heading",
              "style_tokens": [
                {
                  "token_key": "layout",
                  "token_value": "pane_header"
                },
                {
                  "token_key": "align",
                  "token_value": "center"
                }
              ]
            },
            {
              "node_key": "title",
              "node_kind": "text",
              "order": 0,
              "parent_node_key": "header",
              "semantic_role": "heading",
              "style_tokens": [
                {
                  "token_key": "typography",
                  "token_value": "pane_title"
                },
                {
                  "token_key": "align",
                  "token_value": "center"
                }
              ],
              "text": "Create your Aware identity"
            },
            {
              "node_key": "status",
              "node_kind": "status",
              "order": 1,
              "parent_node_key": "header",
              "semantic_role": "status",
              "state_bindings": [
                {
                  "binding_key": "status_text",
                  "fallback_value": "ready",
                  "json_path": "\$.status",
                  "state_attribute_config_id": "37d8ad22-f6b5-50f9-9bdc-5bd32d60e65d",
                  "state_attribute_ref": "status",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "status_tone",
                  "json_path": "\$.status_tone",
                  "state_attribute_config_id": "4c877fd5-fc1a-583d-9cd9-32961ab16767",
                  "state_attribute_ref": "status_tone",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "tone",
                  "transform": "text"
                }
              ]
            },
            {
              "node_key": "intro",
              "node_kind": "text",
              "order": 1,
              "parent_node_key": "root",
              "semantic_role": "paragraph",
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "muted"
                },
                {
                  "token_key": "align",
                  "token_value": "center"
                }
              ],
              "text": "Choose how this Interface presents you to humans, agents, and services."
            },
            {
              "node_key": "preview",
              "node_kind": "box",
              "order": 2,
              "parent_node_key": "root",
              "semantic_role": "section"
            },
            {
              "node_key": "preview.header",
              "node_kind": "section_header",
              "order": 0,
              "parent_node_key": "preview",
              "semantic_role": "heading",
              "text": "Public identity"
            },
            {
              "label": "Display name",
              "node_key": "preview.name",
              "node_kind": "field",
              "order": 1,
              "parent_node_key": "preview",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "display_name_text",
                  "fallback_value": "Choose a display name",
                  "json_path": "\$.display_name",
                  "state_attribute_config_id": "a1a3636a-3beb-5d25-a7d1-3eafc32eda33",
                  "state_attribute_ref": "display_name",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "text",
                  "transform": "text"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "display",
                  "token_value": "prose"
                }
              ]
            },
            {
              "label": "Public handle",
              "node_key": "preview.handle",
              "node_kind": "field",
              "order": 2,
              "parent_node_key": "preview",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "public_handle_text",
                  "fallback_value": "Choose a public handle",
                  "json_path": "\$.public_handle",
                  "state_attribute_config_id": "b45c90b1-6d7b-5d25-8688-d03919d2e920",
                  "state_attribute_ref": "public_handle",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "text",
                  "transform": "text"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "display",
                  "token_value": "identifier"
                }
              ]
            },
            {
              "node_key": "preview.bio_hint",
              "node_kind": "text",
              "order": 3,
              "parent_node_key": "preview",
              "semantic_role": "paragraph",
              "state_bindings": [
                {
                  "binding_key": "bio_visible",
                  "json_path": "\$.bio",
                  "state_attribute_config_id": "bbddcf33-8a5d-5325-aab9-6803b7a711cf",
                  "state_attribute_ref": "bio",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "visible",
                  "transform": "is_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "muted"
                }
              ],
              "text": "Add a short bio to make this identity recognizable across the network."
            },
            {
              "component_ref": "aware.content.markdown_viewer",
              "fallback_node_kind": "text",
              "fallback_text": "Bio preview",
              "node_key": "bio_preview",
              "node_kind": "component",
              "order": 4,
              "parent_node_key": "preview",
              "semantic_role": "paragraph",
              "state_bindings": [
                {
                  "binding_key": "bio_text",
                  "component_input_port_key": "markdown",
                  "json_path": "\$.bio",
                  "state_attribute_config_id": "bbddcf33-8a5d-5325-aab9-6803b7a711cf",
                  "state_attribute_ref": "bio",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "bio_visible",
                  "json_path": "\$.bio",
                  "state_attribute_config_id": "bbddcf33-8a5d-5325-aab9-6803b7a711cf",
                  "state_attribute_ref": "bio",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ]
            },
            {
              "node_key": "form",
              "node_kind": "box",
              "order": 3,
              "parent_node_key": "root",
              "semantic_role": "section"
            },
            {
              "node_key": "form.header",
              "node_kind": "section_header",
              "order": 0,
              "parent_node_key": "form",
              "semantic_role": "heading",
              "text": "Admission profile"
            },
            {
              "label": "Display name",
              "node_key": "display_name_input",
              "node_kind": "text_input",
              "order": 1,
              "parent_node_key": "form",
              "placeholder": "Luis Lechuga",
              "semantic_role": "input",
              "state_bindings": [
                {
                  "binding_key": "display_name_value",
                  "json_path": "\$.display_name",
                  "state_attribute_config_id": "a1a3636a-3beb-5d25-a7d1-3eafc32eda33",
                  "state_attribute_ref": "display_name",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "value",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Public handle",
              "node_key": "public_handle_input",
              "node_kind": "text_input",
              "order": 2,
              "parent_node_key": "form",
              "placeholder": "@luis",
              "semantic_role": "input",
              "state_bindings": [
                {
                  "binding_key": "public_handle_value",
                  "json_path": "\$.public_handle",
                  "state_attribute_config_id": "b45c90b1-6d7b-5d25-8688-d03919d2e920",
                  "state_attribute_ref": "public_handle",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "value",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Bio",
              "node_key": "bio_input",
              "node_kind": "text_input",
              "order": 3,
              "parent_node_key": "form",
              "placeholder": "Builder of Aware",
              "semantic_role": "input",
              "state_bindings": [
                {
                  "binding_key": "bio_value",
                  "json_path": "\$.bio",
                  "state_attribute_config_id": "bbddcf33-8a5d-5325-aab9-6803b7a711cf",
                  "state_attribute_ref": "bio",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "value",
                  "transform": "text"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "input",
                  "token_value": "multiline"
                }
              ]
            },
            {
              "node_key": "form.note",
              "node_kind": "text",
              "order": 4,
              "parent_node_key": "form",
              "semantic_role": "paragraph",
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "muted"
                }
              ],
              "text": "Markdown is supported. Keep it clear enough for humans and agents to recognize you."
            },
            {
              "node_key": "actions",
              "node_kind": "row",
              "order": 4,
              "parent_node_key": "root",
              "semantic_role": "action",
              "style_tokens": [
                {
                  "token_key": "layout",
                  "token_value": "metadata_bar"
                }
              ]
            },
            {
              "action_bindings": [
                {
                  "action_key": "admit_identity",
                  "action_kind": "api",
                  "binding_key": "admit_identity",
                  "endpoint_ref": "identity.signup_via_profile.signup_via_profile",
                  "event": "activate",
                  "input_bindings": [
                    {
                      "payload_path": "profile.display_name",
                      "source_node_key": "display_name_input"
                    },
                    {
                      "payload_path": "profile.public_handle",
                      "source_node_key": "public_handle_input"
                    },
                    {
                      "payload_path": "profile.bio",
                      "source_node_key": "bio_input"
                    }
                  ],
                  "label": "Admit identity",
                  "projection_experience_view_invocation_action_id": "c1b54c39-739f-5175-b12b-40b0e859653c",
                  "receipt_policy": "show_receipt",
                  "target_ref": "identity.signup_via_profile.signup_via_profile",
                  "view_action_key": "admit_identity"
                }
              ],
              "label": "Admit identity",
              "node_key": "submit",
              "node_kind": "button",
              "order": 0,
              "parent_node_key": "actions",
              "semantic_role": "action",
              "style_tokens": [
                {
                  "token_key": "emphasis",
                  "token_value": "primary"
                }
              ]
            },
            {
              "node_key": "receipt",
              "node_kind": "receipt",
              "order": 5,
              "parent_node_key": "root",
              "semantic_role": "receipt",
              "state_bindings": [
                {
                  "binding_key": "provenance_text",
                  "json_path": "\$.receipt.summary",
                  "state_attribute_config_id": "55befcab-aded-5996-81fa-0f6d30814cf7",
                  "state_attribute_ref": "provenance",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "provenance_visible",
                  "json_path": "\$.receipt.summary",
                  "state_attribute_config_id": "55befcab-aded-5996-81fa-0f6d30814cf7",
                  "state_attribute_ref": "provenance",
                  "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "receipt"
                }
              ]
            }
          ],
          "pane_config_id": "cd452f5c-c142-5042-81c8-15978d9900b5",
          "pane_kind": "identity_admission",
          "pane_name": "identity_admission",
          "projection_experience_view_id": "dc56874b-6991-5928-b7c1-30a8d3c38df2",
          "projection_view_key": "identity.admission.v1",
          "renderer_requirements": [
            {
              "capability_key": "column",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "row",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "box",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "field",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "section_header",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "text",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "status",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "text_input",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "button",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "component",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "receipt",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "view_action",
              "capability_kind": "action_binding",
              "is_required": true
            }
          ],
          "root_node_key": "root",
          "spec_id": "20ad3100-f032-5964-8b63-8e45207cba36",
          "spec_version": "0.1.0",
          "state_model_id": "db4bb457-27a8-5e83-af1f-7e6e009926d9",
          "view_ref": "aware_control_identity.identity.admission.v1"
        }
      ),
      PaneRenderSpec.fromJson(
        <String, dynamic>{
          "name": "network_territory_default",
          "nodes": [
            {
              "node_key": "root",
              "node_kind": "scroll",
              "order": 0,
              "semantic_role": "pane",
              "style_tokens": [
                {
                  "token_key": "density",
                  "token_value": "compact"
                }
              ]
            },
            {
              "node_key": "root.header",
              "node_kind": "row",
              "order": 0,
              "parent_node_key": "root",
              "semantic_role": "section"
            },
            {
              "node_key": "root.header.title",
              "node_kind": "text",
              "order": 0,
              "parent_node_key": "root.header",
              "semantic_role": "heading",
              "style_tokens": [
                {
                  "token_key": "emphasis",
                  "token_value": "primary"
                }
              ],
              "text": "Network territory"
            },
            {
              "node_key": "root.header.status",
              "node_kind": "status",
              "order": 1,
              "parent_node_key": "root.header",
              "semantic_role": "status",
              "state_bindings": [
                {
                  "binding_key": "status_text",
                  "fallback_value": "waiting",
                  "json_path": "\$.status",
                  "state_attribute_config_id": "fce7fb98-f0fd-5ede-883a-48f5d039c96b",
                  "state_attribute_ref": "status",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Summary",
              "node_key": "root.summary",
              "node_kind": "field",
              "order": 1,
              "parent_node_key": "root",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "summary_text",
                  "fallback_value": "Network nodes, environments, hosted services, and peers.",
                  "json_path": "\$.summary",
                  "state_attribute_config_id": "c451a165-4971-58f6-9022-982f489a6125",
                  "state_attribute_ref": "summary",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "action_bindings": [
                {
                  "action_key": "discover_territory",
                  "action_kind": "api",
                  "binding_key": "discover_territory",
                  "endpoint_ref": "network.discovery.discover_territory",
                  "event": "activate",
                  "label": "Refresh territory",
                  "projection_experience_view_invocation_action_id": "e2cc35a1-1f2e-59fe-b77e-bbb76a0ca74f",
                  "receipt_policy": "show_receipt",
                  "target_ref": "network.discovery.discover_territory",
                  "view_action_key": "discover_territory"
                }
              ],
              "label": "Refresh territory",
              "node_key": "root.refresh",
              "node_kind": "button",
              "order": 2,
              "parent_node_key": "root",
              "semantic_role": "action",
              "style_tokens": [
                {
                  "token_key": "emphasis",
                  "token_value": "primary"
                }
              ]
            },
            {
              "node_key": "root.error",
              "node_kind": "receipt",
              "order": 3,
              "parent_node_key": "root",
              "semantic_role": "receipt",
              "state_bindings": [
                {
                  "binding_key": "error_text",
                  "json_path": "\$.error",
                  "state_attribute_config_id": "7a124bc5-b081-5c87-b113-af379089754a",
                  "state_attribute_ref": "error",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "error_visible",
                  "json_path": "\$.error",
                  "state_attribute_config_id": "7a124bc5-b081-5c87-b113-af379089754a",
                  "state_attribute_ref": "error",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "warning"
                }
              ]
            },
            {
              "node_key": "root.empty_message",
              "node_kind": "text",
              "order": 4,
              "parent_node_key": "root",
              "semantic_role": "paragraph",
              "state_bindings": [
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.nodes",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "is_empty"
                },
                {
                  "binding_key": "empty_message_text",
                  "fallback_value": "No Network territory has been published yet",
                  "json_path": "\$.empty_message",
                  "state_attribute_config_id": "814fe8a0-b98a-5856-8e18-b0678189777d",
                  "state_attribute_ref": "empty_message",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Source",
              "node_key": "root.source",
              "node_kind": "field",
              "order": 5,
              "parent_node_key": "root",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "authority_source_url_text",
                  "json_path": "\$.authority_source_url",
                  "state_attribute_config_id": "1d3b16d1-023c-5f87-b116-0e4f6caceb2d",
                  "state_attribute_ref": "authority_source_url",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "authority_source_url_visible",
                  "json_path": "\$.authority_source_url",
                  "state_attribute_config_id": "1d3b16d1-023c-5f87-b116-0e4f6caceb2d",
                  "state_attribute_ref": "authority_source_url",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "muted"
                }
              ]
            },
            {
              "node_key": "root.nodes",
              "node_kind": "repeat",
              "order": 6,
              "parent_node_key": "root",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_items",
                  "json_path": "\$.nodes",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "items",
                  "transform": "raw"
                }
              ]
            },
            {
              "node_key": "root.nodes.card",
              "node_kind": "list_item",
              "order": 0,
              "parent_node_key": "root.nodes",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "unknown node",
                  "json_path": "\$.item.node.hostname",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.status",
              "node_kind": "status",
              "order": 0,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "status",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "active",
                  "json_path": "\$.item.node.status",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Route",
              "node_key": "root.nodes.card.route",
              "node_kind": "field",
              "order": 1,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "json_path": "\$.item.node.base_url",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.item.node.base_url",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "provenance"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.metrics",
              "node_kind": "row",
              "order": 2,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "section"
            },
            {
              "label": "environments",
              "node_key": "root.nodes.card.metrics.environments",
              "node_kind": "metric",
              "order": 0,
              "parent_node_key": "root.nodes.card.metrics",
              "semantic_role": "metric",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "0",
                  "json_path": "\$.item.environments",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "count"
                }
              ]
            },
            {
              "label": "services",
              "node_key": "root.nodes.card.metrics.services",
              "node_kind": "metric",
              "order": 1,
              "parent_node_key": "root.nodes.card.metrics",
              "semantic_role": "metric",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "0",
                  "json_path": "\$.item.hosted_services",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "count"
                }
              ]
            },
            {
              "label": "peers",
              "node_key": "root.nodes.card.metrics.peers",
              "node_kind": "metric",
              "order": 2,
              "parent_node_key": "root.nodes.card.metrics",
              "semantic_role": "metric",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "0",
                  "json_path": "\$.item.peers",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "count"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.environments_header",
              "node_kind": "section_header",
              "order": 3,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "heading",
              "state_bindings": [
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.item.environments",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "text": "Environments"
            },
            {
              "node_key": "root.nodes.card.environments",
              "node_kind": "repeat",
              "order": 4,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_items",
                  "json_path": "\$.item.environments",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "items",
                  "transform": "raw"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.environments.row",
              "node_kind": "list_item",
              "order": 0,
              "parent_node_key": "root.nodes.card.environments",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "environment",
                  "json_path": "\$.item.environment_title",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.environments.row.status",
              "node_kind": "status",
              "order": 0,
              "parent_node_key": "root.nodes.card.environments.row",
              "semantic_role": "status",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "active",
                  "json_path": "\$.item.status",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "Key",
              "node_key": "root.nodes.card.environments.row.key",
              "node_kind": "field",
              "order": 1,
              "parent_node_key": "root.nodes.card.environments.row",
              "semantic_role": "metadata",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "json_path": "\$.item.environment_key",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                },
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.item.environment_key",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "style_tokens": [
                {
                  "token_key": "tone",
                  "token_value": "provenance"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.services_header",
              "node_kind": "section_header",
              "order": 5,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "heading",
              "state_bindings": [
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.item.hosted_services",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "text": "Hosted services"
            },
            {
              "node_key": "root.nodes.card.hosted_services",
              "node_kind": "repeat",
              "order": 6,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_items",
                  "json_path": "\$.item.hosted_services",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "items",
                  "transform": "raw"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.hosted_services.row",
              "node_kind": "list_item",
              "order": 0,
              "parent_node_key": "root.nodes.card.hosted_services",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "service",
                  "json_path": "\$.item.service_name",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "label": "endpoints",
              "node_key": "root.nodes.card.hosted_services.row.endpoint_count",
              "node_kind": "metric",
              "order": 0,
              "parent_node_key": "root.nodes.card.hosted_services.row",
              "semantic_role": "metric",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "0",
                  "json_path": "\$.item.endpoint_refs",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "count"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.peers_header",
              "node_kind": "section_header",
              "order": 7,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "heading",
              "state_bindings": [
                {
                  "binding_key": "nodes_visible",
                  "json_path": "\$.item.peers",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "visible",
                  "transform": "not_empty"
                }
              ],
              "text": "Peers"
            },
            {
              "node_key": "root.nodes.card.peers",
              "node_kind": "repeat",
              "order": 8,
              "parent_node_key": "root.nodes.card",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_items",
                  "json_path": "\$.item.peers",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "items",
                  "transform": "raw"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.peers.row",
              "node_kind": "list_item",
              "order": 0,
              "parent_node_key": "root.nodes.card.peers",
              "semantic_role": "section",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "peer",
                  "json_path": "\$.item.peer_base_url",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            },
            {
              "node_key": "root.nodes.card.peers.row.status",
              "node_kind": "status",
              "order": 0,
              "parent_node_key": "root.nodes.card.peers.row",
              "semantic_role": "status",
              "state_bindings": [
                {
                  "binding_key": "nodes_text",
                  "fallback_value": "unknown",
                  "json_path": "\$.item.status",
                  "state_attribute_config_id": "64f96687-2c54-58bd-8658-11ac3afecf58",
                  "state_attribute_ref": "nodes",
                  "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
                  "target_property": "text",
                  "transform": "text"
                }
              ]
            }
          ],
          "pane_config_id": "d3d3e119-83c9-5bad-b76b-f864cd8cfcda",
          "pane_kind": "network_territory",
          "pane_name": "network_territory",
          "projection_experience_view_id": "44197134-7e41-5ecf-99ca-9df7627bfdca",
          "projection_view_key": "territory.discovery.v1",
          "renderer_requirements": [
            {
              "capability_key": "scroll",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "column",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "row",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "repeat",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "field",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "list_item",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "metric",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "section_header",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "status",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "button",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "receipt",
              "capability_kind": "node_kind",
              "is_required": true
            },
            {
              "capability_key": "view_action",
              "capability_kind": "action_binding",
              "is_required": true
            }
          ],
          "root_node_key": "root",
          "spec_id": "28bf28f5-4d1c-5cb4-a3c8-206f96c89d87",
          "spec_version": "0.1.0",
          "state_model_id": "93517332-19eb-5ea7-adef-839b28e2481a",
          "view_ref": "aware_network.territory.discovery.v1"
        }
      ),
    ],
    viewStateDecoderRegistry: InterfaceViewStateDecoderRegistry.fromDecoderMaps(
      <Map<String, InterfaceViewStateDecoder>>[
        <String, InterfaceViewStateDecoder>{
          "aware_hub.home.channel_heads.v1": aware_hub_service_api.HubPublicDiscoveryViewStateV1.fromJson,
          "home.channel_heads.v1": aware_hub_service_api.HubPublicDiscoveryViewStateV1.fromJson,
          "hub.channel_heads": aware_hub_service_api.HubPublicDiscoveryViewStateV1.fromJson,
          "aware_network.territory.discovery.v1": aware_network_service_api.NetworkTerritoryDiscoveryViewStateV1.fromJson,
          "territory.discovery.v1": aware_network_service_api.NetworkTerritoryDiscoveryViewStateV1.fromJson,
          "network.territory_discovery": aware_network_service_api.NetworkTerritoryDiscoveryViewStateV1.fromJson,
        },
      ],
    ),
    renderComponentRegistry: renderComponentRegistryBuilder.build(),
    panePackageRegistry: panePackageRegistry,
  );
}
